### ISSUE TITLE
=> ERROR [frontend internal] load metadata for docker.io/frappe/assets-builder:v13.28.0

### ISSUE THREAD

**Issue by lekhnath** [frappe/frappe_docker#1033]
I am getting following error message and couldnot resolve it.

> => ERROR [frontend internal] load metadata for docker.io/frappe/assets-builder:v13.28.0

** Full error message**
```
docker buildx bake
[+] Building 1.8s (10/10) FINISHED                                                                                                                                                            
 => [frontend internal] load build definition from frontend.Dockerfile                                                                                                                   0.0s
 => => transferring dockerfile: 374B                                                                                                                                                     0.0s
 => [backend internal] load build definition from backend.Dockerfile                                                                                                                     0.0s
 => => transferring dockerfile: 40B                                                                                                                                                      0.0s
 => [mariadb internal] load build definition from mariadb.Dockerfile                                                                                                                     0.0s
 => => transferring dockerfile: 246B                                                                                                                                                     0.0s
 => [frontend internal] load .dockerignore                                                                                                                                               0.1s
 => => transferring context: 2B                                                                                                                                                          0.0s
 => [mariadb internal] load .dockerignore                                                                                                                                                0.1s
 => => transferring context: 2B                                                                                                                                                          0.0s
 => [backend internal] load .dockerignore                                                                                                                                                0.1s
 => => transferring context: 2B                                                                                                                                                          0.0s
 => CANCELED [frontend internal] load metadata for docker.io/frappe/erpnext-nginx:v13.28.0                                                                                               1.7s
 => ERROR [frontend internal] load metadata for docker.io/frappe/assets-builder:v13.28.0                                                                                                 1.7s
 => CANCELED [mariadb internal] load metadata for docker.io/library/mariadb:10.6                                                                                                         1.7s
 => CANCELED [backend] resolve image config for docker.io/docker/dockerfile:1.3                                                                                                          1.6s
------
 > [frontend internal] load metadata for docker.io/frappe/assets-builder:v13.28.0:
------
ERROR: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
make: *** [Makefile:27: bake] Error 1
```

**Comment by lekhnath** [comment]
PS: It is in the production and I am scared

**Comment by revant** [comment]
- assets builder got deprecated because the script diverged from `bench build` and people were facing issues with built assets.
- I'll recommend using this file instead https://github.com/castlecraft/custom_frappe_docker/blob/main/images/frontend.Dockerfile
- I've added frappe/assets-builder:v13.28.0 for people who prefer to keep using it.
- I've pushed v13.46.2 as v13 as well. That can be used for anything v13.

**Comment by lekhnath** [comment]
Thank you very much @revant for bringing back the `assets-builder` image in docker hub. I am now getting following error :

```
Production mode
#24 15.78 internal/fs/utils.js:332
#24 15.78     throw err;
#24 15.78     ^
#24 15.78 
#24 15.78 Error: ENOENT: no such file or directory, mkdir '/frappe-bench/sites/assets/js'
#24 15.78     at Object.mkdirSync (fs.js:1014:3)
#24 15.78     at /frappe-bench/apps/frappe/rollup/build.js:171:7
#24 15.78     at Array.forEach (<anonymous>)
#24 15.78     at ensure_js_css_dirs (/frappe-bench/apps/frappe/rollup/build.js:169:8)
#24 15.78     at Object.<anonymous> (/frappe-bench/apps/frappe/rollup/build.js:39:1)
#24 15.78     at Module._compile (internal/modules/cjs/loader.js:1085:14)
#24 15.78     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
#24 15.78     at Module.load (internal/modules/cjs/loader.js:950:32)
#24 15.78     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
#24 15.78     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
#24 15.78     at internal/main/run_main_module.js:17:47 {
#24 15.78   errno: -2,
#24 15.78   syscall: 'mkdir',
#24 15.78   code: 'ENOENT',
#24 15.78   path: '/frappe-bench/sites/assets/js'
#24 15.78 }
#24 15.80 error Command failed with exit code 1.
#24 15.80 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by lekhnath** [comment]
@revant I also tried building from the Dockerfile you provided above but could no complete the build because of following error message:

```
check python checking for Python executable "python2" in the PATH
#0 153.5 gyp verb `which` failed Error: not found: python2
#0 153.5 gyp verb `which` failed     at getNotFoundError (/home/frappe/frappe-bench/apps/frappe/node_modules/which/which.js:13:12)
#0 153.5 gyp verb `which` failed     at F (/home/frappe/frappe-bench/apps/frappe/node_modules/which/which.js:68:19)
#0 153.5 gyp verb `which` failed     at E (/home/frappe/frappe-bench/apps/frappe/node_modules/which/which.js:80:29)
#0 153.5 gyp verb `which` failed     at /home/frappe/frappe-bench/apps/frappe/node_modules/which/which.js:89:16
#0 153.5 gyp verb `which` failed     at /home/frappe/frappe-bench/apps/frappe/node_modules/isexe/index.js:42:5
#0 153.5 gyp verb `which` failed     at /home/frappe/frappe-bench/apps/frappe/node_modules/isexe/mode.js:8:5
#0 153.5 gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21)
#0 153.5 gyp verb `which` failed  python2 Error: not found: python2
#0 153.5 gyp verb `which` failed     at getNotFoundError (/home/frappe/frappe-bench/apps/frappe/node_modules/which/which.js:13:12)
#0 153.5 gyp verb `which` failed     at F (/home/frappe/frappe-bench/apps/frappe/node_modules/which/which.js:68:19)
#0 153.5 gyp verb `which` failed     at E (/home/frappe/frappe-bench/apps/frappe/node_modules/which/which.js:80:29)
#0 153.5 gyp verb `which` failed     at /home/frappe/frappe-bench/apps/frappe/node_modules/which/which.js:89:16
#0 153.5 gyp verb `which` failed     at /home/frappe/frappe-bench/apps/frappe/node_modules/isexe/index.js:42:5
#0 153.5 gyp verb `which` failed     at /home/frappe/frappe-bench/apps/frappe/node_modules/isexe/mode.js:8:5
#0 153.5 gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:202:21) {
#0 153.5 gyp verb `which` failed   code: 'ENOENT'
#0 153.5 gyp verb `which` failed }
#0 153.5 gyp verb check python checking for Python executable "python" in the PATH
#0 153.5 gyp verb `which` succeeded python /home/frappe/.pyenv/shims/python
#0 153.5 gyp ERR! configure error 
#0 153.5 gyp ERR! stack Error: Command failed: /home/frappe/.pyenv/shims/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
#0 153.5 gyp ERR! stack   File "<string>", line 1
#0 153.5 gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
#0 153.5 gyp ERR! stack                       ^
#0 153.5 gyp ERR! stack SyntaxError: invalid syntax
#0 153.5 gyp ERR! stack 
#0 153.5 gyp ERR! stack     at ChildProcess.exithandler (node:child_process:402:12)
#0 153.5 gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
#0 153.5 gyp ERR! stack     at maybeClose (node:internal/child_process:1100:16)
#0 153.5 gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
#0 153.5 gyp ERR! System Linux 5.15.0-56-generic
#0 153.5 gyp ERR! command "/home/frappe/.nvm/versions/node/v16.18.0/bin/node" "/home/frappe/frappe-bench/apps/frappe/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
#0 153.5 gyp ERR! cwd /home/frappe/frappe-bench/apps/frappe/node_modules/node-sass
#0 153.5 gyp ERR! node -v v16.18.0
#0 153.5 gyp ERR! node-gyp -v v3.8.0
#0 153.5 gyp ERR! not ok 
#0 153.5 Build failed with error code: 1
#0 153.5 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#0 154.5 Traceback (most recent call last):
#0 154.5   File "/home/frappe/.bench/bench/commands/make.py", line 68, in init
#0 154.5     init(
#0 154.5   File "/home/frappe/.bench/bench/utils/render.py", line 105, in wrapper_fn
#0 154.5     return fn(*args, **kwargs)
#0 154.5   File "/home/frappe/.bench/bench/utils/system.py", line 79, in init
#0 154.5     get_app(
#0 154.5   File "/home/frappe/.bench/bench/app.py", line 444, in get_app
#0 154.5     app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
#0 154.5   File "/home/frappe/.bench/bench/utils/render.py", line 126, in wrapper_fn
#0 154.5     return fn(*args, **kwargs)
#0 154.5   File "/home/frappe/.bench/bench/app.py", line 242, in install
#0 154.5     install_app(
#0 154.5   File "/home/frappe/.bench/bench/app.py", line 581, in install_app
#0 154.5     bench.run("yarn install", cwd=app_path)
#0 154.5   File "/home/frappe/.bench/bench/bench.py", line 48, in run
#0 154.5     return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
#0 154.5   File "/home/frappe/.bench/bench/utils/__init__.py", line 158, in exec_cmd
#0 154.5     raise CommandFailedError
#0 154.5 bench.exceptions.CommandFailedError
#0 154.5 
#0 154.5 ERROR: There was a problem while creating /home/frappe/frappe-bench
#0 154.5 Do you want to rollback these changes? [y/N]: Aborted!
------
ERROR: failed to solve: executor failed running [/bin/sh -c PYENV_VERSION=${PYTHON_VERSION} bench init --version=${FRAPPE_VERSION} --skip-redis-config-generation --verbose --skip-assets /home/frappe/frappe-bench]: exit code: 1
make: *** [Makefile:27: bake] Error 
```

**Comment by revant** [comment]
update the file again

https://github.com/frappe/frappe_docker/blob/main/images/nginx/Dockerfile

added following section

```Dockerfile
ARG NODE_VERSION
ENV NVM_DIR=/home/frappe/.nvm
ENV PATH ${NVM_DIR}/versions/node/v${NODE_VERSION}/bin/:${PATH}
```

Specify build arg `NODE_VERSION`, for v13 it takes `v14.19.3`

**Comment by lekhnath** [comment]
@revant How should I install custom apps? Previously I was able to install my custom apps using `install-app` command but now it says :

```
#0 0.342 /bin/sh: 1: install-app: not found

```

**Comment by lekhnath** [comment]
Also, I've to add `ARG ERPNEXT_VERSION` once again below `FROM frappe/bench:latest as assets` after `ARG FRAPPE_VERSION`   to install the specific version of erpnext instead of the latest one:

**Comment by revant** [comment]
https://github.com/castlecraft/custom_frappe_docker/blob/main/images/frontend.Dockerfile

copy this over your frontend file. it does everything.
