### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'frappe-bench'

### ISSUE THREAD

**Issue by diaruys** [frappe/frappe_docker#1043]
Hi, this is my first time installing frappe on docker. I have no experience whatsoever relating to this so here I am.

After opening frappe_docker on VSCode and running the command: `bench init --skip-redis-config-generation --frappe-branch version-14 frappe-bench` from the terminal in vscode, I got the following error:

`
frappe@51cc9b6745b3:/workspace/development$ bench init --skip-redis-config-generation --frappe-branch version-14 frappe-bench
Traceback (most recent call last):
  File "/home/frappe/.bench/bench/commands/make.py", line 68, in init
    init(
  File "/home/frappe/.bench/bench/utils/render.py", line 105, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.bench/bench/utils/system.py", line 63, in init
    bench.setup.dirs()
  File "/home/frappe/.bench/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.bench/bench/bench.py", line 337, in dirs
    os.makedirs(self.bench.name, exist_ok=True)
  File "/home/frappe/.pyenv/versions/3.10.5/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: 'frappe-bench'
`

I've tried creating the file manually on `/home/frappe/` and I've also tried running `chmod -R frappe:frappe` on the frappe folder but still receive the same error.

**Comment by join2nk** [comment]
> Nevermind! I've found the solution!
> 
> All I need to do was run the command `chown frappe:frappe /workspace/development/` and the re-run `bench init --skip-redis-config-generation --frappe-branch version-14 frappe-bench`.
> 
> Apologies to everyone especially the owner for creating unnecessary issue.

thanks
