### ISSUE TITLE
Database Error on Creating First Site during Docker Compose Installation  

### ISSUE THREAD

**Issue by xbiggyl** [frappe/frappe_docker#1056]
## Description of the issue

This issue has been described in this closed issue here and I tried to comment but no reply:

https://github.com/frappe/frappe_docker/issues/1009

I am getting the same error as in the issue above, after multiple tries and starting from scratch each time.

`pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'172.27.0.8' (using password: YES)"`

## Context information (for bug reports)

I am trying to setup ERPnext on a dedicated server running Ubuntu 20.04 by following the single server docker installation instructions here:

https://github.com/frappe/frappe_docker/blob/main/docs/single-server-example.md

I am also following the Port Based Multiple Tenancy instructions here:

https://github.com/frappe/frappe_docker/blob/main/docs/port-based-multi-tenancy.md

## Steps to reproduce the issue

By following the instructions to the letter I receive the above mentioned error when I run the following command (I replaced the changeit with the corresponding password):

```
docker compose --project-name erpnext-one exec backend \
  bench new-site one.example.com --no-mariadb-socket --mariadb-root-password changeit --install-app erpnext --admin-password changeit
```

### Stacktrace / full error message if available

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 74, in new_site
    _new_site(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 80, in _new_site
    install_db(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 156, in install_db
    setup_database(force, source_sql, verbose, no_mariadb_socket)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/__init__.py", line 20, in setup_database
    return frappe.database.mariadb.setup_db.setup_database(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/setup_db.py", line 41, in setup_database
    if force or (db_name not in dbman.get_database_list()):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/db_manager.py", line 49, in get_database_list
    return self.db.sql("SHOW DATABASES", pluck=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 199, in sql
    self.connect()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 113, in connect
    self._conn = self.get_connection()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 98, in get_connection
    conn = self._get_connection()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 104, in _get_connection
    return self.create_connection()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'172.27.0.8' (using password: YES)")
```

### Additional Info

I even tried the following troubleshooting instructions:

https://github.com/frappe/frappe_docker/blob/main/docs/troubleshoot.md#fixing-mariadb-issues-after-rebuilding-the-container

But I keep getting the error. The site folder is created is:

/var/lib/docker/volumes/erpnext-one_sites/_data

But no DB entry in mariadb, not even a mariadb database is created.

This is the result from `SHOW DATABASES;`

```
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
```

### The erpnext-one.yaml file after removing the Traefik stuff and adding the port-site-1 and port-site-2 (as per [this](https://github.com/frappe/frappe_docker/blob/main/docs/port-based-multi-tenancy.md))

```
name: erpnext-one
services:
  backend:
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext:v14.13.0
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  configurator:
    command:
    - |
      bench set-config -g db_host $$DB_HOST; bench set-config -gp db_port $$DB_PORT; bench set-config -g redis_cache "redis://$$REDIS_CACHE"; bench set-config -g redis_queue "redis://$$REDIS_QUEUE"; bench set-config -g redis_socketio "redis://$$REDIS_SOCKETIO"; bench set-config -gp socketio_port $$SOCKETIO_PORT;
    depends_on:
      redis-cache:
        condition: service_started
      redis-queue:
        condition: service_started
      redis-socketio:
        condition: service_started
    entrypoint:
    - bash
    - -c
    environment:
      DB_HOST: mariadb-database
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      REDIS_SOCKETIO: redis-socketio:6379
      SOCKETIO_PORT: "9000"
    image: frappe/erpnext:v14.13.0
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  frontend:
    command:
    - nginx-entrypoint.sh
    depends_on:
      backend:
        condition: service_started
      websocket:
        condition: service_started
    environment:
      BACKEND: backend:8000
      CLIENT_MAX_BODY_SIZE: 50m
      FRAPPE_SITE_NAME_HEADER: $$host
      PROXY_READ_TIMOUT: "120"
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    image: frappe/erpnext:v14.13.0
    networks:
      bench-network: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  queue-default:
    command:
    - bench
    - worker
    - --queue
    - default
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext:v14.13.0
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  queue-long:
    command:
    - bench
    - worker
    - --queue
    - long
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext:v14.13.0
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  queue-short:
    command:
    - bench
    - worker
    - --queue
    - short
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext:v14.13.0
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  redis-cache:
    image: redis:6.2-alpine
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
    - type: volume
      source: redis-cache-data
      target: /data
      volume: {}
  redis-queue:
    image: redis:6.2-alpine
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
    - type: volume
      source: redis-queue-data
      target: /data
      volume: {}
  redis-socketio:
    image: redis:6.2-alpine
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
    - type: volume
      source: redis-socketio-data
      target: /data
      volume: {}
  scheduler:
    command:
    - bench
    - schedule
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext:v14.13.0
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  websocket:
    command:
    - node
    - /home/frappe/frappe-bench/apps/frappe/socketio.js
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext:v14.13.0
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  port-site-1:
    image: frappe/erpnext:v14.13.0
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: erp.nameofmysite.me
      SOCKETIO: websocket:9000
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    ports:
      - "8081:8080"
  port-site-2:
    image: frappe/erpnext:v14.13.0
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: erp2.nameofmysite.me
      SOCKETIO: websocket:9000
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    ports:
      - "8082:8080"  
networks:
  bench-network:
    name: erpnext-one
  mariadb-network:
    name: mariadb-network
    external: true
volumes:
  redis-cache-data:
    name: erpnext-one_redis-cache-data
  redis-queue-data:
    name: erpnext-one_redis-queue-data
  redis-socketio-data:
    name: erpnext-one_redis-socketio-data
  sites:
    name: erpnext-one_sites
x-backend-defaults:
  depends_on:
    configurator:
      condition: service_completed_successfully
  image: frappe/erpnext:v14.13.0
  volumes:
  - sites:/home/frappe/frappe-bench/sites
x-depends-on-configurator:
  depends_on:
    configurator:
      condition: service_completed_successfully
```

**Comment by sdfateh** [comment]
Where is your MariaDB service?

**Comment by revant** [comment]
> `pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'172.27.0.8' (using password: YES)"`

new-site command needs root access, it suggests root password for mariadb used was not correct

This may occur if mariadb container failed to setup the root password during initialization process. Healthcheck for the mariadb service may have failed and it restarted the service interrupting the root password setup process.

Remove the healthchecks and try again fresh (prune volumes for mariadb which has misconfigured data)

**Comment by xbiggyl** [comment]
> > `pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'172.27.0.8' (using password: YES)"`
> 
> new-site command needs root access, it suggests root password for mariadb used was not correct
> 
> This may occur if mariadb container failed to setup the root password during initialization process. Healthcheck for the mariadb service may have failed and it restarted the service interrupting the root password setup process.
> 
> Remove the healthchecks and try again fresh (prune volumes for mariadb which has misconfigured data)

After deploying compose.mariadb-shared.yaml, using terminal in portainer I can successfully login to mysql using root and the password I used in the .env file.

I also tried to prune the healthcheck to no avail.

I'm still receiving the same error.

Here are the logs from the mariadb container:

```
2023-01-25 17:44:52+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.11+maria~ubu2004 started.
2023-01-25 17:44:53+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2023-01-25 17:44:53+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.11+maria~ubu2004 started.
2023-01-25 17:44:53+00:00 [Note] [Entrypoint]: MariaDB upgrade not required
2023-01-25 17:44:53 0 [Note] mariadbd (server 10.6.11-MariaDB-1:10.6.11+maria~ubu2004) starting as process 1 ...
2023-01-25 17:44:53 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2023-01-25 17:44:53 0 [Note] InnoDB: Number of pools: 1
2023-01-25 17:44:53 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2023-01-25 17:44:53 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
2023-01-25 17:44:53 0 [Note] InnoDB: Using Linux native AIO
2023-01-25 17:44:53 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
2023-01-25 17:44:53 0 [Note] InnoDB: Completed initialization of buffer pool
2023-01-25 17:44:53 0 [Note] InnoDB: Starting crash recovery from checkpoint LSN=31799078,31799078
2023-01-25 17:44:53 0 [Note] InnoDB: 128 rollback segments are active.
2023-01-25 17:44:53 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
2023-01-25 17:44:53 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2023-01-25 17:44:53 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2023-01-25 17:44:53 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2023-01-25 17:44:53 0 [Note] InnoDB: 10.6.11 started; log sequence number 31799090; transaction id 9300
2023-01-25 17:44:53 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2023-01-25 17:44:53 0 [Note] Plugin 'FEEDBACK' is disabled.
2023-01-25 17:44:53 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
2023-01-25 17:44:53 0 [Note] Server socket created on IP: '0.0.0.0'.
2023-01-25 17:44:53 0 [Note] Server socket created on IP: '::'.
2023-01-25 17:44:53 0 [Note] InnoDB: Buffer pool(s) load completed at 230125 17:44:53
2023-01-25 17:44:53 0 [Note] mariadbd: ready for connections.
Version: '10.6.11-MariaDB-1:10.6.11+maria~ubu2004'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2023-01-25 17:46:52 3 [Warning] Access denied for user 'frappe'@'192.168.48.7' (using password: NO)
2023-01-25 17:46:52 4 [Warning] Access denied for user 'root'@'192.168.48.7' (using password: YES)
2023-01-25 17:47:41 6 [Warning] Access denied for user '_f1493c8ae8a042aa'@'192.168.48.11' (using password: YES)
2023-01-25 17:48:41 7 [Warning] Access denied for user '_f1493c8ae8a042aa'@'192.168.48.11' (using password: YES)
2023-01-25 17:49:41 8 [Warning] Access denied for user '_f1493c8ae8a042aa'@'192.168.48.11' (using password: YES)
2023-01-25 17:50:42 9 [Warning] Access denied for user '_f1493c8ae8a042aa'@'192.168.48.11' (using password: YES)
```

The following username `_f1493c8ae8a042aa` is in the site_config.json in the volume created by erpnext

Is it supposed to be using this username?

**Comment by revant** [comment]
I don't know how to debug it, I'm not able to reproduce it locally, on tests or on PWD.

If anyone faced it and solved it may help you.

**Comment by xbiggyl** [comment]
> I don't know how to debug it, I'm not able to reproduce it locally, on tests or on PWD.
> 
> If anyone faced it and solved it may help you.

Did you try setting it up without Traefik. Because I'm following the multi tenancy setup

**Comment by revant** [comment]
I've setup multiple swarm instances recently didn't face issue.

i do integration tests where i deploy in-cluster Mariadb setup, that also works for frappe/helm tests.

if you find any fixes send PR.

**Comment by revant** [comment]
make sure your password doesn't contain `&`, `#`, `>`, `<`, `|` or anything that triggers shell command or pipe.
if that is use make sure you quote or escape it.

**Comment by xbiggyl** [comment]
> make sure your password doesn't contain `&`, `#`, `>`, `<`, `|` or anything that triggers shell command or pipe. if that is used, make sure you quote or escape it.

I tried it with a password containing @ and another time I set the password to 123.

The same error seems to be raised when following the Docker Swarm instructions rather than the single server:

https://discuss.frappe.io/t/erpnext-13-docker-ubuntu-22-04-jan-2023/100220/13?u=t33ks

**Comment by revant** [comment]
if you can share access to server where you've reproduced issues I'll check 

use my GitHub account public key

**Comment by xbiggyl** [comment]
Solved it!

The mariadb compose file used in the single server instructions (compose.mariadb-shared,yaml) has the following line:

```
    volumes:
      - ${HOME}/data/mariadb:/var/lib/mysql
```

Therefore, I had to delete this directory and redeploy the mariadb container:

~/data/mariadb:/var/lib/mysql

It appears that the mariadb container is using data from that folder.

I'm not sure but maybe if the following code is included in compose.mariadb-shared,yaml under environment:

`MARIADB_ROOT_PASSWORD: ${DB_PASSWORD:-changeit}`

This could override the data from the folder. I haven't tested it yet, but IMO this line should be added anyway, since only the MYSQL_ROOT_PASSWORD is included in the compose  file.

**Comment by revant** [comment]
I'll remove all bind mounts and use docker volumes.

I searched them and found in compose.traefik-ssl.yaml and compose.mariadb-shared.yaml

Rest all files are using docker `volumes:`

Can you try that out? SSL is also causing problems for people.

**Comment by xbiggyl** [comment]
> I'll remove all bind mounts and use docker volumes.
> 
> I searched them and found in compose.traefik-ssl.yaml and compose.mariadb-shared.yaml
> 
> Rest all files are using docker `volumes:`
> 
> Can you try that out? SSL is also causing problems for people.
> 
> test this PR #1067

I don't have access atm, I will test it asap and get back to you
