### ISSUE TITLE
Frappe runtime error

### ISSUE THREAD

**Issue by lijie97** [frappe/frappe_docker#1084]
## Description of the issue
![图片](https://user-images.githubusercontent.com/25693161/222382987-bcea1937-405c-4596-9781-8ac29730085e.png)

## Steps to reproduce the issue

1. clone the repo
2. using Docker Compose version v2.6.1
3. `cp example.env .env`, without change anything
4. `sudo docker-compose -f compose.yaml -f overrides/compose.redis.yaml -f overrides/compose.noproxy.yaml -f overrides/compose.mariadb.yaml up -d`

### Observed result
Docker status seems good.

```
lijie@lijie:~/frappe_docker$ sudo docker-compose ps
NAME                             COMMAND                  SERVICE             STATUS              PORTS
frappe_docker-backend-1          "/home/frappe/frappe…"   backend             running             
frappe_docker-configurator-1     "bash -c 'ls -1 apps…"   configurator        exited (0)          
frappe_docker-db-1               "docker-entrypoint.s…"   db                  running (healthy)   3306/tcp
frappe_docker-frontend-1         "nginx-entrypoint.sh"    frontend            running             0.0.0.0:8080->8080/tcp, :::8080->8080/tcp
frappe_docker-queue-default-1    "bench worker --queu…"   queue-default       running             
frappe_docker-queue-long-1       "bench worker --queu…"   queue-long          running             
frappe_docker-queue-short-1      "bench worker --queu…"   queue-short         running             
frappe_docker-redis-cache-1      "docker-entrypoint.s…"   redis-cache         running             6379/tcp
frappe_docker-redis-queue-1      "docker-entrypoint.s…"   redis-queue         running             6379/tcp
frappe_docker-redis-socketio-1   "docker-entrypoint.s…"   redis-socketio      running             6379/tcp
frappe_docker-scheduler-1        "bench schedule"         scheduler           running             
frappe_docker-websocket-1        "node /home/frappe/f…"   websocket           running             
```

The log of backend shows
```
lijie@lijie:~/frappe_docker$ sudo docker logs frappe_docker-backend-1
[2023-03-02 09:00:09 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-03-02 09:00:09 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2023-03-02 09:00:09 +0000] [1] [INFO] Using worker: gthread
[2023-03-02 09:00:09 +0000] [7] [INFO] Booting worker with pid: 7
[2023-03-02 09:00:09 +0000] [8] [INFO] Booting worker with pid: 8
[2023-03-02 09:01:34 +0000] [8] [ERROR] Error handling request /?vscodeBrowserReqId=1677747693492
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 323, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/werkzeug/local.py", line 237, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 194, in application
    resp = f(*args[:-2] + (request,))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 93, in application
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1495, in get_hooks
    if conf.developer_mode:
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/werkzeug/local.py", line 495, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: object is not bound
[2023-03-02 09:01:41 +0000] [7] [ERROR] Error handling request /?vscodeBrowserReqId=1677747701575
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 323, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/werkzeug/local.py", line 237, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 194, in application
    resp = f(*args[:-2] + (request,))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 93, in application
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1495, in get_hooks
    if conf.developer_mode:
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/werkzeug/local.py", line 495, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: object is not bound
[2023-03-02 09:01:46 +0000] [8] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 323, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/werkzeug/local.py", line 237, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 194, in application
    resp = f(*args[:-2] + (request,))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 93, in application
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1495, in get_hooks
    if conf.developer_mode:
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/werkzeug/local.py", line 495, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: object is not bound
[2023-03-02 09:01:46 +0000] [8] [ERROR] Error handling request /favicon.ico
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 323, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/werkzeug/local.py", line 237, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 194, in application
    resp = f(*args[:-2] + (request,))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 93, in application
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1495, in get_hooks
    if conf.developer_mode:
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/werkzeug/local.py", line 316, in __get__
    obj = instance._get_current_object()
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/werkzeug/local.py", line 495, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: object is not bound
```

### Expected result
Enter the site app normally.

**Comment by revant** [comment]
- create your first site before entering it.
- copy pasting env will not work, it has example.com sites and email address that don't work with letsencrypt.

**Comment by lijie97** [comment]
@revant I have not used letsencrypt.
```
sudo docker-compose -f compose.yaml -f overrides/compose.redis.yaml -f overrides/compose.noproxy.yaml -f overrides/compose.mariadb.yaml up -d
```
I haven't added *compose.https.yaml* for https.

**Comment by revant** [comment]
have you created first site?

**Comment by revant** [comment]
you'll have to rediscover like everyone that Host header and site name should match
