### ISSUE TITLE
pull access denied for vsc-frappe_docker

### ISSUE THREAD

**Issue by smmitc** [frappe/frappe_docker#1092]
## Description of the issue
I followed the [instructions](https://github.com/frappe/frappe_docker/blob/main/docs/development.md) to setup Containers for development:

But then, after "Reopen in Container" I get this error:
```
[2023-03-07T07:12:51.247Z] Error response from daemon: pull access denied for vsc-frappe_docker-4198a55a028ad12504c7bdfdc5c9e20f-uid, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"
```

## Context information (for bug reports)
```
[2023-03-07T07:12:51.151Z] [+] Running 0/1
[2023-03-07T07:12:51.152Z]  ⠹ frappe Pulling                                                          1.3s
[2023-03-07T07:12:51.246Z] 
[2023-03-07T07:12:51.247Z] [+] Running 0/1
[2023-03-07T07:12:51.247Z]  ⠿ frappe Error                                                            1.4s
[2023-03-07T07:12:51.247Z] Error response from daemon: pull access denied for vsc-frappe_docker-4198a55a028ad12504c7bdfdc5c9e20f-uid, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
[2023-03-07T07:12:51.467Z] Stop (1656 ms): Run: docker-compose --project-name frappe_docker_devcontainer -f /home/smmitc/workspace/frappe/frappe_docker/.devcontainer/docker-compose.yml -f /home/smmitc/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1660026295151.yml up -d --no-recreate
[2023-03-07T07:12:51.468Z] Error: Command failed: docker-compose --project-name frappe_docker_devcontainer -f /home/smmitc/workspace/frappe/frappe_docker/.devcontainer/docker-compose.yml -f /home/smmitc/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1660026295151.yml up -d --no-recreate
[2023-03-07T07:12:51.468Z]     at sie (/home/smmitc/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js:1896:3061)
[2023-03-07T07:12:51.468Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-03-07T07:12:51.468Z]     at async iie (/home/smmitc/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js:1878:2396)
[2023-03-07T07:12:51.469Z]     at async xie (/home/smmitc/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js:1945:2798)
[2023-03-07T07:12:51.469Z]     at async Wf (/home/smmitc/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js:1945:3750)
[2023-03-07T07:12:51.469Z]     at async noe (/home/smmitc/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js:2069:17325)
[2023-03-07T07:12:51.469Z]     at async roe (/home/smmitc/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js:2069:17066)
[2023-03-07T07:12:51.481Z] Stop (2124 ms): Run: /snap/code/120/usr/share/code/code --ms-enable-electron-run-as-node /home/smmitc/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/smmitc/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-be83f469-8a67-492e-bf23-4149407497601678173168302 --workspace-folder /home/smmitc/workspace/frappe/frappe_docker --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/smmitc/workspace/frappe/frappe_docker --id-label devcontainer.config_file=/home/smmitc/workspace/frappe/frappe_docker/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/smmitc/workspace/frappe/frappe_docker/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-03-07T07:12:51.481Z] Exit code 1
[2023-03-07T07:12:51.485Z] Command failed: /snap/code/120/usr/share/code/code --ms-enable-electron-run-as-node /home/smmitc/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/smmitc/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-be83f469-8a67-492e-bf23-4149407497601678173168302 --workspace-folder /home/smmitc/workspace/frappe/frappe_docker --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/smmitc/workspace/frappe/frappe_docker --id-label devcontainer.config_file=/home/smmitc/workspace/frappe/frappe_docker/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/smmitc/workspace/frappe/frappe_docker/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-03-07T07:12:51.485Z] Exit code 1
```

## Steps to reproduce the issue
```
git clone https://github.com/frappe/frappe_docker.git
cd frappe_docker
cp -R devcontainer-example .devcontainer
cp -R development/vscode-example development/.vscode
code .
```
Click "Reopen in Container".

### Observed result
```
Visual Studio Code
An error occurred setting up the container.
- Edit devcontainer.json locally
- More Actions...
- Retry
```

### Expected result
containers are started

**Comment by smmitc** [comment]
The error was caused by old configuration in `/home/smmitc/.config/Code`. Deleting the directory solved the problem.
