### ISSUE TITLE
Unable to build dev-container  

### ISSUE THREAD

**Issue by shikharx06** [frappe/frappe_docker#1106]
Hi, I am trying to build devcontainer in a remote aws-ec2 instance via my windows machine and it keeps throwing `ERROR: .FileNotFoundError: [Errno 2]`. 

This is my devcontainer build log.

```
[2023-03-19T18:56:09.550Z] Dev Containers 0.282.0 in VS Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884).
[2023-03-19T18:56:09.550Z] Start: Resolving Remote
[2023-03-19T18:56:09.770Z] Start: Run: ssh -F C:\Users\shikh\.ssh\config 13.232.94.88 /bin/sh
[2023-03-19T18:56:09.834Z] Start: Run in host: id -un
[2023-03-19T18:56:11.103Z] ubuntu
[2023-03-19T18:56:11.104Z] 
[2023-03-19T18:56:11.104Z] Stop (1270 ms): Run in host: id -un
[2024-03-19T18:56:11.105Z] Start: Run in host: cat /etc/passwd
[2023-03-19T18:56:11.146Z] Stop (41 ms): Run in host: cat /etc/passwd
[2023-03-19T18:56:11.148Z] Start: Run in host: echo ~
[2023-03-19T18:56:11.186Z] /home/ubuntu
[2023-03-19T18:56:11.187Z] 
[2023-03-19T18:56:11.188Z] Stop (40 ms): Run in host: echo ~
[2023-03-19T18:56:11.192Z] Start: Run in host: test -x '/home/ubuntu/.vscode-remote-containers/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/node'
[2023-03-19T18:56:11.235Z] 
[2023-03-19T18:56:11.236Z] 
[2023-03-19T18:56:11.236Z] Exit code 1
[2023-03-19T18:56:11.236Z] Stop (44 ms): Run in host: test -x '/home/ubuntu/.vscode-remote-containers/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/node'
[2023-03-19T18:56:11.239Z] Start: Run in host: test -x '/home/ubuntu/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/node'
[2023-03-19T18:56:11.276Z] 
[2023-03-19T18:56:11.276Z] 
[2023-03-19T18:56:11.277Z] Stop (38 ms): Run in host: test -x '/home/ubuntu/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/node'
[2023-03-19T18:56:11.277Z] Start: Run in host: test -f '/home/ubuntu/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/node_modules/node-pty/package.json'
[2023-03-19T18:56:11.315Z] 
[2023-03-19T18:56:11.315Z] 
[2023-03-19T18:56:11.316Z] Stop (39 ms): Run in host: test -f '/home/ubuntu/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/node_modules/node-pty/package.json'
[2023-03-19T18:56:11.316Z] Start: Run in host: test -f '/home/ubuntu/.vscode-remote-containers/dist/vscode-remote-containers-server-0.282.0.js'
[2023-03-19T18:56:11.359Z] 
[2023-03-19T18:56:11.359Z] 
[2023-03-19T18:56:11.359Z] Stop (43 ms): Run in host: test -f '/home/ubuntu/.vscode-remote-containers/dist/vscode-remote-containers-server-0.282.0.js'
[2023-03-19T18:56:11.403Z] userEnvProbe: loginInteractiveShell (default)
[2023-03-19T18:56:11.404Z] userEnvProbe: not found in cache
[2023-03-19T18:56:11.405Z] userEnvProbe shell: /bin/bash
[2023-03-19T18:56:11.542Z] userEnvProbe PATHs:
Probe:     '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
Container: None
[2023-03-19T18:56:11.589Z] Setting up container for folder or workspace: /home/ubuntu/frappe_docker
[2023-03-19T18:56:11.590Z] Host: ssh://13.232.94.88
[2023-03-19T18:56:11.593Z] Start: Run: wsl -l -v
[2023-03-19T18:56:11.743Z] Stop (150 ms): Run: wsl -l -v
[2023-03-19T18:56:11.747Z] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c echo ~
[2023-03-19T18:56:12.014Z] Stop (267 ms): Run: wsl -d Ubuntu-20.04 -e /bin/sh -c echo ~
[2023-03-19T18:56:12.017Z] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/sinewolf' && /bin/sh
[2023-03-19T18:56:12.032Z] Start: Run in host: id -un
[2023-03-19T18:56:12.146Z] sinewolf
[2023-03-19T18:56:12.147Z] 
[2023-03-19T18:56:12.148Z] Stop (116 ms): Run in host: id -un
[2023-03-19T18:56:12.148Z] Start: Run in host: cat /etc/passwd
[2023-03-19T18:56:12.152Z] Stop (4 ms): Run in host: cat /etc/passwd
[2023-03-19T18:56:12.153Z] Start: Run in host: echo ~
[2023-03-19T18:56:12.157Z] /home/sinewolf
[2023-03-19T18:56:12.158Z] 
[2023-03-19T18:56:12.158Z] Stop (5 ms): Run in host: echo ~
[2023-03-19T18:56:12.158Z] Start: Run in host: test -x '/home/sinewolf/.vscode-remote-containers/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/node'
[2023-03-19T18:56:12.162Z] 
[2023-03-19T18:56:12.163Z] 
[2023-03-19T18:56:12.163Z] Stop (5 ms): Run in host: test -x '/home/sinewolf/.vscode-remote-containers/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/node'
[2023-03-19T18:56:12.163Z] Start: Run in host: test -f '/home/sinewolf/.vscode-remote-containers/dist/vscode-remote-containers-server-0.282.0.js'
[2023-03-19T18:56:12.165Z] 
[2023-03-19T18:56:12.165Z] 
[2023-03-19T18:56:12.165Z] Stop (2 ms): Run in host: test -f '/home/sinewolf/.vscode-remote-containers/dist/vscode-remote-containers-server-0.282.0.js'
[2023-03-19T18:56:12.166Z] userEnvProbe: loginInteractiveShell (default)
[2023-03-19T18:56:12.167Z] userEnvProbe: not found in cache
[2023-03-19T18:56:12.167Z] userEnvProbe shell: /usr/bin/zsh
[2023-03-19T18:56:12.529Z] userEnvProbe PATHs:
Probe:     '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/flutter/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/Java/jdk-15.0.2/bin:/mnt/c/Program Files/dotnet/:/Docker/host/bin:/mnt/c/Users/shikh/AppData/Local/Microsoft/WindowsApps:/mnt/c/flutter/bin:/mnt/c/Program Files/Java/jdk-15.0.2/bin:/mnt/c/Program Files/Apache Software Foundation/Tomcat 9.0/bin:/mnt/c/Users/shikh/AppData/Local/Programs/Microsoft VS Code/bin'
Container: None
[2023-03-19T18:56:12.534Z] Start: Check Docker is running
[2023-03-19T18:56:12.535Z] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[2023-03-19T18:56:12.665Z] Stop (130 ms): Run in Host: docker version --format {{.Server.APIVersion}}
[2023-03-19T18:56:12.666Z] Server API version: 1.41
[2023-03-19T18:56:12.666Z] Stop (132 ms): Check Docker is running
[2023-03-19T18:56:12.667Z] Start: Run in Host: docker volume ls -q
[2023-03-19T18:56:12.810Z] Stop (143 ms): Run in Host: docker volume ls -q
[2023-03-19T18:56:12.811Z] Start: Run in Host: docker ps -q -a --filter label=vsch.local.folder=/home/ubuntu/frappe_docker --filter label=vsch.quality=stable
[2023-03-19T18:56:12.927Z] Stop (116 ms): Run in Host: docker ps -q -a --filter label=vsch.local.folder=/home/ubuntu/frappe_docker --filter label=vsch.quality=stable
[2023-03-19T18:56:12.928Z] Start: Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=/home/ubuntu/frappe_docker --filter label=devcontainer.config_file=/home/ubuntu/frappe_docker/.devcontainer/devcontainer.json
[2023-03-19T18:56:13.053Z] Stop (125 ms): Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=/home/ubuntu/frappe_docker --filter label=devcontainer.config_file=/home/ubuntu/frappe_docker/.devcontainer/devcontainer.json
[2023-03-19T18:56:13.054Z] Start: Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=/home/ubuntu/frappe_docker
[2023-03-19T18:56:13.177Z] Stop (123 ms): Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=/home/ubuntu/frappe_docker
[2023-03-19T18:56:13.178Z] Start: Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=/home/ubuntu/frappe_docker
[2023-03-19T18:56:13.301Z] Stop (123 ms): Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=/home/ubuntu/frappe_docker
[2023-03-19T18:56:13.384Z] Start: Run in Host: /home/ubuntu/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/node /home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-76dfb88e-c5f0-4087-8e81-0b15df74e3e51679252167180 --workspace-folder /home/ubuntu/frappe_docker --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/ubuntu/frappe_docker --id-label devcontainer.config_file=/home/ubuntu/frappe_docker/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/ubuntu/frappe_docker/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-03-19T18:56:13.705Z] (node:19816) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2023-03-19T18:56:13.706Z] (Use `node --trace-deprecation ...` to show where the warning was created)
[2023-03-19T18:56:13.827Z] @devcontainers/cli 0.31.0. Node.js v16.14.2. linux 5.15.0-1031-aws x64.
[2023-03-19T18:56:13.827Z] Start: Run: docker buildx version
[2023-03-19T18:56:13.974Z] Stop (147 ms): Run: docker buildx version
[2023-03-19T18:56:13.975Z] github.com/docker/buildx v0.10.2 00ed17d
[2023-03-19T18:56:13.975Z] 
[2023-03-19T18:56:13.976Z] Start: Resolving Remote
[2023-03-19T18:56:13.983Z] Start: Run: docker-compose version --short
[2023-03-19T18:56:15.314Z] Stop (1331 ms): Run: docker-compose version --short
[2023-03-19T18:56:15.314Z] Docker Compose version: 1.29.2
[2023-03-19T18:56:15.315Z] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=frappe_docker_devcontainer --filter label=com.docker.compose.service=frappe
[2023-03-19T18:56:15.395Z] Stop (80 ms): Run: docker ps -q -a --filter label=com.docker.compose.project=frappe_docker_devcontainer --filter label=com.docker.compose.service=frappe
[2023-03-19T18:56:15.397Z] Start: Run: docker-compose -f /home/ubuntu/frappe_docker/.devcontainer/docker-compose.yml config
[2023-03-19T18:56:16.768Z] Stop (1371 ms): Run: docker-compose -f /home/ubuntu/frappe_docker/.devcontainer/docker-compose.yml config
[2023-03-19T18:56:16.768Z] services:
  frappe:
    command: sleep infinity
    environment:
      SHELL: /bin/bash
    image: frappe/bench:latest
    ports:
    - published: 8000
      target: 8000
    - published: 8001
      target: 8001
    - published: 8002
      target: 8002
    - published: 8003
      target: 8003
    - published: 8004
      target: 8004
    - published: 8005
      target: 8005
    - published: 9000
      target: 9000
    - published: 9001
      target: 9001
    - published: 9002
      target: 9002
    - published: 9003
      target: 9003
    - published: 9004
      target: 9004
    - published: 9005
      target: 9005
    volumes:
    - /home/ubuntu/frappe_docker:/workspace:cached
    working_dir: /workspace/development
  mariadb:
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    - --skip-character-set-client-handshake
    - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: 123
    image: mariadb:10.6
    volumes:
    - mariadb-data:/var/lib/mysql:rw
  redis-cache:
    image: redis:alpine
  redis-queue:
    image: redis:alpine
  redis-socketio:
    image: redis:alpine
version: '3.7'
volumes:
  mariadb-data: {}
  postgresql-data: {}

[2023-03-19T18:56:16.774Z] Start: Run: docker -v
[2023-03-19T18:56:16.861Z] Stop (87 ms): Run: docker -v
[2023-03-19T18:56:16.861Z] Start: Run: docker events --format {{json .}} --filter event=start
[2023-03-19T18:56:16.865Z] PersistedPath=/tmp/devcontainercli-ubuntu, ContainerHasLabels=false
[2023-03-19T18:56:16.866Z] Start: Run: docker-compose -f /home/ubuntu/frappe_docker/.devcontainer/docker-compose.yml config
[2023-03-19T18:56:18.243Z] Stop (1377 ms): Run: docker-compose -f /home/ubuntu/frappe_docker/.devcontainer/docker-compose.yml config
[2023-03-19T18:56:18.244Z] services:
  frappe:
    command: sleep infinity
    environment:
      SHELL: /bin/bash
    image: frappe/bench:latest
    ports:
    - published: 8000
      target: 8000
    - published: 8001
      target: 8001
    - published: 8002
      target: 8002
    - published: 8003
      target: 8003
    - published: 8004
      target: 8004
    - published: 8005
      target: 8005
    - published: 9000
      target: 9000
    - published: 9001
      target: 9001
    - published: 9002
      target: 9002
    - published: 9003
      target: 9003
    - published: 9004
      target: 9004
    - published: 9005
      target: 9005
    volumes:
    - /home/ubuntu/frappe_docker:/workspace:cached
    working_dir: /workspace/development
  mariadb:
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    - --skip-character-set-client-handshake
    - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: 123
    image: mariadb:10.6
    volumes:
    - mariadb-data:/var/lib/mysql:rw
  redis-cache:
    image: redis:alpine
  redis-queue:
    image: redis:alpine
  redis-socketio:
    image: redis:alpine
version: '3.7'
volumes:
  mariadb-data: {}
  postgresql-data: {}

[2023-03-19T18:56:18.246Z] Start: Run: docker inspect --type image frappe/bench:latest
[2023-03-19T18:56:18.339Z] Stop (93 ms): Run: docker inspect --type image frappe/bench:latest
[2023-03-19T18:56:18.341Z] local container features stored at: /home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/node_modules/vscode-dev-containers/container-features
[2023-03-19T18:56:18.343Z] Start: Run: tar --no-same-owner -x -f -
[2023-03-19T18:56:18.377Z] Stop (34 ms): Run: tar --no-same-owner -x -f -
[2023-03-19T18:56:18.378Z] Start: Run: docker-compose --project-name frappe_docker_devcontainer -f /home/ubuntu/frappe_docker/.devcontainer/docker-compose.yml build
[2023-03-19T18:56:19.065Z] /snap/docker/2746/lib/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
  from cryptography.hazmat.backends import default_backend
[2023-03-19T18:56:19.732Z] mariadb uses an image, skipping
[2023-03-19T18:56:19.733Z] redis-cache uses an image, skipping
redis-queue uses an image, skipping
redis-socketio uses an image, skipping
frappe uses an image, skipping
[2023-03-19T18:56:20.010Z] Stop (1632 ms): Run: docker-compose --project-name frappe_docker_devcontainer -f /home/ubuntu/frappe_docker/.devcontainer/docker-compose.yml build
[2023-03-19T18:56:20.012Z] Start: Run: docker inspect --type image frappe/bench:latest
[2023-03-19T18:56:20.103Z] Stop (91 ms): Run: docker inspect --type image frappe/bench:latest
[2023-03-19T18:56:20.106Z] Start: Run: docker build -f /tmp/devcontainercli-ubuntu/updateUID.Dockerfile-0.31.0 -t vsc-frappe_docker-f86ce87335b36930737c7e067e3bc03d-uid --build-arg BASE_IMAGE=frappe/bench:latest --build-arg REMOTE_USER=frappe --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=frappe /tmp/devcontainercli-ubuntu/empty-folder
[2023-03-19T18:56:20.430Z] [+] Building 0.0s (0/0)                                                         
[2023-03-19T18:56:20.517Z] [+] Building 0.1s (6/6) FINISHED                                                
[2023-03-19T18:56:20.518Z] 
 => [internal] load build definition from updateUID.Dockerfile-0.31.0      0.0s
 => => transferring dockerfile: 1.33kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/frappe/bench:latest             0.0s
 => [1/2] FROM docker.io/frappe/bench:latest                               0.0s
 => CACHED [2/2] RUN eval $(sed -n "s/frappe:[^:]*:\([^:]*\):\([^:]*\):[^  0.0s
 => exporting to image                                                     0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:ffc29f2ca03270f6a4b215acc79c7bbe9348d7ad8fdf1  0.0s
 => => naming to docker.io/library/vsc-frappe_docker-f86ce87335b36930737c  0.0s
[2023-03-19T18:56:20.722Z] Stop (616 ms): Run: docker build -f /tmp/devcontainercli-ubuntu/updateUID.Dockerfile-0.31.0 -t vsc-frappe_docker-f86ce87335b36930737c7e067e3bc03d-uid --build-arg BASE_IMAGE=frappe/bench:latest --build-arg REMOTE_USER=frappe --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=frappe /tmp/devcontainercli-ubuntu/empty-folder
[2023-03-19T18:56:20.724Z] Docker Compose override file for creating container:
version: "3.7"

services:
  'frappe':
    image: vsc-frappe_docker-f86ce87335b36930737c7e067e3bc03d-uid
    entrypoint: ["/bin/sh", "-c", "echo Container started\n
trap \"exit 0\" 15\n
\n
exec \"$$@\"\n
while sleep 1 & wait $$!; do :; done", "-"]
    labels:
      - 'devcontainer.local_folder=/home/ubuntu/frappe_docker'
      - 'devcontainer.config_file=/home/ubuntu/frappe_docker/.devcontainer/devcontainer.json'
      - 'devcontainer.metadata=[{"customizations":{"vscode":{"extensions":["ms-python.python","ms-vscode.live-server","grapecity.gc-excelviewer","mtxr.sqltools","visualstudioexptteam.vscodeintellicode"],"settings":{"terminal.integrated.profiles.linux":{"frappe bash":{"path":"/bin/bash"}},"terminal.integrated.defaultProfile.linux":"frappe bash","debug.node.autoAttach":"disabled"}}},"remoteUser":"frappe","forwardPorts":[8000,9000,6787],"shutdownAction":"stopCompose"}]'
    volumes:
      - vscode:/vscode
volumes:
  vscode:
    external: true
[2023-03-19T18:56:20.724Z] Writing docker-compose.devcontainer.containerFeatures-1679252180724.yml to /tmp/devcontainercli-ubuntu/docker-compose
[2023-03-19T18:56:20.724Z] Start: Run: docker-compose --project-name frappe_docker_devcontainer -f /home/ubuntu/frappe_docker/.devcontainer/docker-compose.yml -f /tmp/devcontainercli-ubuntu/docker-compose/docker-compose.devcontainer.containerFeatures-1679252180724.yml up -d
[2023-03-19T18:56:21.374Z] /snap/docker/2746/lib/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
  from cryptography.hazmat.backends import default_backend
[2023-03-19T18:56:22.006Z] ERROR: .FileNotFoundError: [Errno 2] No such file or directory: '/tmp/devcontainercli-ubuntu/docker-compose/docker-compose.devcontainer.containerFeatures-1679252180724.yml'
[2023-03-19T18:56:22.273Z] Stop (1549 ms): Run: docker-compose --project-name frappe_docker_devcontainer -f /home/ubuntu/frappe_docker/.devcontainer/docker-compose.yml -f /tmp/devcontainercli-ubuntu/docker-compose/docker-compose.devcontainer.containerFeatures-1679252180724.yml up -d
[2023-03-19T18:56:22.153Z] Error: Command failed: docker-compose --project-name frappe_docker_devcontainer -f /home/ubuntu/frappe_docker/.devcontainer/docker-compose.yml -f /tmp/devcontainercli-ubuntu/docker-compose/docker-compose.devcontainer.containerFeatures-1679252180724.yml up -d
[2023-03-19T18:56:22.153Z]     at sie (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:1896:3061)
[2023-03-19T18:56:22.153Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-03-19T18:56:22.154Z]     at async iie (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:1878:2396)
[2023-03-19T18:56:22.154Z]     at async xie (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:1945:2798)
[2023-03-19T18:56:22.154Z]     at async Wf (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:1945:3750)
[2023-03-19T18:56:22.155Z]     at async noe (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:2069:17325)
[2023-03-19T18:56:22.155Z]     at async roe (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:2069:17066)
[2023-03-19T18:56:22.169Z] Stop (8785 ms): Run in Host: /home/ubuntu/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/node /home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-76dfb88e-c5f0-4087-8e81-0b15df74e3e51679252167180 --workspace-folder /home/ubuntu/frappe_docker --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/ubuntu/frappe_docker --id-label devcontainer.config_file=/home/ubuntu/frappe_docker/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/ubuntu/frappe_docker/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-03-19T18:56:22.169Z] Exit code 1
[2023-03-19T18:56:22.176Z] Command failed: /home/ubuntu/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/node /home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-76dfb88e-c5f0-4087-8e81-0b15df74e3e51679252167180 --workspace-folder /home/ubuntu/frappe_docker --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/ubuntu/frappe_docker --id-label devcontainer.config_file=/home/ubuntu/frappe_docker/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/ubuntu/frappe_docker/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-03-19T18:56:22.176Z] Exit code 1
```

It says there's no file in `/tmp/ubuntu`  but when I manually lookup the file, it is present and it has appropriate user permissions too.
Please help.

**Comment by shikharx06** [comment]
FIXED IT:

**Comment by mullerch** [comment]
I had a similar issue. I had to update docker to the latest version.
