### ISSUE TITLE
wkhtmltopdf TimeoutError - Server Error

### ISSUE THREAD

**Issue by intellimomentum** [frappe/frappe_docker#1113]
Hello, since some days I get following error. Even after an update of my erpnext containers from v14.12.1 to v14.19.0 it is still alive.

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/print_format.py", line 129, in download_pdf
    pdf_file = frappe.get_print(
  File "apps/frappe/frappe/__init__.py", line 2040, in get_print
    return get_pdf(html, options=pdf_options, output=output)
  File "apps/frappe/frappe/utils/pdf.py", line 38, in get_pdf
    filedata = pdfkit.from_string(html, options=options or {}, verbose=True)
  File "env/lib/python3.10/site-packages/pdfkit/api.py", line 75, in from_string
    return r.to_pdf(output_path)
  File "env/lib/python3.10/site-packages/pdfkit/pdfkit.py", line 201, in to_pdf
    self.handle_error(exit_code, stderr)
  File "env/lib/python3.10/site-packages/pdfkit/pdfkit.py", line 155, in handle_error
    raise IOError('wkhtmltopdf reported an error:\n' + stderr)
OSError: wkhtmltopdf reported an error:
Exit with code 1 due to network error: TimeoutError

**Comment by revant** [comment]
check if this helps https://discuss.frappe.io/t/frappe-docker-2023-production-setup-password-reset-email-link-added-with-port-8000/101844/8

**Comment by intellimomentum** [comment]
still does not work.

common_**site_config.json** looks like this:
`{}`

the `site_config.json` looks like this:
```
{
 "db_name": "_...",
 "db_password": "mysecretpwd",
 "db_type": "mariadb",
 "encryption_key": "***************",
 "user_type_doctype_limit": {
  "employee_self_service": 20
 },
 "restart_supervisor_on_update": true,
 "restart_systemd_on_update": true
}
```

**restart_supervisor_on_update** and **restart_systemd_on_update** have no effect.

**Comment by revant** [comment]
> common_**site_config.json** looks like this:
> `{}`

empty common_site_config.json will not work.

**Comment by dawoodjee** [comment]
Related #1049
