### ISSUE TITLE
Cannot build images for production

### ISSUE THREAD

**Issue by lekhnath** [frappe/frappe_docker#1192]
## Description of the issue
Error building docker images

## Context information (for bug reports)
Erpnext Version : v13.28
frappe_docker version: compat 

### Observed result
**Authentication failed. Please check the API token on https://snyk.io**

### Expected result
**Build/bake docker images**

### Stacktrace / full error message if available
```
#23 0.662 WARN: bench is installed in editable mode!
#23 0.662 
#23 0.662 This is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`
#23 0.662 
#23 1.154 $ /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade pip
#23 5.967 Installing 4 applications...
#23 5.967 Installing frappe
#23 5.968 $ /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/frappe/frappe-bench/apps/frappe 
#23 13.22 DEPRECATION: dropbox 11.7.0 has a non-standard dependency specifier stone>=2.*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of dropbox or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
#23 13.55 $ yarn install
#23 13.71 yarn install v1.22.19
#23 13.81 [1/4] Resolving packages...
#23 14.18 success Already up-to-date.
#23 14.19 $ yarn run snyk-protect
#23 14.33 yarn run v1.22.19
#23 14.37 $ snyk protect
#23 18.47 Authentication failed. Please check the API token on https://snyk.io
#23 18.51 
#23 19.40 error Command failed with exit code 2.
#23 19.40 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#23 19.43 error Command failed with exit code 2.
#23 19.43 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#23 19.45 ERROR: 
#23 19.45 Traceback (most recent call last):
#23 19.45   File "/home/frappe/.local/bin/bench", line 33, in <module>
#23 19.46     sys.exit(load_entry_point('frappe-bench', 'console_scripts', 'bench')())
#23 19.46   File "/home/frappe/.bench/bench/cli.py", line 121, in cli
#23 19.46     raise e
#23 19.46   File "/home/frappe/.bench/bench/cli.py", line 111, in cli
#23 19.46     bench_command()
#23 19.46   File "/home/frappe/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
#23 19.46     return self.main(*args, **kwargs)
#23 19.46   File "/home/frappe/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
#23 19.46     rv = self.invoke(ctx)
#23 19.46   File "/home/frappe/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
#23 19.46     return _process_result(sub_ctx.command.invoke(sub_ctx))
#23 19.46   File "/home/frappe/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
#23 19.46     return _process_result(sub_ctx.command.invoke(sub_ctx))
#23 19.46   File "/home/frappe/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
#23 19.46     return ctx.invoke(self.callback, **ctx.params)
#23 19.46   File "/home/frappe/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
#23 19.46     return __callback(*args, **kwargs)
#23 19.46   File "/home/frappe/.bench/bench/commands/setup.py", line 155, in setup_requirements
#23 19.46     bench.setup.requirements(apps=apps)
#23 19.46   File "/home/frappe/.bench/bench/utils/render.py", line 95, in wrapper_fn
#23 19.46     return fn(*args, **kwargs)
#23 19.46   File "/home/frappe/.bench/bench/bench.py", line 443, in requirements
#23 19.46     app = App(path_to_app, bench=self.bench, to_clone=False).install(
#23 19.47   File "/home/frappe/.bench/bench/utils/render.py", line 110, in wrapper_fn
#23 19.47     return fn(*args, **kwargs)
#23 19.47   File "/home/frappe/.bench/bench/app.py", line 232, in install
#23 19.47     install_app(
#23 19.47   File "/home/frappe/.bench/bench/app.py", line 559, in install_app
#23 19.48     bench.run("yarn install", cwd=app_path)
#23 19.48   File "/home/frappe/.bench/bench/bench.py", line 47, in run
#23 19.48     return exec_cmd(cmd, cwd=cwd or self.cwd)
#23 19.48   File "/home/frappe/.bench/bench/utils/__init__.py", line 153, in exec_cmd
#23 19.48     raise CommandFailedError
#23 19.48 bench.exceptions.CommandFailedError
------
error: failed to solve: executor failed running [/bin/sh -c bench setup requirements]: exit code: 1
make: *** [Makefile:32: bake] Error 1
```

**Comment by revant** [comment]
You can fix compat branch and send a PR or this issue will close after 2 months of inactivity.

**Comment by lekhnath** [comment]
Not interested

**Comment by revant** [comment]
```shell
export APPS_JSON='[                                                   
  {
    "url": "https://github.com/frappe/erpnext",
    "branch": "version-13"
  }
]'

export APPS_JSON_BASE64=$(echo ${APPS_JSON} | base64 -w 0)

docker build \                                                        
  --build-arg=FRAPPE_PATH=https://github.com/frappe/frappe \
  --build-arg=FRAPPE_BRANCH=version-13 \       
  --build-arg=PYTHON_VERSION=3.9.17 \
  --build-arg=NODE_VERSION=14.21.3 \
  --build-arg=APPS_JSON_BASE64=$APPS_JSON_BASE64 \
  --tag=delete-me:latest \                                
  --file=images/custom/Containerfile .
```

This will build single image with ERPNext v13.

**Comment by lekhnath** [comment]
Thanks a lot @revant. Appreciated.
