### ISSUE TITLE
bench init frappe-bench broken using docker dependencies versions ? 

### ISSUE THREAD

**Issue by Grolaf** [frappe/frappe_docker#1195]
## Description of the issue

Dear frappe developers and community. I had an issue for my lastest installation.

Using lastest docker images, the command `bench init --skip-redis-config-generation frappe-bench` fails inside the `frappe` container.

## Context information (for bug reports)

Basic installation

## Steps to reproduce the issue

(Simply follow the tutorial) : 

```bash
# Clone repository
git clone https://github.com/frappe/frappe_docker.git
cd frappe_docker
# Prepare .yml file
cp -R devcontainer-example .devcontainer
# Start containers
docker-compose -f .devcontainer/docker-compose.yml up -d
# Enter the container (not necessary but convenient to perform operations)
docker exec -e "TERM=xterm-256color" -w /workspace/development -it devcontainer-frappe-1 bash
# Init frappe-bench (This command fails)
bench init --skip-redis-config-generation frappe-bench
```

### Observed result

The command fails because of dependancies issues : 

```bash
error frappe-framework@: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.1"
error Found incompatible module.
```

### Expected result

`frappe-bench` init normally (the repository is cretaed and `frappe` is installed

### Stacktrace / full error message if available

```bash
$ bench init --skip-redis-config-generation frappe-bench

Setting Up Environment
$ python3 -m venv env
$ /workspace/development/frappe-bench/frappe-bench/env/bin/python -m pip install --quiet --upgrade pip
$ /workspace/development/frappe-bench/frappe-bench/env/bin/python -m pip install --quiet wheel
Getting frappe
$ git clone https://github.com/frappe/frappe.git  --depth 1 --origin upstream
Cloning into 'frappe'...
remote: Enumerating objects: 3219, done.
remote: Counting objects: 100% (3219/3219), done.
remote: Compressing objects: 100% (2835/2835), done.
remote: Total 3219 (delta 420), reused 1755 (delta 283), pack-reused 0
Receiving objects: 100% (3219/3219), 17.19 MiB | 10.95 MiB/s, done.
Resolving deltas: 100% (420/420), done.
Installing frappe
$ /workspace/development/frappe-bench/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /workspace/development/frappe-bench/frappe-bench/apps/frappe 
$ yarn install
yarn install v1.22.19
[1/5] Validating package.json...
error frappe-framework@: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
subprocess.CalledProcessError: Command 'yarn install' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/frappe/.bench/bench/commands/make.py", line 68, in init
    init(
  File "/home/frappe/.bench/bench/utils/render.py", line 105, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.bench/bench/utils/system.py", line 79, in init
    get_app(
  File "/home/frappe/.bench/bench/app.py", line 444, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/home/frappe/.bench/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.bench/bench/app.py", line 242, in install
    install_app(
  File "/home/frappe/.bench/bench/app.py", line 581, in install_app
    bench.run("yarn install", cwd=app_path)
  File "/home/frappe/.bench/bench/bench.py", line 48, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
  File "/home/frappe/.bench/bench/utils/__init__.py", line 158, in exec_cmd
    raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError: yarn install

ERROR: There was a problem while creating frappe-bench
```

Thank you very much in advance ! 
Grolaf.

**Comment by revant** [comment]
If you wish to use develop branch of frappe framework then it'll use v18

version-14 which is stable for normal developers works on v16

`nvm use v18` before you `bench init`

You can just use `installer.py` to create bench, choose versions, etc. For help, `python installer.py --help`

**Comment by Grolaf** [comment]
Hello revant and thank you for your very quick answer ! 

Yes you are right for this :) but actually the tutorial is not up to date then ! 

I'll try to fix this in the docker file directly !

**Comment by revant** [comment]
Mentioned here for version 13 and 14 https://github.com/frappe/frappe_docker/blob/main/docs/development.md#setup-first-bench

Python versions need update
