### ISSUE TITLE
Unable to login into app

### ISSUE THREAD

**Issue by rameshandroid** [frappe/frappe_docker#1200]
## Description of the issue
when i am trying to install erpnext using docker i am unable to login into the web application.

## Steps to reproduce the issue
i am following the below documentation
https://github.com/frappe/frappe_docker/blob/main/docs/setup_for_linux_mac.md
I ran the below commands 
cd frappe_docker
docker-compose -f ./pwd.yml up
### Observed result
Login is not proceeding further after entering the username and password(http://localhost:8080/#login) 

### Expected result
Login should proceed further

### Stacktrace / full error message if available
website.js:177 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 83, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 171, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 34, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 70, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 115, in __init__
    self.run_trigger("on_session_creation")
  File "apps/frappe/frappe/auth.py", line 298, in run_trigger
    frappe.call(frappe.get_attr(method), login_manager=self)
  File "apps/frappe/frappe/__init__.py", line 1619, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/core/doctype/activity_log/feed.py", line 55, in login_feed
    add_authentication_log(subject, login_manager.user)
  File "apps/frappe/frappe/core/doctype/activity_log/activity_log.py", line 43, in add_authentication_log
    frappe.get_doc(
  File "apps/frappe/frappe/model/document.py", line 285, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1082, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1267, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1251, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/frappe/frappe/automation/doctype/assignment_rule/assignment_rule.py", line 328, in update_due_date
    rule_doc = frappe.get_cached_doc("Assignment Rule", rule.get("name"))
AttributeError: 'str' object has no attribute 'get'

process_response @ website.js:177
(anonymous) @ website.js:111
te @ jquery.js:3500
fireWith @ jquery.js:3630
di @ jquery.js:9798
(anonymous) @ jquery.js:10057
load (async)
send @ jquery.js:10076
ajax @ jquery.js:9690
call @ website.js:77
login.call @ (index):1475
(anonymous) @ (index):1342
dispatch @ jquery.js:5430
Mt.handle @ jquery.js:5234
```
![erpnext](https://github.com/frappe/frappe_docker/assets/4383787/7b0f4064-eda6-4684-ac33-41b09a256acb)

**Comment by revant** [comment]
Works for me, tests work, here's a video:


https://github.com/frappe/frappe_docker/assets/1040161/40f8b4a3-cb09-4750-916c-b04ef06ae15b
