### ISSUE TITLE
node version requirment issue inside the dev docker image / container

### ISSUE THREAD

**Issue by aghanem** [frappe/frappe_docker#1211]
## Description of the issue

Trying the latest dev container mechanism and got error on node version not met inside the docker container. Not sure where to fix it.

## Steps to reproduce the issue

1. Clone dev container repo
2. follow instructions from https://github.com/frappe/frappe_docker/blob/main/docs/development.md
3. when approached "bench init" , got the error above

### Observed result
node version inside docker container is 16
![image](https://github.com/frappe/frappe_docker/assets/2403613/7d395c99-ed6b-42b2-8a8e-97a5239b1ca7)

### Expected result
node version should be >=18 as required by frappe bench app 
### Stacktrace / full error message if available

```
frappe@9e7033c4f3ff:/workspace/development$ bench init --skip-redis-config-generation frappe-bench
cd frappe-bench
Setting Up Environment
$ python3 -m venv env
$ /workspace/development/frappe-bench/env/bin/python -m pip install --quiet --upgrade pip
$ /workspace/development/frappe-bench/env/bin/python -m pip install --quiet wheel
Getting frappe
$ git clone https://github.com/frappe/frappe.git  --depth 1 --origin upstream
Cloning into 'frappe'...
remote: Enumerating objects: 3235, done.
remote: Counting objects: 100% (3235/3235), done.
remote: Compressing objects: 100% (2851/2851), done.
remote: Total 3235 (delta 424), reused 1758 (delta 273), pack-reused 0
Receiving objects: 100% (3235/3235), 17.21 MiB | 1.92 MiB/s, done.
Resolving deltas: 100% (424/424), done.
Updating files: 100% (3070/3070), done.
Installing frappe
$ /workspace/development/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /workspace/development/frappe-bench/apps/frappe 

$ yarn install
yarn install v1.22.19
[1/5] Validating package.json...
error frappe-framework@: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
subprocess.CalledProcessError: Command 'yarn install' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/frappe/.bench/bench/commands/make.py", line 68, in init
    init(
  File "/home/frappe/.bench/bench/utils/render.py", line 105, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.bench/bench/utils/system.py", line 79, in init
    get_app(
  File "/home/frappe/.bench/bench/app.py", line 444, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/home/frappe/.bench/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.bench/bench/app.py", line 242, in install
    install_app(
  File "/home/frappe/.bench/bench/app.py", line 581, in install_app
    bench.run("yarn install", cwd=app_path)
  File "/home/frappe/.bench/bench/bench.py", line 48, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
  File "/home/frappe/.bench/bench/utils/__init__.py", line 158, in exec_cmd
    raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError: yarn install

ERROR: There was a problem while creating frappe-bench
Do you want to rollback these changes? [y/N]: Aborted!
frappe@9e7033c4f3ff:/workspace/development/frappe-bench$ $ git clone https://github.com/frappe/frappe.git  --depth 1 --origin upstream
Cloning into 'frappe'...
remote: Enumerating objects: 3235, done.
remote: Counting objects: 100% (3235/3235), done.
remote: Compressing objects: 100% (2851/2851), done.
remote: Total 3235 (delta 424), reused 1758 (delta 273), pack-reused 0
Receiving objects: 100% (3235/3235), 17.21 MiB | 1.92 MiB/s, done.
Resolving deltas: 100% (424/424), done.
Updating files: 100% (3070/3070), done.
Installing frappe
$ /workspace/development/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /workspace/development/frappe-bench/apps/frappe 

$ yarn install
yarn install v1.22.19
[1/5] Validating package.json...
error frappe-framework@: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
subprocess.CalledProcessError: Command 'yarn install' returned non-zero exit status 1.

frappe@9e7033c4f3ff:/workspace/development/frappe-bench$ node --version
v16.20.1
```

**Comment by aghanem** [comment]
I'm trying now 
nvm use v18 , but seems that you need to fix the docs/guide.

**Comment by revant** [comment]
The defaults are set to use version-14. Which is stable version for production.

The one you are installing is from develop branch which requires nodejs 18. Execute `nvm use 18` before `bench init` command and it'll use nodejs v18.

**Comment by aghanem** [comment]
may I suggest if you can update the docs  https://github.com/frappe/frappe_docker/blob/main/docs/development.md

or automatically run the mentioned nvm command in container startup ?

**Comment by revant** [comment]
Following sections are part of existing documentation. Add anything to it and send PR.

To setup frappe framework version 14 bench set `PYENV_VERSION` environment variable to `3.10.5` (default)  use NodeJS version 16 (default),

```shell
# Use default environments
bench init --skip-redis-config-generation --frappe-branch version-14 frappe-bench
# Or set environment versions explicitly
nvm use v16
PYENV_VERSION=3.10.12 bench init --skip-redis-config-generation --frappe-branch version-14 frappe-bench
# Switch directory
cd frappe-bench
```

To setup frappe framework version 13 bench set `PYENV_VERSION` environment variable to `3.9.9` and use NodeJS version 14,

```shell
nvm use v14
PYENV_VERSION=3.9.9 bench init --skip-redis-config-generation --frappe-branch version-13 frappe-bench
cd frappe-bench
```
