### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:12311 in websocket container

### ISSUE THREAD

**Issue by tamhv** [frappe/frappe_docker#1217]
## Description of the issue
I just tried to set up frappe on Play with docker. Everything looks good, i can see frappe login page and login as Administrator. But when i'm checking container logs, i saw a lot of error log from websocket container, I'm not sure it's a bug or not. I haven't touched anything yet.

## Steps to reproduce the issue

1. Go to https://labs.play-with-docker.com/?stack=https://raw.githubusercontent.com/frappe/frappe_docker/main/pwd.yml && login
2. wget https://raw.githubusercontent.com/frappe/frappe_docker/main/pwd.yml 
3. docker-compose -f pwd.yml up -d
4. docker-compose -f pwd.yml logs websocket

### Observed result
```
frappe_docker-websocket-1  | node:events:491
frappe_docker-websocket-1  |       throw er; // Unhandled 'error' event
frappe_docker-websocket-1  |       ^
frappe_docker-websocket-1  | 
frappe_docker-websocket-1  | Error: connect ECONNREFUSED 127.0.0.1:12311
frappe_docker-websocket-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
frappe_docker-websocket-1  | Emitted 'error' event on RedisClient instance at:
frappe_docker-websocket-1  |     at RedisClient.on_error (/home/frappe/frappe-bench/apps/frappe/node_modules/redis/index.js:342:14)
frappe_docker-websocket-1  |     at Socket.<anonymous> (/home/frappe/frappe-bench/apps/frappe/node_modules/redis/index.js:223:14)
frappe_docker-websocket-1  |     at Socket.emit (node:events:513:28)
frappe_docker-websocket-1  |     at emitErrorNT (node:internal/streams/destroy:157:8)
frappe_docker-websocket-1  |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
frappe_docker-websocket-1  |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
frappe_docker-websocket-1  |   errno: -111,
frappe_docker-websocket-1  |   code: 'ECONNREFUSED',
frappe_docker-websocket-1  |   syscall: 'connect',
frappe_docker-websocket-1  |   address: '127.0.0.1',
frappe_docker-websocket-1  |   port: 12311
frappe_docker-websocket-1  | }
```
### Stacktrace / full error message if available

```
(paste here)
```

**Comment by revant** [comment]
That log is before `configuration` container changed the common_site_config.json.
