### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by arvindkumar134** [frappe/frappe_docker#1276]
Hi, I am facing an issue with the salary register. below is error

### App Versions

```
{
    "erpnext": "14.33.0",
    "frappe": "14.45.0",
    "hrmanagement": "0.0.1",
    "hrms": "14.16.1",
    "payments": "0.0.1"
}
```

### Traceback

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
               ^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1620, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 802, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 232, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 802, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/core/doctype/report/report.py", line 131, in execute_script_report
    res = self.execute_module(filters)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/hrms/hrms/payroll/report/salary_register/salary_register.py", line 29, in execute
    earning_types, ded_types = get_earning_and_deduction_types(salary_slips)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/hrms/hrms/payroll/report/salary_register/salary_register.py", line 88, in get_earning_and_deduction_types
    salary_component_and_type[_(component_type)].append(salary_compoent)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: None

```

### Request Data

```
{
    "type": "GET",
    "args": {
        "report_name": "Salary Register",
        "filters": "{\"from_date\":\"2023-06-08\",\"to_date\":\"2023-11-23\",\"currency\":\"INR\",\"company\":\"SP Facilities\",\"docstatus\":\"Submitted\"}",
        "are_default_filters": false
    },
    "headers": {},
    "error_handlers": {},
    "url": "/api/method/frappe.desk.query_report.run"
}
```

### Response Data

```
{
    "exception": "KeyError: None"
}
```

**Comment by revant** [comment]
I haven't faced this issue. Hope someone who uses same apps helps you.

**Comment by revant** [comment]
You can also report the issue in the app repo of salary register

**Comment by ankush** [comment]
Nothing to do with docker.
