### ISSUE TITLE
Cannot build image for Erpnext version v13.28.0

### ISSUE THREAD

**Issue by lekhnath** [frappe/frappe_docker#1282]
@revant I am building custom image from Containerfile using following build command but could not complete the build. Any suggestions?

Thank you.

**Build command**

```bash
export APPS_JSON_BASE64=`base64 -w 0 $PWD/data/apps.json` \
    && \
    docker build --no-cache \
    --build-arg=DEBIAN_BASE=bullseye \
    --build-arg=WKHTMLTOPDF_DISTRO=buster \
    --build-arg=WKHTMLTOPDF_VERSION=0.12.6-1 \
		--build-arg=FRAPPE_BRANCH=v13.28.0 \
		--build-arg=PYTHON_VERSION=3.9.9 \
		--build-arg=NODE_VERSION=14.18.1 \
		--build-arg=APPS_JSON_BASE64=$APPS_JSON_BASE64 \
		--tag=erpnext-nepal:13.1.0 \
		--file=images/custom/Containerfile .
```

**Build Error**

```bash
65.04 INFO: pip is looking at multiple versions of frappe to determine which version is compatible with other requirements. This could take a while.
65.04 ERROR: Ignored the following yanked versions: 1.0.0, 1.1.0, 1.2.0, 2.0.0, 2.1.0, 2.2.1, 2.3.0, 2.4.0, 2.4.1, 2.5.0, 2.6.0, 2.6.1, 2.7.0, 2.8.0, 2.9.0, 2.9.1, 2.10.0, 2.10.1, 2.11.0, 2.12.0, 2.12.1, 2.12.2, 2.12.3, 2.13.0, 2.14.0, 2.14.1, 2.14.2, 2.15.0, 2.16.0, 2.17.0, 2.18.0, 2.19.0, 2.20.0, 2.21.0, 2.22.0, 2.23.0, 2.23.1, 2.24.0, 2.24.1, 2.25.0, 2.25.1, 2.26.0, 2.27.0, 2.28.0, 2.29.0, 2.29.1, 3.0.0, 3.1.0, 3.1.1, 3.2.0, 3.3.0, 3.4.0, 3.4.1, 3.5.0, 3.6.0, 3.7.0, 3.8.0, 3.9.0, 3.10.0, 3.11.0, 3.11.1, 3.12.0, 3.13.0, 3.14.0, 3.15.0, 3.16.0, 3.17.0, 3.18.0, 3.19.0, 3.20.0, 3.21.0, 3.22.0, 3.23.0, 3.24.0, 3.25.0, 3.26.1, 3.27.0, 3.28.0, 3.29.0, 3.29.1, 3.29.2, 3.30.0, 3.31.0, 3.32.0, 3.33.0, 3.34.0, 3.35.0, 3.37.0, 3.37.1, 3.37.2, 3.38.0, 3.39.0, 3.39.1, 3.40.0, 3.41.0, 3.42.0, 3.43.0, 3.44.0, 3.45.0, 3.46.0, 3.47.0, 3.48.0, 3.49.0, 3.50.0, 3.51.0, 3.52.0, 3.53.0, 3.54.0, 3.55.0, 3.56.0, 3.57.1, 3.58.0, 3.59.0, 4.0.0, 4.1.0, 4.2.0, 4.3.0, 4.4.0, 4.5.0, 4.6.0, 4.7.0, 4.8.0, 4.9.0, 4.10.0, 4.11.0, 4.12.0, 4.13.0, 4.13.1, 4.14.0, 4.15.2, 4.16.0, 4.17.0
65.04 ERROR: Could not find a version that satisfies the requirement braintree~=4.8.0 (from frappe) (from versions: 3.59.1, 4.17.1, 4.18.0, 4.18.1, 4.19.0, 4.20.0, 4.21.0, 4.22.0, 4.23.0, 4.24.0)
65.04 ERROR: No matching distribution found for braintree~=4.8.0
66.11 subprocess.CalledProcessError: Command '/home/frappe/frappe-bench/env/bin/python -m pip install  --upgrade -e /home/frappe/frappe-bench/apps/frappe ' returned non-zero exit status 1.
66.11 
66.11 The above exception was the direct cause of the following exception:
66.11 
66.11 Traceback (most recent call last):
66.11   File "/usr/local/lib/python3.9/site-packages/bench/commands/make.py", line 75, in init
66.11     init(
66.11   File "/usr/local/lib/python3.9/site-packages/bench/utils/render.py", line 105, in wrapper_fn
66.11     return fn(*args, **kwargs)
66.11   File "/usr/local/lib/python3.9/site-packages/bench/utils/system.py", line 87, in init
66.11     get_app(
66.11   File "/usr/local/lib/python3.9/site-packages/bench/app.py", line 444, in get_app
66.11     app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
66.11   File "/usr/local/lib/python3.9/site-packages/bench/utils/render.py", line 126, in wrapper_fn
66.11     return fn(*args, **kwargs)
66.11   File "/usr/local/lib/python3.9/site-packages/bench/app.py", line 242, in install
66.11     install_app(
66.11   File "/usr/local/lib/python3.9/site-packages/bench/app.py", line 573, in install_app
66.11     bench.run(
66.11   File "/usr/local/lib/python3.9/site-packages/bench/bench.py", line 48, in run
66.11     return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
66.11   File "/usr/local/lib/python3.9/site-packages/bench/utils/__init__.py", line 158, in exec_cmd
66.11     raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
66.11 bench.exceptions.CommandFailedError: /home/frappe/frappe-bench/env/bin/python -m pip install  --upgrade -e /home/frappe/frappe-bench/apps/frappe 
66.11 
66.11 ERROR: There was a problem while creating /home/frappe/frappe-bench
66.11 Do you want to rollback these changes? [y/N]: Aborted!
------
Containerfile:108
--------------------
 107 |     ARG FRAPPE_PATH=https://github.com/frappe/frappe
 108 | >>> RUN export APP_INSTALL_ARGS="" && \
 109 | >>>   if [ -n "${APPS_JSON_BASE64}" ]; then \
 110 | >>>     export APP_INSTALL_ARGS="--apps_path=/opt/frappe/apps.json"; \
 111 | >>>   fi && \
 112 | >>>   bench init ${APP_INSTALL_ARGS}\
 113 | >>>     --frappe-branch=${FRAPPE_BRANCH} \
 114 | >>>     --frappe-path=${FRAPPE_PATH} \
 115 | >>>     --no-procfile \
 116 | >>>     --no-backups \
 117 | >>>     --skip-redis-config-generation \
 118 | >>>     --verbose \
 119 | >>>     /home/frappe/frappe-bench && \
 120 | >>>   cd /home/frappe/frappe-bench && \
 121 | >>>   echo "{}" > sites/common_site_config.json && \
 122 | >>>   find apps -mindepth 1 -path "*/.git" | xargs rm -fr
 123 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c export APP_INSTALL_ARGS=\"\" &&   if [ -n \"${APPS_JSON_BASE64}\" ]; then     export APP_INSTALL_ARGS=\"--apps_path=/opt/frappe/apps.json\";   fi &&   bench init ${APP_INSTALL_ARGS}    --frappe-branch=${FRAPPE_BRANCH}     --frappe-path=${FRAPPE_PATH}     --no-procfile     --no-backups     --skip-redis-config-generation     --verbose     /home/frappe/frappe-bench &&   cd /home/frappe/frappe-bench &&   echo \"{}\" > sites/common_site_config.json &&   find apps -mindepth 1 -path \"*/.git\" | xargs rm -fr" did not complete successfully: exit code: 1
make: *** [Makefile:4: build] Error 1

```

**Comment by revant** [comment]
> braintree~=4.8.0

Use available version of the package

https://pypi.org/project/braintree/4.8.0/
