### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by auliabismar** [frappe/frappe_docker#1310]
Using the latest yml, the server is up but when I tried to connect to localhost:8080 it will says internal server error
when I checked the db-1 log it showed:
```2024-01-11 15:36:18 2024-01-11  8:36:18 24 [Warning] Access denied for user '_5e5899d8398b5f7b'@'172.19.0.9' (using password: YES)
2024-01-11 15:36:18 2024-01-11  8:36:18 25 [Warning] Access denied for user '_5e5899d8398b5f7b'@'172.19.0.9' (using password: YES)
2024-01-11 15:36:18 2024-01-11  8:36:18 26 [Warning] Access denied for user '_5e5899d8398b5f7b'@'172.19.0.9' (using password: YES)
2024-01-11 15:36:42 2024-01-11  8:36:42 42 [Warning] Access denied for user '_5e5899d8398b5f7b'@'172.19.0.7' (using password: YES)
2024-01-11 15:37:42 2024-01-11  8:37:42 77 [Warning] Access denied for user '_5e5899d8398b5f7b'@'172.19.0.7' (using password: YES)```

when I checked the backend-1 log it showed:
```2024-01-11 15:36:18 [2024-01-11 08:36:18 +0000] [8] [ERROR] Error handling request /
2024-01-11 15:36:18 Traceback (most recent call last):
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 95, in application
2024-01-11 15:36:18     init_request(request)
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 191, in init_request
2024-01-11 15:36:18     frappe.local.http_request = HTTPRequest()
2024-01-11 15:36:18                                 ^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 40, in __init__
2024-01-11 15:36:18     self.set_session()
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 76, in set_session
2024-01-11 15:36:18     frappe.local.login_manager = LoginManager()
2024-01-11 15:36:18                                  ^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 121, in __init__
2024-01-11 15:36:18     self.make_session(resume=True)
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 209, in make_session
2024-01-11 15:36:18     frappe.local.session_obj = Session(
2024-01-11 15:36:18                                ^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 214, in __init__
2024-01-11 15:36:18     self.resume()
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 285, in resume
2024-01-11 15:36:18     validate_ip_address(self.user)
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 420, in validate_ip_address
2024-01-11 15:36:18     frappe.get_cached_value("User", user, user_fields, as_dict=True)
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1196, in get_cached_value
2024-01-11 15:36:18     doc = get_cached_doc(doctype, name)
2024-01-11 15:36:18           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1137, in get_cached_doc
2024-01-11 15:36:18     doc = get_doc(*args, **kwargs)
2024-01-11 15:36:18           ^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1265, in get_doc
2024-01-11 15:36:18     doc = frappe.model.document.get_doc(*args, **kwargs)
2024-01-11 15:36:18           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
2024-01-11 15:36:18     controller = get_controller(doctype)
2024-01-11 15:36:18                  ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 69, in get_controller
2024-01-11 15:36:18     site_controllers[doctype] = import_controller(doctype)
2024-01-11 15:36:18                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 80, in import_controller
2024-01-11 15:36:18     doctype_info = frappe.db.get_value("DocType", doctype, fieldname="*")
2024-01-11 15:36:18                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 466, in get_value
2024-01-11 15:36:18     result = self.get_values(
2024-01-11 15:36:18              ^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 563, in get_values
2024-01-11 15:36:18     out = self._get_values_from_table(
2024-01-11 15:36:18           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 827, in _get_values_from_table
2024-01-11 15:36:18     return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
2024-01-11 15:36:18            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
2024-01-11 15:36:18     result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
2024-01-11 15:36:18              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 194, in sql
2024-01-11 15:36:18     self.connect()
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 109, in connect
2024-01-11 15:36:18     self._conn = self.get_connection()
2024-01-11 15:36:18                  ^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 102, in get_connection
2024-01-11 15:36:18     conn = self._get_connection()
2024-01-11 15:36:18            ^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 108, in _get_connection
2024-01-11 15:36:18     return self.create_connection()
2024-01-11 15:36:18            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 111, in create_connection
2024-01-11 15:36:18     return pymysql.connect(**self.get_connection_settings())
2024-01-11 15:36:18            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 358, in __init__
2024-01-11 15:36:18     self.connect()
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 664, in connect
2024-01-11 15:36:18     self._request_authentication()
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 954, in _request_authentication
2024-01-11 15:36:18     auth_packet = self._read_packet()
2024-01-11 15:36:18                   ^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 772, in _read_packet
2024-01-11 15:36:18     packet.raise_for_error()
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 221, in raise_for_error
2024-01-11 15:36:18     err.raise_mysql_exception(self._data)
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
2024-01-11 15:36:18     raise errorclass(errno, errval)
2024-01-11 15:36:18 pymysql.err.OperationalError: (1045, "Access denied for user '_5e5899d8398b5f7b'@'172.19.0.9' (using password: YES)")
2024-01-11 15:36:18 
2024-01-11 15:36:18 During handling of the above exception, another exception occurred:
2024-01-11 15:36:18 
2024-01-11 15:36:18 Traceback (most recent call last):
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 282, in handle
2024-01-11 15:36:18     keepalive = self.handle_request(req, conn)
2024-01-11 15:36:18                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
2024-01-11 15:36:18     respiter = self.wsgi(environ, resp.start_response)
2024-01-11 15:36:18                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 74, in application
2024-01-11 15:36:18     app(environ, start_response),
2024-01-11 15:36:18     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 189, in application
2024-01-11 15:36:18     resp = f(*args[:-2] + (request,))
2024-01-11 15:36:18            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 128, in application
2024-01-11 15:36:18     response = handle_exception(e)
2024-01-11 15:36:18                ^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 320, in handle_exception
2024-01-11 15:36:18     allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
2024-01-11 15:36:18                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 2300, in get_system_settings
2024-01-11 15:36:18     local.system_settings = get_cached_doc("System Settings")
2024-01-11 15:36:18                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1137, in get_cached_doc
2024-01-11 15:36:18     doc = get_doc(*args, **kwargs)
2024-01-11 15:36:18           ^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1265, in get_doc
2024-01-11 15:36:18     doc = frappe.model.document.get_doc(*args, **kwargs)
2024-01-11 15:36:18           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 80, in get_doc
2024-01-11 15:36:18     controller = get_controller(doctype)
2024-01-11 15:36:18                  ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 69, in get_controller
2024-01-11 15:36:18     site_controllers[doctype] = import_controller(doctype)
2024-01-11 15:36:18                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 80, in import_controller
2024-01-11 15:36:18     doctype_info = frappe.db.get_value("DocType", doctype, fieldname="*")
2024-01-11 15:36:18                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 466, in get_value
2024-01-11 15:36:18     result = self.get_values(
2024-01-11 15:36:18              ^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 563, in get_values
2024-01-11 15:36:18     out = self._get_values_from_table(
2024-01-11 15:36:18           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 827, in _get_values_from_table
2024-01-11 15:36:18     return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
2024-01-11 15:36:18            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
2024-01-11 15:36:18     result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
2024-01-11 15:36:18              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 194, in sql
2024-01-11 15:36:18     self.connect()
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 109, in connect
2024-01-11 15:36:18     self._conn = self.get_connection()
2024-01-11 15:36:18                  ^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 102, in get_connection
2024-01-11 15:36:18     conn = self._get_connection()
2024-01-11 15:36:18            ^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 108, in _get_connection
2024-01-11 15:36:18     return self.create_connection()
2024-01-11 15:36:18            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 111, in create_connection
2024-01-11 15:36:18     return pymysql.connect(**self.get_connection_settings())
2024-01-11 15:36:18            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 358, in __init__
2024-01-11 15:36:18     self.connect()
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 664, in connect
2024-01-11 15:36:18     self._request_authentication()
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 954, in _request_authentication
2024-01-11 15:36:18     auth_packet = self._read_packet()
2024-01-11 15:36:18                   ^^^^^^^^^^^^^^^^^^^
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 772, in _read_packet
2024-01-11 15:36:18     packet.raise_for_error()
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 221, in raise_for_error
2024-01-11 15:36:18     err.raise_mysql_exception(self._data)
2024-01-11 15:36:18   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
2024-01-11 15:36:18     raise errorclass(errno, errval)
2024-01-11 15:36:18 pymysql.err.OperationalError: (1045, "Access denied for user '_5e5899d8398b5f7b'@'172.19.0.9' (using password: YES)")
```

why does one need to access using db name to db host?

**Comment by revant** [comment]
> why does one need to access using db name to db host?

Ask this on frappe framework repo or forum. It was their decision to use dbname and username as same.

**Comment by revant** [comment]
Also 2 issues pointing to same problem. Hope someone solves them for you. https://github.com/frappe/frappe_docker/issues/1308

- You need db_name and database user as same.
- db user should only have wildcard host. It should not have any IP addr. delete user with host as ip addr.
- if user doesn't exist create and grant all priv to same database name.

**Comment by auliabismar** [comment]
> Two issues pointing to same problem. Hope someone solves them for you. #1308
> 
>     * You need db_name and database user as same.
> 
>     * db user should only have wildcard host. It should not have any IP addr. delete user with host as ip addr.
> 
>     * if user doesn't exist create and grant all priv to same database name.

Thanks Revant. Shouldn't these steps include in either the doc or the script?
