### ISSUE TITLE
Custom image with compose.yaml doesn't work

### ISSUE THREAD

**Issue by Tameflame** [frappe/frappe_docker#1329]
## Description of the issue
Using compose.yaml with a custom built image doesn't work

## Context information (for bug reports)

Running wsl2
Cloned the current main branch of frappe_docker
working with the custom image guide

## Steps to reproduce the issue

1. clone git repo
2. mkdir development
3. nano ./development/apps.json and fill with the following
```
    {
      "url": "https://github.com/frappe/gameplan",
      "branch": "main"
    },
    {
      "url": "https://github.com/frappe/erpnext",
      "branch": "develop"
    }
  ]
```
5. build with docker
```
docker build --no-cache \
  --build-arg=FRAPPE_PATH=https://github.com/frappe/frappe \
  --build-arg=FRAPPE_BRANCH=develop \
  --build-arg=PYTHON_VERSION=3.11.6 \
  --build-arg=NODE_VERSION=18.18.2 \
  --build-arg=APPS_JSON_BASE64=$APPS_JSON_BASE64 \
  --tag=shazamo333/avo-erp:latest \
  --file=images/custom/Containerfile .
```
7. run compose.yaml
docker compose -p avo-erp -f compose.yaml up

### Observed result
site fails to load

### Expected result
errors as below

### Stacktrace / full error message if available

Logs for docker compose:

```
tameflame@DESKTOP-AJH3DJK:~/programming/projects/erpnext/avo-frappe$ docker compose -p avo-erp -f compose.yaml up
WARN[0000] The "DB_HOST" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DB_PORT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "REDIS_CACHE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "REDIS_QUEUE" variable is not set. Defaulting to a blank string. 
[+] Running 9/9
 ✔ Network avo-erp_default           Created                                                                                                                                         0.3s 
 ✔ Volume "avo-erp_sites"            Created                                                                                                                                         0.0s 
 ✔ Container avo-erp-configurator-1  Created                                                                                                                                         2.0s 
 ✔ Container avo-erp-websocket-1     Created                                                                                                                                         1.9s 
 ✔ Container avo-erp-scheduler-1     Created                                                                                                                                         1.9s 
 ✔ Container avo-erp-backend-1       Created                                                                                                                                         1.9s 
 ✔ Container avo-erp-queue-long-1    Created                                                                                                                                         1.9s 
 ✔ Container avo-erp-queue-short-1   Created                                                                                                                                         1.9s 
 ✔ Container avo-erp-frontend-1      Created                                                                                                                                         0.5s 
Attaching to backend-1, configurator-1, frontend-1, queue-long-1, queue-short-1, scheduler-1, websocket-1
configurator-1  | Usage: bench  set-config [OPTIONS] KEY VALUE
configurator-1  | Try 'bench  set-config --help' for help.
configurator-1  | 
configurator-1  | Error: Missing argument 'VALUE'.
configurator-1  | Usage: bench  set-config [OPTIONS] KEY VALUE
configurator-1  | Try 'bench  set-config --help' for help.
configurator-1  | 
configurator-1  | Error: Missing argument 'VALUE'.
configurator-1 exited with code 0
websocket-1     | Realtime service listening on:  9000
websocket-1     | node:internal/process/promises:288
websocket-1     |             triggerUncaughtException(err, true /* fromPromise */);
websocket-1     |             ^
websocket-1     | 
websocket-1     | Error: connect ECONNREFUSED 127.0.0.1:6379
websocket-1     |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
websocket-1     | Emitted 'error' event on RedisClient instance at:
websocket-1     |     at RedisSocket.<anonymous> (/home/frappe/frappe-bench/apps/frappe/node_modules/@redis/client/dist/lib/client/index.js:412:14)
websocket-1     |     at RedisSocket.emit (node:events:517:28)
websocket-1     |     at RedisSocket._RedisSocket_connect (/home/frappe/frappe-bench/apps/frappe/node_modules/@redis/client/dist/lib/client/socket.js:166:18)
websocket-1     |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
websocket-1     |     at async RedisClient.connect (/home/frappe/frappe-bench/apps/frappe/node_modules/@redis/client/dist/lib/client/index.js:185:9)
websocket-1     |     at async /home/frappe/frappe-bench/apps/frappe/realtime/index.js:44:2 {
websocket-1     |   errno: -111,
websocket-1     |   code: 'ECONNREFUSED',
websocket-1     |   syscall: 'connect',
websocket-1     |   address: '127.0.0.1',
websocket-1     |   port: 6379
websocket-1     | }
websocket-1     | 
websocket-1     | Node.js v18.18.2
backend-1       | [2024-02-04 12:42:29 +0000] [1] [INFO] Starting gunicorn 21.2.0
backend-1       | [2024-02-04 12:42:29 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
backend-1       | [2024-02-04 12:42:29 +0000] [1] [INFO] Using worker: gthread
backend-1       | [2024-02-04 12:42:29 +0000] [7] [INFO] Booting worker with pid: 7
websocket-1 exited with code 1
backend-1       | [2024-02-04 12:42:29 +0000] [8] [INFO] Booting worker with pid: 8
queue-long-1    | Traceback (most recent call last):
queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 264, in connect
queue-long-1    |     sock = self.retry.call_with_retry(
queue-long-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
queue-long-1    |     return do()
queue-long-1    |            ^^^^
queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 265, in <lambda>
queue-long-1    |     lambda: self._connect(), lambda error: self.disconnect(error)
queue-long-1    |             ^^^^^^^^^^^^^^^
queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 627, in _connect
queue-long-1    |     raise err
queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 615, in _connect
queue-long-1    |     sock.connect(socket_address)
queue-long-1    | OSError: [Errno 99] Cannot assign requested address
queue-long-1    | 
queue-long-1    | During handling of the above exception, another exception occurred:
queue-long-1    | 
queue-long-1    | Traceback (most recent call last):
queue-long-1    |   File "<frozen runpy>", line 198, in _run_module_as_main
queue-long-1    |   File "<frozen runpy>", line 88, in _run_code
queue-long-1    |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
queue-long-1    |     main()
queue-long-1    |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
queue-long-1    |     click.Group(commands=commands)(prog_name="bench")
queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
queue-long-1    |     return self.main(*args, **kwargs)
queue-long-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1078, in main
queue-long-1    |     rv = self.invoke(ctx)
queue-long-1    |          ^^^^^^^^^^^^^^^^
queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
queue-long-1    |     return _process_result(sub_ctx.command.invoke(sub_ctx))
queue-long-1    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
queue-long-1    |     return _process_result(sub_ctx.command.invoke(sub_ctx))
queue-long-1    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
queue-long-1    |     return ctx.invoke(self.callback, **ctx.params)
queue-long-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
queue-long-1    |     return __callback(*args, **kwargs)
queue-long-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-long-1    |   File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 208, in start_worker
queue-long-1    |     start_worker(
queue-long-1    |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 281, in start_worker
queue-long-1    |     redis_connection = get_redis_conn(username=rq_username, password=rq_password)
queue-long-1    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
queue-long-1    |     return self(f, *args, **kw)
queue-long-1    |            ^^^^^^^^^^^^^^^^^^^^
queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
queue-long-1    |     do = self.iter(retry_state=retry_state)
queue-long-1    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/tenacity/__init__.py", line 325, in iter
queue-long-1    |     raise retry_exc.reraise()
queue-long-1    |           ^^^^^^^^^^^^^^^^^^^
queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/tenacity/__init__.py", line 158, in reraise
queue-long-1    |     raise self.last_attempt.result()
queue-long-1    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-long-1    |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
queue-long-1    |     return self.__get_result()
queue-long-1    |            ^^^^^^^^^^^^^^^^^^^
queue-long-1    |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
queue-long-1    |     raise self._exception
queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
queue-long-1    |     result = fn(*args, **kwargs)
queue-long-1    |              ^^^^^^^^^^^^^^^^^^^
queue-long-1    |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 466, in get_redis_conn
queue-long-1    |     return get_redis_connection_without_auth()
queue-long-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-long-1    |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 488, in get_redis_connection_without_auth
queue-long-1    |     _redis_queue_conn = RedisQueue.get_connection()
queue-long-1    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-long-1    |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_queue.py", line 21, in get_connection
queue-long-1    |     conn.ping()
queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/commands/core.py", line 1216, in ping
queue-long-1    |     return self.execute_command("PING", **kwargs)
queue-long-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/client.py", line 533, in execute_command
queue-long-1    |     conn = self.connection or pool.get_connection(command_name, **options)
queue-long-1    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 1086, in get_connection
queue-long-1    |     connection.connect()
queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 270, in connect
queue-long-1    |     raise ConnectionError(self._error_message(e))
queue-long-1    | redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.
queue-long-1    | Please make sure that Redis Queue runs @ redis://. Redis reported error: Error 99 connecting to localhost:6379. Cannot assign requested address.
queue-long-1    | Please make sure that Redis Queue runs @ redis://. Redis reported error: Error 99 connecting to localhost:6379. Cannot assign requested address.
queue-long-1    | Please make sure that Redis Queue runs @ redis://. Redis reported error: Error 99 connecting to localhost:6379. Cannot assign requested address.
queue-long-1    | Please make sure that Redis Queue runs @ redis://. Redis reported error: Error 99 connecting to localhost:6379. Cannot assign requested address.
queue-long-1    | Please make sure that Redis Queue runs @ redis://. Redis reported error: Error 99 connecting to localhost:6379. Cannot assign requested address.
queue-short-1   | Traceback (most recent call last):
queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 264, in connect
queue-short-1   |     sock = self.retry.call_with_retry(
queue-short-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
queue-short-1   |     return do()
queue-short-1   |            ^^^^
queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 265, in <lambda>
queue-short-1   |     lambda: self._connect(), lambda error: self.disconnect(error)
queue-short-1   |             ^^^^^^^^^^^^^^^
queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 627, in _connect
queue-short-1   |     raise err
queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 615, in _connect
queue-short-1   |     sock.connect(socket_address)
queue-short-1   | OSError: [Errno 99] Cannot assign requested address
queue-short-1   | 
queue-short-1   | During handling of the above exception, another exception occurred:
queue-short-1   | 
queue-short-1   | Traceback (most recent call last):
queue-short-1   |   File "<frozen runpy>", line 198, in _run_module_as_main
queue-short-1   |   File "<frozen runpy>", line 88, in _run_code
queue-short-1   |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
queue-short-1   |     main()
queue-short-1   |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
queue-short-1   |     click.Group(commands=commands)(prog_name="bench")
queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
queue-short-1   |     return self.main(*args, **kwargs)
queue-short-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1078, in main
queue-short-1   |     rv = self.invoke(ctx)
queue-short-1   |          ^^^^^^^^^^^^^^^^
queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
queue-short-1   |     return _process_result(sub_ctx.command.invoke(sub_ctx))
queue-short-1   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
queue-short-1   |     return _process_result(sub_ctx.command.invoke(sub_ctx))
queue-short-1   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
queue-short-1   |     return ctx.invoke(self.callback, **ctx.params)
queue-short-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
queue-short-1   |     return __callback(*args, **kwargs)
queue-short-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-short-1   |   File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 208, in start_worker
queue-short-1   |     start_worker(
queue-short-1   |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 281, in start_worker
queue-short-1   |     redis_connection = get_redis_conn(username=rq_username, password=rq_password)
queue-short-1   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
queue-short-1   |     return self(f, *args, **kw)
queue-short-1   |            ^^^^^^^^^^^^^^^^^^^^
queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
queue-short-1   |     do = self.iter(retry_state=retry_state)
queue-short-1   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/tenacity/__init__.py", line 325, in iter
queue-short-1   |     raise retry_exc.reraise()
queue-short-1   |           ^^^^^^^^^^^^^^^^^^^
queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/tenacity/__init__.py", line 158, in reraise
queue-short-1   |     raise self.last_attempt.result()
queue-short-1   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-short-1   |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
queue-short-1   |     return self.__get_result()
queue-short-1   |            ^^^^^^^^^^^^^^^^^^^
queue-short-1   |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
queue-short-1   |     raise self._exception
queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
queue-short-1   |     result = fn(*args, **kwargs)
queue-short-1   |              ^^^^^^^^^^^^^^^^^^^
queue-short-1   |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 466, in get_redis_conn
queue-short-1   |     return get_redis_connection_without_auth()
queue-short-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-short-1   |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 488, in get_redis_connection_without_auth
queue-short-1   |     _redis_queue_conn = RedisQueue.get_connection()
queue-short-1   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-short-1   |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_queue.py", line 21, in get_connection
queue-short-1   |     conn.ping()
queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/commands/core.py", line 1216, in ping
queue-short-1   |     return self.execute_command("PING", **kwargs)
queue-short-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/client.py", line 533, in execute_command
queue-short-1   |     conn = self.connection or pool.get_connection(command_name, **options)
queue-short-1   |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 1086, in get_connection
queue-short-1   |     connection.connect()
queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 270, in connect
queue-short-1   |     raise ConnectionError(self._error_message(e))
queue-short-1   | redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.
queue-short-1   | Please make sure that Redis Queue runs @ redis://. Redis reported error: Error 99 connecting to localhost:6379. Cannot assign requested address.
queue-short-1   | Please make sure that Redis Queue runs @ redis://. Redis reported error: Error 99 connecting to localhost:6379. Cannot assign requested address.
queue-short-1   | Please make sure that Redis Queue runs @ redis://. Redis reported error: Error 99 connecting to localhost:6379. Cannot assign requested address.
queue-short-1   | Please make sure that Redis Queue runs @ redis://. Redis reported error: Error 99 connecting to localhost:6379. Cannot assign requested address.
queue-short-1   | Please make sure that Redis Queue runs @ redis://. Redis reported error: Error 99 connecting to localhost:6379. Cannot assign requested address.
queue-long-1 exited with code 1
queue-short-1 exited with code 1
```

**Comment by Tameflame** [comment]
Okay I realised that I had to generate a new yaml file rather than use the compose.yaml file.

Thanks
