### ISSUE TITLE
docker-compose fails with 'chunked' error

### ISSUE THREAD

**Issue by saru2020** [frappe/frappe_docker#1400]
## Description of the issue
I'm following [custom-apps](https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md) doc for setup
## Context information (for bug reports)
NOTE: trying to setup with https override

> `sudo docker compose version`
> Docker Compose version v2.27.0

> `sudo docker --version`
Docker version 26.1.3, build b72abbb

## Steps to reproduce the issue

`sudo docker-compose -f compose.yaml -f overrides/compose.https.yaml config > ~/gitops/docker-compose.yml`
`sudo docker-compose -f ~/gitops/docker-compose.yml up -d`

### Observed result
fails to build docker images/containers
### Expected result
docker images/containers should get built
### Stacktrace / full error message if available

```
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
           ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
             ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: HTTPConnection.request() got an unexpected keyword argument 'chunked'
```

what am I doing wrong here?

**Comment by beowulf1416** [comment]
I am also experiencing the exact same issue.

**Comment by saru2020** [comment]
@beowulf1416  nobody's going to answer our queries, it is just up to us to figure out everything, that's the biggest caveat working with frappe community :(

**Comment by saru2020** [comment]
> This issue has been automatically marked as stale. You have a week to explain why you believe this is an error.

not fair!
