### ISSUE TITLE
Git pull repository, docker compose up, compose script broken

### ISSUE THREAD

**Issue by mezka** [frappe/frappe_docker#1404]
## Description of the issue

Ubuntu 22.04 with official docker repo docker runtime and docker scripts

compose.yaml broken

## Context information (for bug reports)

docker compose up

## Steps to reproduce the issue

1. Pull the repo
2. docker compose up

### Observed result

Broken compose script

### Expected result

Working ERPNEXT installation

### Stacktrace / full error message if available

```
sudo docker compose up
[+] Running 7/0
 ✔ Container frappe_docker_mesquita-configurator-1  Created                                                                                                                                                                             0.0s 
 ✔ Container frappe_docker_mesquita-queue-long-1    Created                                                                                                                                                                             0.0s 
 ✔ Container frappe_docker_mesquita-queue-short-1   Created                                                                                                                                                                             0.0s 
 ✔ Container frappe_docker_mesquita-scheduler-1     Created                                                                                                                                                                             0.0s 
 ✔ Container frappe_docker_mesquita-backend-1       Created                                                                                                                                                                             0.0s 
 ✔ Container frappe_docker_mesquita-websocket-1     Created                                                                                                                                                                             0.0s 
 ✔ Container frappe_docker_mesquita-frontend-1      Created                                                                                                                                                                             0.0s 
Attaching to frappe_docker_mesquita-backend-1, frappe_docker_mesquita-configurator-1, frappe_docker_mesquita-frontend-1, frappe_docker_mesquita-queue-long-1, frappe_docker_mesquita-queue-short-1, frappe_docker_mesquita-scheduler-1, frappe_docker_mesquita-websocket-1
frappe_docker_mesquita-configurator-1  | Usage: bench  set-config [OPTIONS] KEY VALUE
frappe_docker_mesquita-configurator-1  | Try 'bench  set-config --help' for help.
frappe_docker_mesquita-configurator-1  | 
frappe_docker_mesquita-configurator-1  | 
frappe_docker_mesquita-configurator-1  | Error: Missing argument 'VALUE'.
frappe_docker_mesquita-configurator-1  | Usage: bench  set-config [OPTIONS] KEY VALUE
frappe_docker_mesquita-configurator-1  | Try 'bench  set-config --help' for help.
frappe_docker_mesquita-configurator-1  | 
frappe_docker_mesquita-configurator-1  | 
frappe_docker_mesquita-configurator-1  | Error: Missing argument 'VALUE'.
frappe_docker_mesquita-configurator-1 exited with code 0
frappe_docker_mesquita-websocket-1     | Realtime service listening on:  9000
frappe_docker_mesquita-websocket-1     | node:internal/process/promises:288
frappe_docker_mesquita-websocket-1     |             triggerUncaughtException(err, true /* fromPromise */);
frappe_docker_mesquita-websocket-1     |             ^
frappe_docker_mesquita-websocket-1     | 
frappe_docker_mesquita-websocket-1     | Error: connect ECONNREFUSED 127.0.0.1:6379
frappe_docker_mesquita-websocket-1     |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
frappe_docker_mesquita-websocket-1     | Emitted 'error' event on RedisClient instance at:
frappe_docker_mesquita-websocket-1     |     at RedisSocket.<anonymous> (/home/frappe/frappe-bench/apps/frappe/node_modules/@redis/client/dist/lib/client/index.js:412:14)
frappe_docker_mesquita-websocket-1     |     at RedisSocket.emit (node:events:517:28)
frappe_docker_mesquita-websocket-1     |     at RedisSocket._RedisSocket_connect (/home/frappe/frappe-bench/apps/frappe/node_modules/@redis/client/dist/lib/client/socket.js:166:18)
frappe_docker_mesquita-websocket-1     |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
frappe_docker_mesquita-websocket-1     |     at async RedisClient.connect (/home/frappe/frappe-bench/apps/frappe/node_modules/@redis/client/dist/lib/client/index.js:185:9)
frappe_docker_mesquita-websocket-1     |     at async /home/frappe/frappe-bench/apps/frappe/realtime/index.js:44:2 {
frappe_docker_mesquita-websocket-1     |   errno: -111,
frappe_docker_mesquita-websocket-1     |   code: 'ECONNREFUSED',
frappe_docker_mesquita-websocket-1     |   syscall: 'connect',
frappe_docker_mesquita-websocket-1     |   address: '127.0.0.1',
frappe_docker_mesquita-websocket-1     |   port: 6379
frappe_docker_mesquita-websocket-1     | }
frappe_docker_mesquita-websocket-1     | 
frappe_docker_mesquita-websocket-1     | Node.js v18.18.2
frappe_docker_mesquita-websocket-1     | 
frappe_docker_mesquita-websocket-1 exited with code 1
frappe_docker_mesquita-frontend-1      | 2024/06/03 02:19:52 [emerg] 8#8: host not found in upstream "websocket:9000" in /etc/nginx/conf.d/frappe.conf:6
frappe_docker_mesquita-frontend-1 exited with code 1
frappe_docker_mesquita-backend-1       | [2024-06-03 02:19:52 +0000] [1] [INFO] Starting gunicorn 22.0.0
frappe_docker_mesquita-backend-1       | [2024-06-03 02:19:52 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
frappe_docker_mesquita-backend-1       | [2024-06-03 02:19:52 +0000] [1] [INFO] Using worker: gthread
frappe_docker_mesquita-backend-1       | [2024-06-03 02:19:52 +0000] [7] [INFO] Booting worker with pid: 7
frappe_docker_mesquita-backend-1       | [2024-06-03 02:19:52 +0000] [8] [INFO] Booting worker with pid: 8
frappe_docker_mesquita-queue-short-1   | Traceback (most recent call last):
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 699, in connect
frappe_docker_mesquita-queue-short-1   |     sock = self.retry.call_with_retry(
frappe_docker_mesquita-queue-short-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
frappe_docker_mesquita-queue-short-1   |     return do()
frappe_docker_mesquita-queue-short-1   |            ^^^^
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 700, in <lambda>
frappe_docker_mesquita-queue-short-1   |     lambda: self._connect(), lambda error: self.disconnect(error)
frappe_docker_mesquita-queue-short-1   |             ^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 1002, in _connect
frappe_docker_mesquita-queue-short-1   |     raise err
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 990, in _connect
frappe_docker_mesquita-queue-short-1   |     sock.connect(socket_address)
frappe_docker_mesquita-queue-short-1   | OSError: [Errno 99] Cannot assign requested address
frappe_docker_mesquita-queue-short-1   | 
frappe_docker_mesquita-queue-short-1   | During handling of the above exception, another exception occurred:
frappe_docker_mesquita-queue-short-1   | 
frappe_docker_mesquita-queue-short-1   | Traceback (most recent call last):
frappe_docker_mesquita-queue-short-1   | 
frappe_docker_mesquita-queue-short-1   |   File "<frozen runpy>", line 198, in _run_module_as_main
frappe_docker_mesquita-queue-short-1   |   File "<frozen runpy>", line 88, in _run_code
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
frappe_docker_mesquita-queue-short-1   |     main()
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
frappe_docker_mesquita-queue-short-1   |     click.Group(commands=commands)(prog_name="bench")
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
frappe_docker_mesquita-queue-short-1   |     return self.main(*args, **kwargs)
frappe_docker_mesquita-queue-short-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1078, in main
frappe_docker_mesquita-queue-short-1   |     rv = self.invoke(ctx)
frappe_docker_mesquita-queue-short-1   |          ^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
frappe_docker_mesquita-queue-short-1   |     return _process_result(sub_ctx.command.invoke(sub_ctx))
frappe_docker_mesquita-queue-short-1   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
frappe_docker_mesquita-queue-short-1   |     return _process_result(sub_ctx.command.invoke(sub_ctx))
frappe_docker_mesquita-queue-short-1   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
frappe_docker_mesquita-queue-short-1   |     return ctx.invoke(self.callback, **ctx.params)
frappe_docker_mesquita-queue-short-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
frappe_docker_mesquita-queue-short-1   |     return __callback(*args, **kwargs)
frappe_docker_mesquita-queue-short-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 202, in start_worker
frappe_docker_mesquita-queue-short-1   |     start_worker(
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 280, in start_worker
frappe_docker_mesquita-queue-short-1   |     redis_connection = get_redis_conn(username=rq_username, password=rq_password)
frappe_docker_mesquita-queue-short-1   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
frappe_docker_mesquita-queue-short-1   |     return self(f, *args, **kw)
frappe_docker_mesquita-queue-short-1   |            ^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
frappe_docker_mesquita-queue-short-1   |     do = self.iter(retry_state=retry_state)
frappe_docker_mesquita-queue-short-1   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/tenacity/__init__.py", line 325, in iter
frappe_docker_mesquita-queue-short-1   |     raise retry_exc.reraise()
frappe_docker_mesquita-queue-short-1   |           ^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/tenacity/__init__.py", line 158, in reraise
frappe_docker_mesquita-queue-short-1   |     raise self.last_attempt.result()
frappe_docker_mesquita-queue-short-1   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-short-1   |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
frappe_docker_mesquita-queue-short-1   |     return self.__get_result()
frappe_docker_mesquita-queue-short-1   |            ^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-short-1   |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
frappe_docker_mesquita-queue-short-1   |     raise self._exception
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
frappe_docker_mesquita-queue-short-1   |     result = fn(*args, **kwargs)
frappe_docker_mesquita-queue-short-1   |              ^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 473, in get_redis_conn
frappe_docker_mesquita-queue-short-1   |     return get_redis_connection_without_auth()
frappe_docker_mesquita-queue-short-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 495, in get_redis_connection_without_auth
frappe_docker_mesquita-queue-short-1   |     _redis_queue_conn = RedisQueue.get_connection()
frappe_docker_mesquita-queue-short-1   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_queue.py", line 35, in get_connection
frappe_docker_mesquita-queue-short-1   |     conn.ping()
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/commands/core.py", line 1205, in ping
frappe_docker_mesquita-queue-short-1   |     return self.execute_command("PING", **kwargs)
frappe_docker_mesquita-queue-short-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/client.py", line 1266, in execute_command
frappe_docker_mesquita-queue-short-1   |     conn = self.connection or pool.get_connection(command_name, **options)
frappe_docker_mesquita-queue-short-1   |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 1457, in get_connection
frappe_docker_mesquita-queue-short-1   |     connection.connect()
frappe_docker_mesquita-queue-short-1   |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 705, in connect
frappe_docker_mesquita-queue-short-1   |     raise ConnectionError(self._error_message(e))
frappe_docker_mesquita-queue-short-1   | redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.
frappe_docker_mesquita-queue-short-1   | Please make sure that Redis Queue runs @ redis://. Redis reported error: Error 99 connecting to localhost:6379. Cannot assign requested address.
frappe_docker_mesquita-queue-short-1   | Please make sure that Redis Queue runs @ redis://. Redis reported error: Error 99 connecting to localhost:6379. Cannot assign requested address.
frappe_docker_mesquita-queue-short-1   | Please make sure that Redis Queue runs @ redis://. Redis reported error: Error 99 connecting to localhost:6379. Cannot assign requested address.
frappe_docker_mesquita-queue-short-1   | Please make sure that Redis Queue runs @ redis://. Redis reported error: Error 99 connecting to localhost:6379. Cannot assign requested address.
frappe_docker_mesquita-queue-short-1   | Please make sure that Redis Queue runs @ redis://. Redis reported error: Error 99 connecting to localhost:6379. Cannot assign requested address.
frappe_docker_mesquita-queue-long-1    | Traceback (most recent call last):
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 699, in connect
frappe_docker_mesquita-queue-long-1    |     sock = self.retry.call_with_retry(
frappe_docker_mesquita-queue-long-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
frappe_docker_mesquita-queue-long-1    |     return do()
frappe_docker_mesquita-queue-long-1    |            ^^^^
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 700, in <lambda>
frappe_docker_mesquita-queue-long-1    |     lambda: self._connect(), lambda error: self.disconnect(error)
frappe_docker_mesquita-queue-long-1    |             ^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 1002, in _connect
frappe_docker_mesquita-queue-long-1    |     raise err
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 990, in _connect
frappe_docker_mesquita-queue-long-1    |     sock.connect(socket_address)
frappe_docker_mesquita-queue-long-1    | OSError: [Errno 99] Cannot assign requested address
frappe_docker_mesquita-queue-long-1    | 
frappe_docker_mesquita-queue-long-1    | During handling of the above exception, another exception occurred:
frappe_docker_mesquita-queue-long-1    | 
frappe_docker_mesquita-queue-long-1    | Traceback (most recent call last):
frappe_docker_mesquita-queue-long-1    |   File "<frozen runpy>", line 198, in _run_module_as_main
frappe_docker_mesquita-queue-long-1    |   File "<frozen runpy>", line 88, in _run_code
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
frappe_docker_mesquita-queue-long-1    |     main()
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
frappe_docker_mesquita-queue-long-1    |     click.Group(commands=commands)(prog_name="bench")
frappe_docker_mesquita-queue-long-1    | 
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
frappe_docker_mesquita-queue-long-1    |     return self.main(*args, **kwargs)
frappe_docker_mesquita-queue-long-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1078, in main
frappe_docker_mesquita-queue-long-1    |     rv = self.invoke(ctx)
frappe_docker_mesquita-queue-long-1    |          ^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
frappe_docker_mesquita-queue-long-1    |     return _process_result(sub_ctx.command.invoke(sub_ctx))
frappe_docker_mesquita-queue-long-1    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
frappe_docker_mesquita-queue-long-1    |     return _process_result(sub_ctx.command.invoke(sub_ctx))
frappe_docker_mesquita-queue-long-1    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
frappe_docker_mesquita-queue-long-1    |     return ctx.invoke(self.callback, **ctx.params)
frappe_docker_mesquita-queue-long-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
frappe_docker_mesquita-queue-long-1    |     return __callback(*args, **kwargs)
frappe_docker_mesquita-queue-long-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 202, in start_worker
frappe_docker_mesquita-queue-long-1    |     start_worker(
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 280, in start_worker
frappe_docker_mesquita-queue-long-1    |     redis_connection = get_redis_conn(username=rq_username, password=rq_password)
frappe_docker_mesquita-queue-long-1    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
frappe_docker_mesquita-queue-long-1    |     return self(f, *args, **kw)
frappe_docker_mesquita-queue-long-1    |            ^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
frappe_docker_mesquita-queue-long-1    |     do = self.iter(retry_state=retry_state)
frappe_docker_mesquita-queue-long-1    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/tenacity/__init__.py", line 325, in iter
frappe_docker_mesquita-queue-long-1    |     raise retry_exc.reraise()
frappe_docker_mesquita-queue-long-1    |           ^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/tenacity/__init__.py", line 158, in reraise
frappe_docker_mesquita-queue-long-1    |     raise self.last_attempt.result()
frappe_docker_mesquita-queue-long-1    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-long-1    |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
frappe_docker_mesquita-queue-long-1    |     return self.__get_result()
frappe_docker_mesquita-queue-long-1    |            ^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-long-1    |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
frappe_docker_mesquita-queue-long-1    |     raise self._exception
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
frappe_docker_mesquita-queue-long-1    |     result = fn(*args, **kwargs)
frappe_docker_mesquita-queue-long-1    |              ^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 473, in get_redis_conn
frappe_docker_mesquita-queue-long-1    |     return get_redis_connection_without_auth()
frappe_docker_mesquita-queue-long-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 495, in get_redis_connection_without_auth
frappe_docker_mesquita-queue-long-1    |     _redis_queue_conn = RedisQueue.get_connection()
frappe_docker_mesquita-queue-long-1    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_queue.py", line 35, in get_connection
frappe_docker_mesquita-queue-long-1    |     conn.ping()
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/commands/core.py", line 1205, in ping
frappe_docker_mesquita-queue-long-1    |     return self.execute_command("PING", **kwargs)
frappe_docker_mesquita-queue-long-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/client.py", line 1266, in execute_command
frappe_docker_mesquita-queue-long-1    |     conn = self.connection or pool.get_connection(command_name, **options)
frappe_docker_mesquita-queue-long-1    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 1457, in get_connection
frappe_docker_mesquita-queue-long-1    |     connection.connect()
frappe_docker_mesquita-queue-long-1    |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/redis/connection.py", line 705, in connect
frappe_docker_mesquita-queue-long-1    |     raise ConnectionError(self._error_message(e))
frappe_docker_mesquita-queue-long-1    | redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.
frappe_docker_mesquita-queue-long-1    | Please make sure that Redis Queue runs @ redis://. Redis reported error: Error 99 connecting to localhost:6379. Cannot assign requested address.
frappe_docker_mesquita-queue-long-1    | Please make sure that Redis Queue runs @ redis://. Redis reported error: Error 99 connecting to localhost:6379. Cannot assign requested address.
frappe_docker_mesquita-queue-long-1    | Please make sure that Redis Queue runs @ redis://. Redis reported error: Error 99 connecting to localhost:6379. Cannot assign requested address.
frappe_docker_mesquita-queue-long-1    | Please make sure that Redis Queue runs @ redis://. Redis reported error: Error 99 connecting to localhost:6379. Cannot assign requested address.
frappe_docker_mesquita-queue-long-1    | Please make sure that Redis Queue runs @ redis://. Redis reported error: Error 99 connecting to localhost:6379. Cannot assign requested address.
frappe_docker_mesquita-queue-short-1 exited with code 1
frappe_docker_mesquita-queue-long-1 exited with code 1

```

**Comment by dnk8n** [comment]
Same here, similar error messages on v14 and v15. Docker setup is broken out of the box. Had to create a .env file with `ERPNEXT_VERSION=v14` for example.

**Comment by germa89** [comment]
> Same here, similar error messages on v14 and v15. Docker setup is broken out of the box. Had to create a .env file with `ERPNEXT_VERSION=v14` for example.

This didn't work for me. Using MacOS M2. I did try the compose from: https://github.com/frappe/frappe_docker/blob/main/docs/setup_for_linux_mac.md but I wasn't lucky either.

**Comment by dnk8n** [comment]
I eventually worked it out.

The Frappe docs has recently improved by a PR clearing up how to [use PWD in your own environment](https://github.com/frappe/frappe_docker/tree/main#try-on-your-dev-environment)

That is more for play / demo, [read this to setup development environment](https://github.com/frappe/frappe_docker/blob/main/docs/development.md): 

Modern MacOS users will need to patch their docker-compose file with [the changes of this PR](https://github.com/frappe/frappe_docker/pull/1415/files).

**Comment by germa89** [comment]
I end up rebuilding the docker images in the raspberry pi 5.... now it works perfect.

**Comment by dnk8n** [comment]
@Chev91 Your changes making people's lives easier!
