### ISSUE TITLE
bench keep stoping i have to restart docker containers

### ISSUE THREAD

**Issue by ahmadRagheb** [frappe/frappe_docker#1430]
i have issue when i run docker development :
Traceback (most recent call last):
  File "/home/frappe/.local/bin/bench", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/frappe/.bench/bench/cli.py", line 74, in cli
    cmd_from_sys = get_cmd_from_sysargv()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/.bench/bench/utils/__init__.py", line 581, in get_cmd_from_sysargv
    if sys_argv.index(arg) == 0 and arg in Bench(".").apps:
                                           ^^^^^^^^^^
  File "/home/frappe/.bench/bench/bench.py", line 62, in __init__
    self.cwd = os.path.abspath(path)
               ^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 404, in abspath
FileNotFoundError: [Errno 2] No such file or directory

i have to stop and then start docker then start bench to get it work

**Comment by ahmadRagheb** [comment]
i cant see the files in the vs code , like am disconnected from container on my vscode
