### ISSUE TITLE
RQ Logs  frappe.exceptions.IncorrectSitePath: 404 Not Found: <sitename> does not exist

### ISSUE THREAD

**Issue by letajmal** [frappe/frappe_docker#1437]
## Description of the issue
Issue with DNS Resolution in Docker Compose Single Server Multi Bench Setup

## Context information (for bug reports)

Service names are the same when following the default instructions in Single Server Example

Because multiple projects share a MariaDB service using the same network (mariadb-network) and have the same service names, I was getting an error in the scheduler itself because jobs are being assigned to a different project's scheduler, leading to job failures.

From the Docker Docs AI,
> If you have two Docker Compose projects with the same service names but different networks, there should not be any conflict because the DNS resolution is network-scoped. This means that a service web in network1 is not the same as a service web in network2, even if they have the same service name. They can coexist without any issues because they are in different networks.
However, if the services are also attached to a shared network, the situation can be different. If a service tries to resolve a hostname, and the hostname is present in both the project-specific network and the shared network, Docker does not guarantee which one it will resolve to. This is because a network-wide alias can be shared by multiple containers, and even by multiple services. If it is, then exactly which container the name resolves to is not guaranteed [[source](https://docs.docker.com/compose/compose-file/05-services/#aliases)].

**You can fix this by giving each service a unique name or hostname, or by using separate MariaDB instances for each Docker Compose project.**

Using separate MariaDB instances means you don't need to share the mariadb-network. We still share the traefik-network for the frontend, but since other services aren't on this network, we can use the same service names. However, the best solution is to give unique service names, hostnames, or aliases in each project.
## Steps to reproduce the issue

1. Create mutiple benches by following the Single Server Docker Compose Docs

### Observed result
RQ Jobs Failing
### Stacktrace / full error message if available
Docker Logs
```
Traceback (most recent call last):
File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/rq/worker.py", line 1449, in perform_job job.execute_failure_callback(self.death_penalty_class, *exc_info)
File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/rq/job.py", line 1429, in execute_failure_callback self.failure_callback(self, self.connection, *exc_info)
File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 565, in truncate_failed_registry conf frappe.conf if frappe.conf else appe.get_conf(site=job.kwargs.get("site"))
File "/home/frappe/frappe-bench/apps/frappe/frappe/_init_.py", line 399, in get_conf with init_site(site):
File "/home/frappe/frappe-bench/apps/frappe/frappe/_init_.py", line 409, in _enter_ init(self.site)
File "/home/frappe/frappe-bench/apps/frappe/frappe/_init_.py", line 239, in init local.conf = dict(get_site_config())
File "/home/frappe/frappe-bench/apps/frappe/frappe/_init__.py", line 337, in get_site_config
raise IncorrectSitePath(f"{local.site) does not exist")
frappe.exceptions.IncorrectSitePath: 404 Not Found: <sitename> does not exist
```
RQ Logs

![image](https://github.com/user-attachments/assets/f0247191-d093-4a58-8da5-719c37711243)

**Comment by letajmal** [comment]
> @letajmal how did you solve this? I am specifically interested in this comment of yours
> ```
> However, the best solution is to give unique service names, hostnames, or aliases in each project.
> ```
> What changes should I make to my setup if I am following their docs?

Give unique names to every service in the docker compose file.

For eg:
`backend-<project name>` instead of `backend`

**Comment by letajmal** [comment]
You need to change the service names in common site config as well
