### ISSUE TITLE
How to test emails with mailpit

### ISSUE THREAD

**Issue by giulio-perosino** [frappe/frappe_docker#1446]
Hello,
I'm attempting to enable the Mailpit service. I have successfully initiated the container and can access the GUI on port 8025.
The documentation in [docs/development.md](https://github.com/frappe/frappe_docker/blob/e70b9954c6115f4dd55e7e43ca4e1906da130147/docs/development.md) lacks of instructions so has left me perplexed about the next steps. How do I configure my Frappe instance to connect with the Mailpit service?

Thank you.

**Comment by WebsiteDeveloper** [comment]
You have to setup an outgoing email account with the server as "mailpit" and the port as 1025

**Comment by giulio-perosino** [comment]
Hello @WebsiteDeveloper, thank you for the assistance. To create an outgoing email account, I need to set up a domain, but I'm unsure about the values that need to be entered.

![image](https://github.com/user-attachments/assets/dfa93295-1f4e-4558-a464-88a5cb7d3bbe)

If I use "mailpit" as incoming and outgoing server and 1025 as port Frappe throws an error:
`frappe.exceptions.ValidationError: Error connecting via IMAP/POP3: b'220 ff15acf9ec27 Mailpit ESMTP Service ready'`

**Comment by WebsiteDeveloper** [comment]
You can only use mailpit as an outgoing server per default which you need to configure in the E-Mail Account Doctype not in E-Mail Domain
If you want to use incoming Mails you would need to change the mailpit config see https://mailpit.axllent.org/docs/configuration/pop3/

**Comment by revant** [comment]
video for reference:

https://github.com/user-attachments/assets/585a3ef8-3504-4d99-8eb9-9530cc678f56

**Comment by giulio-perosino** [comment]
@revant thanks for the video reference, I followed the steps and when I want to send the pending email I get this error: "HostNotFoundError"

```js
172.18.0.1 - - [10/Feb/2025 08:24:13] "GET /assets/frappe/node_modules/ace-builds/src-noconflict/ace.js?v=1739175853564 HTTP/1.1" 200 -
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 115, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 50, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1700, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 448, in send_now
    record.send()
  File "apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 168, in send
    message = ctx.build_message(recipient.recipient)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 318, in build_message
    message = self.include_attachments(message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 395, in include_attachments
    print_format_file = frappe.attach_print(**attachment)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 2155, in attach_print
    else get_print(doctype, name, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 2114, in get_print
    return get_pdf(html, options=pdf_options, output=output) if as_pdf else html
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/pdf.py", line 94, in get_pdf
    filedata = pdfkit.from_string(html, options=options or {}, verbose=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pdfkit/api.py", line 75, in from_string
    return r.to_pdf(output_path)
           ^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pdfkit/pdfkit.py", line 201, in to_pdf
    self.handle_error(exit_code, stderr)
  File "env/lib/python3.11/site-packages/pdfkit/pdfkit.py", line 155, in handle_error
    raise IOError('wkhtmltopdf reported an error:\n' + stderr)
OSError: wkhtmltopdf reported an error:
Exit with code 1 due to network error: HostNotFoundError
```

**Comment by giulio-perosino** [comment]
Since the error is related to `wkhtmltopdf`, I tried disabling the 'Attach Document Print' option in the email dialog, and it worked.

![Image](https://github.com/user-attachments/assets/746e373d-bc21-4753-96fd-e4fcd675a3c2)
