### ISSUE TITLE
Error: No module named 'hrms.hooks' when running docker compose in frappe_docker

### ISSUE THREAD

**Issue by NeihTzxc** [frappe/frappe_docker#1533]
---

**Description:**

I encountered the following error when trying to run the `frappe_docker` setup on Ubuntu 22.04.2 using Docker:

**Steps to Reproduce:**
1. Clone the repository:  
   ```bash
   git clone https://github.com/frappe/frappe_docker
   cd frappe_docker
   ```
2. Start the containers using:  
   ```bash
   docker compose -f pwd.yml up
   ```

**Environment Details:**
- OS: Ubuntu 22.04.2 LTS
- Docker version: 24.0.2, build cb74dfc
- Docker Compose version: v2.15.1
- frappe_docker branch: `main` (default after cloning)

**Error Output:**
The following error is observed in the logs:

```plaintext
[2024-12-23 15:02:35 +0000] [7] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/serve.py", line 19, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  ...
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 603, in throw
    msgprint(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 568, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 519, in _raise_exception
    raise exc
frappe.exceptions.DoesNotExistError: DocType Job Opening not found

```

**Full Log Trace:**  
<details>
<summary>Click to expand</summary>

```plaintext
frappe_docker-backend-1       | [2024-12-23 15:02:35 +0000] [7] [ERROR] Error handling request /
frappe_docker-backend-1       | Traceback (most recent call last):
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/serve.py", line 19, in get_response
frappe_docker-backend-1       |     endpoint, renderer_instance = path_resolver.resolve()
frappe_docker-backend-1       |                                   ^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 69, in resolve
frappe_docker-backend-1       |     if renderer_instance.can_render():
frappe_docker-backend-1       |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/document_page.py", line 17, in can_render
frappe_docker-backend-1       |     if self.search_in_doctypes_with_web_view():
frappe_docker-backend-1       |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/document_page.py", line 26, in search_in_doctypes_with_web_view
frappe_docker-backend-1       |     if document := _find_matching_document_webview(self.path):
frappe_docker-backend-1       |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/caching.py", line 158, in redis_cache_wrapper
frappe_docker-backend-1       |     val = func(*args, **kwargs)
frappe_docker-backend-1       |           ^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/document_page.py", line 90, in _find_matching_document_webview
frappe_docker-backend-1       |     meta = frappe.get_meta(doctype)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1318, in get_meta
frappe_docker-backend-1       |     return frappe.model.meta.get_meta(doctype, cached=cached)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 63, in get_meta
frappe_docker-backend-1       |     meta = Meta(doctype)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 117, in __init__
frappe_docker-backend-1       |     super().__init__("DocType", doctype)
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 126, in __init__
frappe_docker-backend-1       |     self.load_from_db()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 123, in load_from_db
frappe_docker-backend-1       |     super().load_from_db()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 172, in load_from_db
frappe_docker-backend-1       |     frappe.throw(
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 603, in throw
frappe_docker-backend-1       |     msgprint(
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 568, in msgprint
frappe_docker-backend-1       |     _raise_exception()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 519, in _raise_exception
frappe_docker-backend-1       |     raise exc
frappe_docker-backend-1       | frappe.exceptions.DoesNotExistError: DocType Job Opening not found
frappe_docker-backend-1       | 
frappe_docker-backend-1       | During handling of the above exception, another exception occurred:
frappe_docker-backend-1       | 
frappe_docker-backend-1       | Traceback (most recent call last):
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
frappe_docker-backend-1       |     return frappe.local.request_cache[func][args_key]
frappe_docker-backend-1       |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
frappe_docker-backend-1       | KeyError: -4568689492780685268
frappe_docker-backend-1       | 
frappe_docker-backend-1       | During handling of the above exception, another exception occurred:
frappe_docker-backend-1       | 
frappe_docker-backend-1       | Traceback (most recent call last):
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 123, in application
frappe_docker-backend-1       |     response = get_response()
frappe_docker-backend-1       |                ^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/serve.py", line 28, in get_response
frappe_docker-backend-1       |     response = ErrorPage(exception=e).render()
frappe_docker-backend-1       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
frappe_docker-backend-1       |     html = self.get_html()
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 531, in cache_html_decorator
frappe_docker-backend-1       |     html = func(*args, **kwargs)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
frappe_docker-backend-1       |     self.init_context()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
frappe_docker-backend-1       |     super().init_context()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
frappe_docker-backend-1       |     self.context.update(get_website_settings())
frappe_docker-backend-1       |                         ^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 263, in get_website_settings
frappe_docker-backend-1       |     context.boot = get_boot_data()
frappe_docker-backend-1       |                    ^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 169, in get_boot_data
frappe_docker-backend-1       |     apps = get_apps() or []
frappe_docker-backend-1       |            ^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
frappe_docker-backend-1       |     return func(*args, **kwargs)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/apps.py", line 23, in get_apps
frappe_docker-backend-1       |     app_details = frappe.get_hooks("add_to_apps_screen", app_name=app)
frappe_docker-backend-1       |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1596, in get_hooks
frappe_docker-backend-1       |     hooks = _dict(_load_app_hooks(app_name))
frappe_docker-backend-1       |                   ^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
frappe_docker-backend-1       |     return_val = func(*args, **kwargs)
frappe_docker-backend-1       |                  ^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1568, in _load_app_hooks
frappe_docker-backend-1       |     app_hooks = get_module(f"{app}.hooks")
frappe_docker-backend-1       |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1434, in get_module
frappe_docker-backend-1       |     return importlib.import_module(modulename)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
frappe_docker-backend-1       |     return _bootstrap._gcd_import(name[level:], package, level)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
frappe_docker-backend-1       |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
frappe_docker-backend-1       |   File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
frappe_docker-backend-1       | ModuleNotFoundError: No module named 'hrms.hooks'
frappe_docker-backend-1       | 
frappe_docker-backend-1       | During handling of the above exception, another exception occurred:
frappe_docker-backend-1       | 
frappe_docker-backend-1       | Traceback (most recent call last):
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/serve.py", line 19, in get_response
frappe_docker-backend-1       |     endpoint, renderer_instance = path_resolver.resolve()
frappe_docker-backend-1       |                                   ^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 69, in resolve
frappe_docker-backend-1       |     if renderer_instance.can_render():
frappe_docker-backend-1       |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/document_page.py", line 17, in can_render
frappe_docker-backend-1       |     if self.search_in_doctypes_with_web_view():
frappe_docker-backend-1       |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/document_page.py", line 26, in search_in_doctypes_with_web_view
frappe_docker-backend-1       |     if document := _find_matching_document_webview(self.path):
frappe_docker-backend-1       |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/caching.py", line 158, in redis_cache_wrapper
frappe_docker-backend-1       |     val = func(*args, **kwargs)
frappe_docker-backend-1       |           ^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/document_page.py", line 90, in _find_matching_document_webview
frappe_docker-backend-1       |     meta = frappe.get_meta(doctype)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1318, in get_meta
frappe_docker-backend-1       |     return frappe.model.meta.get_meta(doctype, cached=cached)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 63, in get_meta
frappe_docker-backend-1       |     meta = Meta(doctype)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 117, in __init__
frappe_docker-backend-1       |     super().__init__("DocType", doctype)
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 126, in __init__
frappe_docker-backend-1       |     self.load_from_db()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 123, in load_from_db
frappe_docker-backend-1       |     super().load_from_db()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 172, in load_from_db
frappe_docker-backend-1       |     frappe.throw(
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 603, in throw
frappe_docker-backend-1       |     msgprint(
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 568, in msgprint
frappe_docker-backend-1       |     _raise_exception()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 519, in _raise_exception
frappe_docker-backend-1       |     raise exc
frappe_docker-backend-1       | frappe.exceptions.DoesNotExistError: DocType Job Opening not found
frappe_docker-backend-1       | 
frappe_docker-backend-1       | During handling of the above exception, another exception occurred:
frappe_docker-backend-1       | 
frappe_docker-backend-1       | Traceback (most recent call last):
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
frappe_docker-backend-1       |     return frappe.local.request_cache[func][args_key]
frappe_docker-backend-1       |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
frappe_docker-backend-1       | KeyError: -4568689492780685268
frappe_docker-backend-1       | 
frappe_docker-backend-1       | During handling of the above exception, another exception occurred:
frappe_docker-backend-1       | 
frappe_docker-backend-1       | Traceback (most recent call last):
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 282, in handle
frappe_docker-backend-1       |     keepalive = self.handle_request(req, conn)
frappe_docker-backend-1       |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
frappe_docker-backend-1       |     respiter = self.wsgi(environ, resp.start_response)
frappe_docker-backend-1       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 79, in application
frappe_docker-backend-1       |     app(environ, start_response),
frappe_docker-backend-1       |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 190, in application
frappe_docker-backend-1       |     resp = f(*args[:-2] + (request,))
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 132, in application
frappe_docker-backend-1       |     response = handle_exception(e)
frappe_docker-backend-1       |                ^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 395, in handle_exception
frappe_docker-backend-1       |     response = get_response("message", http_status_code=http_status_code)
frappe_docker-backend-1       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/serve.py", line 28, in get_response
frappe_docker-backend-1       |     response = ErrorPage(exception=e).render()
frappe_docker-backend-1       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
frappe_docker-backend-1       |     html = self.get_html()
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 531, in cache_html_decorator
frappe_docker-backend-1       |     html = func(*args, **kwargs)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
frappe_docker-backend-1       |     self.init_context()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
frappe_docker-backend-1       |     super().init_context()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
frappe_docker-backend-1       |     self.context.update(get_website_settings())
frappe_docker-backend-1       |                         ^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 263, in get_website_settings
frappe_docker-backend-1       |     context.boot = get_boot_data()
frappe_docker-backend-1       |                    ^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 169, in get_boot_data
frappe_docker-backend-1       |     apps = get_apps() or []
frappe_docker-backend-1       |            ^^^^^^^^^^
frappe_docker-frontend-1      | 172.21.0.1 - - [23/Dec/2024:15:02:35 +0000] "GET / HTTP/1.1" 500 141 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0"
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
frappe_docker-backend-1       |     return func(*args, **kwargs)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/apps.py", line 23, in get_apps
frappe_docker-backend-1       |     app_details = frappe.get_hooks("add_to_apps_screen", app_name=app)
frappe_docker-backend-1       |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1596, in get_hooks
frappe_docker-backend-1       |     hooks = _dict(_load_app_hooks(app_name))
frappe_docker-backend-1       |                   ^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
frappe_docker-backend-1       |     return_val = func(*args, **kwargs)
frappe_docker-backend-1       |                  ^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1568, in _load_app_hooks
frappe_docker-backend-1       |     app_hooks = get_module(f"{app}.hooks")
frappe_docker-backend-1       |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1434, in get_module
frappe_docker-backend-1       |     return importlib.import_module(modulename)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
frappe_docker-backend-1       |     return _bootstrap._gcd_import(name[level:], package, level)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
frappe_docker-backend-1       |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
frappe_docker-backend-1       |   File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
frappe_docker-backend-1       | ModuleNotFoundError: No module named 'hrms.hooks'
```

</details>

---

**Expected Behavior:**  
The containers should start without errors, and the system should initialize as expected.

**Actual Behavior:**  
The containers failed to start due to a `ModuleNotFoundError`.

**Possible Cause:**  
The error seems related to the HRMS module being referenced in the codebase but not present in the environment. This might be due to missing dependencies or configurations.

**Additional Notes:**  
Let me know if more details or logs are needed. I can assist in debugging if required.

**Suggestions for Fix:**  
- Verify if the HRMS module is required in the current setup.
- Ensure all dependencies are included in the `docker-compose` configuration or environment.

---

**Comment by NeihTzxc** [comment]
> frappe/hrms is not required by frappe/erpnext
> 
> Everything works as expected, tests pass, works locally for me.
> 
>  pwd_works_20241224_133951.webm

Thank you, I down all containers, deleted all containers, deleted all volumes and ran again, the result was normal.
