### ISSUE TITLE
Install ERROR 1062 (23000) at line 1: Duplicate entry '%-_2d904ed711a03166' for key 'PRIMARY'

### ISSUE THREAD

**Issue by AlvaroMolano** [frappe/frappe_docker#166]
Hi all,
I have followed setup steps many times, I take care environment vars, permissions, ports... But, always get stuck in the same point.

1. create environment variables for project and sites.
1.1 Tried with version edge
1.2 Tried with version v12
2. create sites dir with right permissions
3. exec 
    ` docker-compose \
        --project-name ${PROJECT} \
        -f  ~/frappe_docker/installation/docker-compose-common.yml \
        -f  ~/frappe_docker/installation/docker-compose-erpnext.yml \
        -f  ~/frappe_docker/installation/docker-compose-networks.yml \
        --project-directory $PFOLDER up -d
    `
4. exec 
    ` docker-compose \
        --project-name ${PROJECT} \
        -f installation/docker-compose-common.yml \
        -f installation/docker-compose-erpnext.yml \
        --project-directory installation \ 
        run --publish 80:80 -d erpnext-nginx
    `
5. exec
    ` docker exec -it \
        -e "SITE_NAME=${SITE_NAME}" \
        -e "DB_ROOT_USER=${DB_ROOT_USER}" \
        -e "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" \
        -e "ADMIN_PASSWORD=${ADMIN_PASSWORD}" \
        -e "INSTALL_APPS=erpnext" \
        -e "FORCE=1" \
        $PROJECTVAR docker-entrypoint.sh new
    `
This steps takes a while, and up to this point all seems to be ok, stack is running with no errors and every container is listening.

## Then I get:

    Created user _2d904ed711a03166
    Created database _2d904ed711a03166
    Granted privileges to user _2d904ed711a03166 and database _2d904ed711a03166
    Starting database import...
    Imported from database /home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/framework_mariadb.sql

    Installing frappe...
    Updating DocTypes for frappe        : [========================================]
    Updating country info               : [========================================]

    Installing erpnext...
    Updating DocTypes for erpnext       : [========================================]
    Updating customizations for Address
    *** Scheduler is disabled ***
    ERROR 1062 (23000) at line 1: Duplicate entry '%-_2d904ed711a03166' for key 'PRIMARY'

Please advise.

And Thanks.

Alvaro

**Comment by revant** [comment]
I don't think that message will cause any problem? Is everything working as expected?

in `new.py` it creates the site first and then it additionally creates a user

```sql
`_2d904ed711a03166`@'%'
```

It doesn't check if the user already exists or not.

**Comment by AlvaroMolano** [comment]
Hi, Thanks for your quick replay. 
Well, that is certainly not a clear trace of what is happening but, it is all that CLI is giving back, plus:
The scheduler is stopped
The scheduler service is not reachable, the site is not working, then the error ERROR is the only meaningful clue I have. Nginx run container is still expecting connection from erpnext container.
I exposed erpnext and socketio containers ports 8000 and 9000, implemented an Nginx instance to proxy from host. 
From the hosts and from the container all I get is an Internal Server Error:
    - erpnext container logs:

`

    [2020-03-24 08:15:57 +0000] [19] [INFO] Listening at: http://0.0.0.0:8000 (19)[2020-03-24 08:15:57 +0000] [19] [INFO] Using worker: gthread[2020-03-24 08:15:57 +0000] [23] [INFO] Booting worker with pid: 23[2020-03-24 08:15:57 +0000] [24] [INFO] Booting worker with pid: 24[2020-03-24 08:22:08 +0000] [24] [ERROR] Error handling request /Traceback (most recent call last):  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 53, in application    init_request(request)  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 108, in init_request    frappe.init(site=site, sites_path=_sites_path)  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 150, in init    local.conf = _dict(get_site_config())  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 224, in get_site_config    sys.exit(1)SystemExit: 1
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 72, in __getattr__    return self.__storage__[self.__ident_func__()][name]KeyError: 'conf'
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 309, in _get_current_object    return getattr(self.__local, self.__name__)  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 74, in __getattr__    raise AttributeError(name)AttributeError: conf
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 280, in handle    keepalive = self.handle_request(req, conn)  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 329, in handle_request    respiter = self.wsgi(environ, resp.start_response)  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 231, in application    return ClosingIterator(app(environ, start_response), self.cleanup)  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/wrappers/base_request.py", line 237, in application    resp = f(*args[:-2] + (request,))  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 96, in application    frappe.monitor.stop(response)  File "/home/frappe/frappe-bench/apps/frappe/frappe/monitor.py", line 26, in stop    if frappe.conf.monitor and hasattr(frappe.local, "monitor"):  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__    return getattr(self._get_current_object(), name)  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 311, in _get_current_object    raise RuntimeError("no object bound to %s" % self.__name__)RuntimeError: no object bound to conf[2020-03-24 08:22:08 +0000] [24] [ERROR] Error handling request /favicon.icoTraceback (most recent call last):  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 53, in application    init_request(request)  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 108, in init_request    frappe.init(site=site, sites_path=_sites_path)  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 150, in init    local.conf = _dict(get_site_config())  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 224, in get_site_config    sys.exit(1)SystemExit: 1
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 72, in __getattr__    return self.__storage__[self.__ident_func__()][name]KeyError: 'conf'
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 309, in _get_current_object    return getattr(self.__local, self.__name__)  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 74, in __getattr__    raise AttributeError(name)AttributeError: conf
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 280, in handle    keepalive = self.handle_request(req, conn)  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 329, in handle_request    respiter = self.wsgi(environ, resp.start_response)  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 231, in application    return ClosingIterator(app(environ, start_response), self.cleanup)  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/wrappers/base_request.py", line 237, in application    resp = f(*args[:-2] + (request,))  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 96, in application    frappe.monitor.stop(response)  File "/home/frappe/frappe-bench/apps/frappe/frappe/monitor.py", line 26, in stop    if frappe.conf.monitor and hasattr(frappe.local, "monitor"):  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__    return getattr(self._get_current_object(), name)  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 311, in _get_current_object    raise RuntimeError("no object bound to %s" % self.__name__)RuntimeError: no object bound to conf


`

**Comment by revant** [comment]
The error `Duplicate entry` occurs when `FORCE=1` is used and site already exists. for fresh site creation no need of `FORCE=1`

Somehow even after the error my scheduler didn't stop. Couldn't recreate the scheduler stopping issue

**Comment by revant** [comment]
What are the sites available under installation/sites directory?

If test.localhost is there, try http://test.localhost

To try sites locally only *.localhost sites are available

**Comment by AlvaroMolano** [comment]
> The error `Duplicate entry` occurs when `FORCE=1` is used and the site already exists. for fresh site creation no need of `FORCE=1`
> 
> Somehow even after the error my scheduler didn't stop. Couldn't recreate the scheduler stopping issue

You are right, might not need  ´FORCE=1´.
I did add it after a few trials and did not remove it later.

**Comment by AlvaroMolano** [comment]
> What are the sites available under installation/sites directory?
> 
> If test.localhost is there, try http://test.localhost
> 
> To try sites locally only *.localhost sites are available

All my directories:
`
saas@saas:~/frappe_docker/installation/sites$ ls
erpirradia
saas@saas:~/frappe_docker/installation/sites/erpirradia$ ls
frappe-mariadb.cnf  sites
saas@saas:~/frappe_docker/installation/sites/erpirradia$ ls sites/
app_versions.json  apps.txt  assets  common_site_config.json  irradiaErp
saas@saas:~/frappe_docker/installation/sites/erpirradia$ ls sites/irradiaErp/
locks  private  public  site_config.json  task-logs  touched_tables.json`

Any *.localhost is going to same default nginx welcome screen. 
Visiting irradiaerp.localhost or irradiaerp.localhost does not hit nexterp, but in my case container address 172.x.x.x:8000 or 0.0.0.0:32768 would hit erpirradia_erpnext-python_1 container and it is producing the beforementioned error logs. `no object bound to conf`

Thanks for your followup.

**Comment by revant** [comment]
I think something wrong with the sites directory. It has all the sites only. No nested sites should be in there.

Does your site again has nested sites?
sites/erpirradia/sites/irradiaErp/

Something is wrong with mounts? 

Also the site name should be irradiaErp.localhost

And not just irradiaErp

localhost thing was mentioned in documentation but it can be easily missed I guess.

Why it is so? Both nginx and python serve whatever is caught in $http_host. That is, whatever url typed in browser to request website. If it's not found in sites directory nginx will 404 and python will 500.

I don't know how to solve the problem of conveying how things work.

**Comment by revant** [comment]
Reopen if necessary
