### ISSUE TITLE
erpnext-assets service keeps restarting

### ISSUE THREAD

**Issue by sindile** [frappe/frappe_docker#196]
Any pointers what I could be missing?
The erpnext-assets service keeps restarting with the following log output:
Waiting for frappe-python to be available on 0.0.0.0 port 8000

I am also seeing the following output from the mariadb container (with Access denied for user '_d285a3619a10383d'@'10.42.39.237' (using password: YES):

```
2020-04-17 16:36:52 0 [Note] mysqld (mysqld 10.3.22-MariaDB-1:10.3.22+maria~bionic) starting as process 1 ...
2020-04-17 16:36:52 0 [Note] InnoDB: Using Linux native AIO
2020-04-17 16:36:52 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2020-04-17 16:36:52 0 [Note] InnoDB: Uses event mutexes
2020-04-17 16:36:52 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2020-04-17 16:36:52 0 [Note] InnoDB: Number of pools: 1
2020-04-17 16:36:52 0 [Note] InnoDB: Using SSE2 crc32 instructions
2020-04-17 16:36:52 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
2020-04-17 16:36:52 0 [Note] InnoDB: Completed initialization of buffer pool
2020-04-17 16:36:52 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2020-04-17 16:36:52 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2020-04-17 16:36:52 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2020-04-17 16:36:52 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2020-04-17 16:36:52 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2020-04-17 16:36:52 0 [Note] InnoDB: Waiting for purge to start
2020-04-17 16:36:52 0 [Note] InnoDB: 10.3.22 started; log sequence number 1625457; transaction id 21
2020-04-17 16:36:52 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2020-04-17 16:36:52 0 [Note] Plugin 'FEEDBACK' is disabled.
2020-04-17 16:36:52 0 [Note] InnoDB: Buffer pool(s) load completed at 200417 16:36:52
2020-04-17 16:36:52 0 [Note] Server socket created on IP: '::'.
2020-04-17 16:36:52 0 [Warning] 'proxies_priv' entry '@% root@8f40f71e9b7e' ignored in --skip-name-resolve mode.
2020-04-17 16:36:52 0 [Note] Reading of all Master_info entries succeeded
2020-04-17 16:36:52 0 [Note] Added new Master_info '' to hash table
2020-04-17 16:36:52 0 [Note] mysqld: ready for connections.
Version: '10.3.22-MariaDB-1:10.3.22+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2020-04-17 16:37:29 13 [Warning] Access denied for user 'frappe'@'10.42.34.6' (using password: NO)
2020-04-17 16:37:29 14 [Warning] 'proxies_priv' entry '@% root@8f40f71e9b7e' ignored in --skip-name-resolve mode.
2020-04-17 16:37:54 17 [Warning] Access denied for user '_d285a3619a10383d'@'10.42.39.237' (using password: YES)
2020-04-17 16:38:54 18 [Warning] Access denied for user '_d285a3619a10383d'@'10.42.39.237' (using password: YES)
2020-04-17 16:39:54 19 [Warning] Access denied for user '_d285a3619a10383d'@'10.42.39.237' (using password: YES)
2020-04-17 16:40:54 20 [Warning] Access denied for user '_d285a3619a10383d'@'10.42.39.237' (using password: YES)
2020-04-17 16:40:59 21 [Warning] 'proxies_priv' entry '@% root@8f40f71e9b7e' ignored in --skip-name-resolve mode.
2020-04-17 16:40:59 23 [Warning] 'proxies_priv' entry '@% root@8f40f71e9b7e' ignored in --skip-name-resolve mode.

```

I am using the following docker-compose file via Rancher

```yaml
version: '2'

services:
  redis-cache:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-cache-vol:/data

  redis-queue:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-queue-vol:/data

  redis-socketio:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-socketio-vol:/data

  mariadb:
    image: mariadb:10.3
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - /home/lptp/gitrepos/erpnext-frappe-docker/installation/frappe-mariadb.cnf:/etc/mysql/conf.d/frappe.cnf
      - mariadb-vol:/var/lib/mysql

  erpnext-assets:
    image: frappe/erpnext-nginx:v12
    restart: on-failure
    environment:
      - ERPNEXT_PY=erpnext-python
      - ERPNEXT_PY_PORT=8000
      - FRAPPE_SOCKETIO=frappe-socketio
      - FRAPPE_SOCKETIO_PORT=9000
      - LETSENCRYPT_HOST=erpnext.localhost
      - VIRTUAL_HOST=erpnext.localhost
      - LETSENCRYPT_EMAIL=support@erpnext.localhost
    depends_on:
      - erpnext-python
      - frappe-socketio
      - erpnext-worker-default
      - erpnext-worker-long
      - erpnext-worker-short
    links:
      - erpnext-python
      - frappe-socketio
      - erpnext-worker-default
      - erpnext-worker-long
      - erpnext-worker-short
    volumes:
      - /home/lptp/gitrepos/erpnext-frappe-docker/installation/sites:/var/www/html/sites:rw
#      - sites-vol:/var/www/html/sites:rw
      - assets-vol:/assets:rw
    ports:
      - "8090:80"

  erpnext-python:
    image: frappe/erpnext-worker:v12
    restart: on-failure
    environment:
      - MARIADB_HOST=mariadb
      - REDIS_CACHE=redis-cache:6379
      - REDIS_QUEUE=redis-queue:6379
      - REDIS_SOCKETIO=redis-socketio:6379
      - SOCKETIO_PORT=9000
      - AUTO_MIGRATE=1
#      - SITE_NAME=erpnext.localhost
#      - DB_ROOT_USER=root
#      - MYSQL_ROOT_PASSWORD=admin
#      - ADMIN_PASSWORD=admin
#      - INSTALL_APPS=erpnext
    volumes:
      - /home/lptp/gitrepos/erpnext-frappe-docker/installation/sites:/home/frappe/frappe-bench/sites:rw
#      - sites-vol:/var/www/html/sites:rw
      - assets-vol:/home/frappe/frappe-bench/sites/assets:rw

  frappe-socketio:
    image: frappe/frappe-socketio:v12
    restart: on-failure
    depends_on:
      - redis-socketio
    links:
      - redis-socketio
    volumes:
      - /home/lptp/gitrepos/erpnext-frappe-docker/installation/sites:/home/frappe/frappe-bench/sites:rw
#      - sites-vol:/var/www/html/sites:rw

  erpnext-worker-default:
    image: frappe/erpnext-worker:v12
    restart: on-failure
    command: worker
    depends_on:
      - redis-queue
      - redis-cache
    links:
      - redis-queue
      - redis-cache
    volumes:
      - /home/lptp/gitrepos/erpnext-frappe-docker/installation/sites:/home/frappe/frappe-bench/sites:rw
#      - sites-vol:/var/www/html/sites:rw

  erpnext-worker-short:
    image: frappe/erpnext-worker:v12
    restart: on-failure
    command: worker
    environment:
      - WORKER_TYPE=short
    depends_on:
      - redis-queue
      - redis-cache
    links:
      - redis-queue
      - redis-cache
    volumes:
      - /home/lptp/gitrepos/erpnext-frappe-docker/installation/sites:/home/frappe/frappe-bench/sites:rw
#      - sites-vol:/var/www/html/sites:rw

  erpnext-worker-long:
    image: frappe/erpnext-worker:v12
    restart: on-failure
    command: worker
    environment:
      - WORKER_TYPE=long
    depends_on:
      - redis-queue
      - redis-cache
    links:
      - redis-queue
      - redis-cache
    volumes:
      - /home/lptp/gitrepos/erpnext-frappe-docker/installation/sites:/home/frappe/frappe-bench/sites:rw
#      - sites-vol:/var/www/html/sites:rw

  erpnext-schedule:
    image: frappe/erpnext-worker:v12
    restart: on-failure
    command: schedule
    depends_on:
      - redis-queue
      - redis-cache
    links:
      - redis-queue
      - redis-cache
    volumes:
      - /home/lptp/gitrepos/erpnext-frappe-docker/installation/sites:/home/frappe/frappe-bench/sites:rw
#      - sites-vol:/var/www/html/sites:rw

volumes:
#  sites-vol:
  mariadb-vol:
  assets-vol:
  redis-cache-vol:
  redis-queue-vol:
  redis-socketio-vol:

# networks:
#   default:
#     external:
#       name: webproxy

```

My .env

```
VERSION=v12
MARIADB_HOST=mariadb
MYSQL_ROOT_PASSWORD=admin
SITES=erpnext.localhost
LETSENCRYPT_EMAIL=support@erpnext.localhost
```
After deploying the stack I did the following:

```sh
docker exec -it -e "SITE_NAME=erpnext.localhost" -e "DB_ROOT_USER=root" -e "MYSQL_ROOT_PASSWORD=admin" -e "ADMIN_PASSWORD=admin" -e "INSTALL_APPS=erpnext" -e "FORCE=1" r-erpnext-erpnext-python-1-ff71ad63 docker-entrypoint.sh new

```
With the following output

```
Created user _d285a3619a10383d
Created database _d285a3619a10383d
Granted privileges to user _d285a3619a10383d and database _d285a3619a10383d
Starting database import...
Imported from database /home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/framework_mariadb.sql

Installing frappe...
Updating DocTypes for frappe        : [========================================]
Updating country info               : [========================================]

Installing erpnext...
Updating DocTypes for erpnext       : [========================================]
Updating customizations for Address
*** Scheduler is disabled ***

```

**Comment by ddavidebor** [comment]
I see permissions errors, try following these instructions
https://github.com/frappe/frappe_docker#failed-migration-after-image-upgrade

**Comment by revant** [comment]
is the site available at http://erpnext.localhost:8090

Try to access it from browser

**Comment by revant** [comment]
There's no ERPNEXT_PY and ERPNEXT_PY_PORT

There's FRAPPE_*

https://github.com/frappe/frappe_docker/blob/develop/installation/docker-compose-erpnext.yml#L8

**Comment by sindile** [comment]
I have made some headway with the suggestions from @revant but getting "Internal Server Error"
**docker container logs r-erpnext-erpnext-python-1-b7aae8ec**
Attempt 1 to connect to mariadb:3306
Attempt 2 to connect to mariadb:3306
Attempt 3 to connect to mariadb:3306
Attempt 4 to connect to mariadb:3306
Attempt 5 to connect to mariadb:3306
Attempt 1 to connect to redis-queue:6379
Attempt 1 to connect to redis-cache:6379
Attempt 1 to connect to redis-socketio:6379
Connections OK
[2020-04-18 13:17:04 +0000] [26] [INFO] Starting gunicorn 19.10.0
[2020-04-18 13:17:04 +0000] [26] [INFO] Listening at: http://0.0.0.0:8000 (26)
[2020-04-18 13:17:04 +0000] [26] [INFO] Using worker: gthread
[2020-04-18 13:17:04 +0000] [30] [INFO] Booting worker with pid: 30
[2020-04-18 13:17:04 +0000] [31] [INFO] Booting worker with pid: 31
[2020-04-18 13:23:44 +0000] [31] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 53, in application
    init_request(request)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 108, in init_request
    frappe.init(site=site, sites_path=_sites_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 150, in init
    local.conf = _dict(get_site_config())
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 224, in get_site_config
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 72, in __getattr__
    return self.__storage__[self.__ident_func__()][name]
KeyError: 'conf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 309, in _get_current_object
    return getattr(self.__local, self.__name__)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 74, in __getattr__
    raise AttributeError(name)
AttributeError: conf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 280, in handle
    keepalive = self.handle_request(req, conn)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 329, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 231, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/wrappers/base_request.py", line 237, in application
    resp = f(*args[:-2] + (request,))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 96, in application
    frappe.monitor.stop(response)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/monitor.py", line 26, in stop
    if frappe.conf.monitor and hasattr(frappe.local, "monitor"):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 311, in _get_current_object
    raise RuntimeError("no object bound to %s" % self.__name__)
RuntimeError: no object bound to conf
[2020-04-18 13:24:03 +0000] [30] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 53, in application
    init_request(request)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 108, in init_request
    frappe.init(site=site, sites_path=_sites_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 150, in init
    local.conf = _dict(get_site_config())
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 224, in get_site_config
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 72, in __getattr__
    return self.__storage__[self.__ident_func__()][name]
KeyError: 'conf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 309, in _get_current_object
    return getattr(self.__local, self.__name__)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 74, in __getattr__
    raise AttributeError(name)
AttributeError: conf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 280, in handle
    keepalive = self.handle_request(req, conn)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 329, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 231, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/wrappers/base_request.py", line 237, in application
    resp = f(*args[:-2] + (request,))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 96, in application
    frappe.monitor.stop(response)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/monitor.py", line 26, in stop
    if frappe.conf.monitor and hasattr(frappe.local, "monitor"):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 311, in _get_current_object
    raise RuntimeError("no object bound to %s" % self.__name__)
RuntimeError: no object bound to conf
[2020-04-18 13:24:04 +0000] [31] [ERROR] Error handling request /favicon.ico
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 53, in application
    init_request(request)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 108, in init_request
    frappe.init(site=site, sites_path=_sites_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 150, in init
    local.conf = _dict(get_site_config())
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 224, in get_site_config
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 72, in __getattr__
    return self.__storage__[self.__ident_func__()][name]
KeyError: 'conf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 309, in _get_current_object
    return getattr(self.__local, self.__name__)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 74, in __getattr__
    raise AttributeError(name)
AttributeError: conf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 280, in handle
    keepalive = self.handle_request(req, conn)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 329, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 231, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/wrappers/base_request.py", line 237, in application
    resp = f(*args[:-2] + (request,))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 96, in application
    frappe.monitor.stop(response)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/monitor.py", line 26, in stop
    if frappe.conf.monitor and hasattr(frappe.local, "monitor"):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 311, in _get_current_object
    raise RuntimeError("no object bound to %s" % self.__name__)
RuntimeError: no object bound to conf


**docker container logs r-erpnext-mariadb-1-06c5046b**
2020-04-18 13:16:54+00:00 [Note] [Entrypoint]: Database files initialized
2020-04-18 13:16:54+00:00 [Note] [Entrypoint]: Starting temporary server
2020-04-18 13:16:54+00:00 [Note] [Entrypoint]: Waiting for server startup
2020-04-18 13:16:54 0 [Note] mysqld (mysqld 10.3.22-MariaDB-1:10.3.22+maria~bionic) starting as process 127 ...
2020-04-18 13:16:54 0 [Note] InnoDB: Using Linux native AIO
2020-04-18 13:16:54 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2020-04-18 13:16:54 0 [Note] InnoDB: Uses event mutexes
2020-04-18 13:16:54 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2020-04-18 13:16:54 0 [Note] InnoDB: Number of pools: 1
2020-04-18 13:16:54 0 [Note] InnoDB: Using SSE2 crc32 instructions
2020-04-18 13:16:54 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
2020-04-18 13:16:54 0 [Note] InnoDB: Completed initialization of buffer pool
2020-04-18 13:16:54 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2020-04-18 13:16:55 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2020-04-18 13:16:55 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2020-04-18 13:16:55 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2020-04-18 13:16:55 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2020-04-18 13:16:55 0 [Note] InnoDB: Waiting for purge to start
2020-04-18 13:16:55 0 [Note] InnoDB: 10.3.22 started; log sequence number 1625448; transaction id 21
2020-04-18 13:16:55 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2020-04-18 13:16:55 0 [Note] Plugin 'FEEDBACK' is disabled.
2020-04-18 13:16:55 0 [Note] InnoDB: Buffer pool(s) load completed at 200418 13:16:55
2020-04-18 13:16:55 0 [Warning] 'user' entry 'root@9bb2061b244e' ignored in --skip-name-resolve mode.
2020-04-18 13:16:55 0 [Warning] 'user' entry '@9bb2061b244e' ignored in --skip-name-resolve mode.
2020-04-18 13:16:55 0 [Warning] 'proxies_priv' entry '@% root@9bb2061b244e' ignored in --skip-name-resolve mode.
2020-04-18 13:16:55 0 [Note] Reading of all Master_info entries succeeded
2020-04-18 13:16:55 0 [Note] Added new Master_info '' to hash table
2020-04-18 13:16:55 0 [Note] mysqld: ready for connections.
Version: '10.3.22-MariaDB-1:10.3.22+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
2020-04-18 13:16:55+00:00 [Note] [Entrypoint]: Temporary server started.
Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
2020-04-18 13:16:57 10 [Warning] 'proxies_priv' entry '@% root@9bb2061b244e' ignored in --skip-name-resolve mode.

2020-04-18 13:16:57+00:00 [Note] [Entrypoint]: Stopping temporary server
2020-04-18 13:16:58 0 [Note] mysqld (initiated by: root[root] @ localhost []): Normal shutdown
2020-04-18 13:16:58 0 [Note] Event Scheduler: Purging the queue. 0 events
2020-04-18 13:16:58 0 [Note] InnoDB: FTS optimize thread exiting.
2020-04-18 13:16:58 0 [Note] InnoDB: Starting shutdown...
2020-04-18 13:16:58 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2020-04-18 13:16:58 0 [Note] InnoDB: Buffer pool(s) dump completed at 200418 13:16:58
2020-04-18 13:17:00 0 [Note] InnoDB: Shutdown completed; log sequence number 1625457; transaction id 24
2020-04-18 13:17:00 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2020-04-18 13:17:00 0 [Note] mysqld: Shutdown complete

2020-04-18 13:17:01+00:00 [Note] [Entrypoint]: Temporary server stopped

2020-04-18 13:17:01+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.

2020-04-18 13:17:01 0 [Note] mysqld (mysqld 10.3.22-MariaDB-1:10.3.22+maria~bionic) starting as process 1 ...
2020-04-18 13:17:01 0 [Note] InnoDB: Using Linux native AIO
2020-04-18 13:17:01 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2020-04-18 13:17:01 0 [Note] InnoDB: Uses event mutexes
2020-04-18 13:17:01 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2020-04-18 13:17:01 0 [Note] InnoDB: Number of pools: 1
2020-04-18 13:17:01 0 [Note] InnoDB: Using SSE2 crc32 instructions
2020-04-18 13:17:01 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
2020-04-18 13:17:01 0 [Note] InnoDB: Completed initialization of buffer pool
2020-04-18 13:17:01 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2020-04-18 13:17:01 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2020-04-18 13:17:01 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2020-04-18 13:17:01 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2020-04-18 13:17:01 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2020-04-18 13:17:01 0 [Note] InnoDB: Waiting for purge to start
2020-04-18 13:17:01 0 [Note] InnoDB: 10.3.22 started; log sequence number 1625457; transaction id 21
2020-04-18 13:17:01 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2020-04-18 13:17:01 0 [Note] Plugin 'FEEDBACK' is disabled.
2020-04-18 13:17:01 0 [Note] InnoDB: Buffer pool(s) load completed at 200418 13:17:01
2020-04-18 13:17:01 0 [Note] Server socket created on IP: '::'.
2020-04-18 13:17:01 0 [Warning] 'proxies_priv' entry '@% root@9bb2061b244e' ignored in --skip-name-resolve mode.
2020-04-18 13:17:01 0 [Note] Reading of all Master_info entries succeeded
2020-04-18 13:17:01 0 [Note] Added new Master_info '' to hash table
2020-04-18 13:17:01 0 [Note] mysqld: ready for connections.
Version: '10.3.22-MariaDB-1:10.3.22+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2020-04-18 13:18:26 13 [Warning] Access denied for user 'frappe'@'10.42.145.182' (using password: NO)
2020-04-18 13:18:26 14 [Warning] 'proxies_priv' entry '@% root@9bb2061b244e' ignored in --skip-name-resolve mode.
2020-04-18 13:19:05 17 [Warning] Access denied for user '_d285a3619a10383d'@'10.42.42.66' (using password: YES)
2020-04-18 13:20:05 18 [Warning] Access denied for user '_d285a3619a10383d'@'10.42.42.66' (using password: YES)
2020-04-18 13:21:05 19 [Warning] Access denied for user '_d285a3619a10383d'@'10.42.42.66' (using password: YES)
2020-04-18 13:21:39 20 [Warning] 'proxies_priv' entry '@% root@9bb2061b244e' ignored in --skip-name-resolve mode.
2020-04-18 13:21:39 22 [Warning] 'proxies_priv' entry '@% root@9bb2061b244e' ignored in --skip-name-resolve mode.

**Comment by revant** [comment]
Only list of sites under `sites` directory are available, i.e. http://erpnext.localhost:8090.

Also note that when trying locally site name should end with `.localhost`

https://github.com/frappe/frappe_docker/issues/182#issuecomment-609899924

**Comment by sindile** [comment]
Thanks @revant it is working now.
