### ISSUE TITLE
Error: `ValidationError Item Group is an invalid Data field` on `new` command.

### ISSUE THREAD

**Issue by NickBusey** [frappe/frappe_docker#203]
## Description of the issue

While running the `new` site command, I get this back `frappe.exceptions.ValidationError: <b>Item Group</b> is an invalid Data field.<br><br>Only Options allowed for Data field are:<br><ul><li>Email</li><li>Phone</ul>`

## Context information (for bug reports)

Docker-compose file:

```
---
version: '3'

# This networks section required for the pacakge to be visible to Traefik.
# DO NOT Remove
networks:
  traefik_network:
    external:
      name: homelabos_traefik

services:
  redis-cache:
    networks:
      - traefik_network
    image: redis:latest
    restart: on-failure
    volumes:
      - "/var/homelabos/erpnext/redis-cache-vol:/data"

  redis-queue:
    networks:
      - traefik_network
    image: redis:latest
    restart: on-failure
    volumes:
      - "/var/homelabos/erpnext/redis-queue-vol:/data"

  redis-socketio:
    networks:
      - traefik_network
    image: redis:latest
    restart: on-failure
    volumes:
      - "/var/homelabos/erpnext/redis-socketi-vol:/data"

  mariadb:
    networks:
      - traefik_network
    image: mariadb:10.3
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - "/var/homelabos/erpnext/frappe-mariadb.cnf:/etc/mysql/conf.d/frappe.cnf"
      - "/var/homelabos/erpnext/mariadb-vol:/var/lib/mysql"

  erpnext-nginx:
    image: frappe/erpnext-nginx:${VERSION}
    restart: on-failure
    environment:
      - FRAPPE_PY=erpnext-python
      - FRAPPE_PY_PORT=8000
      - FRAPPE_SOCKETIO=frappe-socketio
      - SOCKETIO_PORT=9000
      - LETSENCRYPT_HOST=${SITES}
      - VIRTUAL_HOST=${SITES}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      - erpnext-python
      - frappe-socketio
      - frappe-worker-default
      - frappe-worker-long
      - frappe-worker-short
    links:
      - erpnext-python
      - frappe-socketio
      - frappe-worker-default
      - frappe-worker-long
      - frappe-worker-short
    volumes:
      - "/var/homelabos/erpnext/sites:/var/www/html/sites"
      - "/var/homelabos/erpnext/assets-vol:/assets"
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=homelabos_traefik"
      - "traefik.http.services.erpnext.loadbalancer.server.scheme=http"
      - "traefik.http.services.erpnext.loadbalancer.server.port=80"
      - "traefik.http.routers.erpnext-http.rule=Host(`erpnext.hlos.grownetics.co`)"
      - "traefik.http.routers.erpnext-http.entrypoints=http"
      - "traefik.http.routers.erpnext-http.middlewares=customFrameHomelab@file"
      - "traefik.http.routers.erpnext.rule=Host(`erpnext.hlos.grownetics.co`)"
      - "traefik.http.routers.erpnext.entrypoints=https"
      - "traefik.http.routers.erpnext.middlewares=customFrameHomelab@file"
      - "traefik.http.routers.erpnext.tls=true"
      - "traefik.http.routers.erpnext.tls.certresolver=http"
      - "traefik.http.routers.erpnext-tor-http.rule=Host(`erpnext.tq7xqfh4qaecb4za.onion`)"
      - "traefik.http.routers.erpnext-tor-http.entrypoints=http"
      - "traefik.http.routers.erpnext-tor-http.middlewares=customFrameHomelab-tor@file"

  erpnext-python:
    image: frappe/erpnext-worker:${VERSION}
    restart: on-failure
    networks:
      - traefik_network
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - REDIS_CACHE=redis-cache:6379
      - REDIS_QUEUE=redis-queue:6379
      - REDIS_SOCKETIO=redis-socketio:6379
      - SOCKETIO_PORT=9000
      - AUTO_MIGRATE=1
    volumes:
      - "/var/homelabos/erpnext/sites:/home/frappe/frappe-bench/sites"
      - "/var/homelabos/erpnext/assets-vol:/home/frappe/frappe-bench/sites/assets"

  frappe-socketio:
    networks:
      - traefik_network
    image: frappe/frappe-socketio:${VERSION}
    restart: on-failure
    depends_on:
      - redis-socketio
    links:
      - redis-socketio
    volumes:
      - "/var/homelabos/erpnext/sites:/home/frappe/frappe-bench/sites"


  frappe-worker-default:
    networks:
      - traefik_network
    image: frappe/erpnext-worker:${VERSION}
    restart: on-failure
    command: worker
    depends_on:
      - redis-queue
      - redis-cache
    links:
      - redis-queue
      - redis-cache
    volumes:
      - "/var/homelabos/erpnext/sites:/home/frappe/frappe-bench/sites"

  frappe-worker-short:
    image: frappe/erpnext-worker:${VERSION}
    networks:
      - traefik_network
    restart: on-failure
    command: worker
    environment:
      - WORKER_TYPE=short
    depends_on:
      - redis-queue
      - redis-cache
    links:
      - redis-queue
      - redis-cache
    volumes:
      - "/var/homelabos/erpnext/sites:/home/frappe/frappe-bench/sites"

  frappe-worker-long:
    image: frappe/erpnext-worker:${VERSION}
    networks:
      - traefik_network
    restart: on-failure
    command: worker
    environment:
      - WORKER_TYPE=long
    depends_on:
      - redis-queue
      - redis-cache
    links:
      - redis-queue
      - redis-cache
    volumes:
      - "/var/homelabos/erpnext/sites:/home/frappe/frappe-bench/sites"

  frappe-schedule:
    image: frappe/erpnext-worker:${VERSION}
    networks:
      - traefik_network
    restart: on-failure
    command: schedule
    depends_on:
      - redis-queue
      - redis-cache
    links:
      - redis-queue
      - redis-cache
    volumes:
      - "/var/homelabos/erpnext/sites:/home/frappe/frappe-bench/sites"
```

## Steps to reproduce the issue

Try and spin up the compose file above.

### Observed result

Page only shows Internal Server Errors.

### Expected result

Working application?

### Stacktrace / full error message if available

```
root@erpnext:/var/homelabos/erpnext# docker exec -it     -e "SITE_NAME=SITE"     -e "ADMIN_PASSWORD=PASS"     -e "INSTALL_APPS=erpnext"     -e "FORCE=1" erpnext_erpnext-python_1 docker-entrypoint.sh new
Created user _b3293690bf119a92
Created database _b3293690bf119a92
Granted privileges to user _b3293690bf119a92 and database _b3293690bf119a92
Starting database import...
Imported from database /home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/framework_mariadb.sql

Installing frappe...
Updating DocTypes for frappe        : [========================================]
Updating country info               : [========================================]

Installing erpnext...
Updating DocTypes for erpnext       : [========================================]
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/commands/new.py", line 81, in <module>
    main()
  File "/home/frappe/frappe-bench/commands/new.py", line 47, in main
    reinstall=False,
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 89, in _new_site
    _install_app(app, verbose=verbose, set_as_patched=not source_sql)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 85, in install_app
    add_to_installed_apps(name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 110, in add_to_installed_apps
    post_install(rebuild_website)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 171, in post_install
    init_singles()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 192, in init_singles
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 277, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 300, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 264, in insert
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 938, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 805, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1091, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1074, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 799, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_settings/stock_settings.py", line 67, in on_update
    self.toggle_warehouse_field_for_inter_warehouse_transfer()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_settings/stock_settings.py", line 72, in toggle_warehouse_field_for_inter_warehouse_transfer
    make_property_setter("Purchase Invoice Item", "from_warehouse", "hidden", 1 - cint(self.allow_from_pr), "Check")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/custom/doctype/property_setter/property_setter.py", line 90, in make_property_setter
    property_setter.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 264, in insert
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 938, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 805, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1091, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1074, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 799, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/custom/doctype/property_setter/property_setter.py", line 74, in on_update
    validate_fields_for_doctype(self.doc_type)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 644, in validate_fields_for_doctype
    validate_fields(frappe.get_meta(doctype, cached=False))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 935, in validate_fields
    validate_data_field_type(d)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 902, in validate_data_field_type
    frappe.msgprint(text_str + df_options_str, title="Invalid Data Field", raise_exception=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 364, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 317, in _raise_exception
    raise ValidationError(msg)
frappe.exceptions.ValidationError: <b>Item Group</b> is an invalid Data field.<br><br>Only Options allowed for Data field are:<br><ul><li>Email</li><li>Phone</ul>
Backed up files /home/frappe/frappe-bench/sites/Grownetics/private/backups/20200422_002328-Grownetics-files.tar
Backed up files /home/frappe/frappe-bench/sites/Grownetics/private/backups/20200422_002328-Grownetics-private-files.tar
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 104, in _new_site_cleanup
    _drop_site(site, mariadb_root_username, mariadb_root_password, force=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 425, in _drop_site
    os.mkdir(archived_sites_path)
PermissionError: [Errno 13] Permission denied: '/home/frappe/frappe-bench/apps/frappe/frappe/../../../archived_sites'
```

**Comment by revant** [comment]
```yaml
    volumes:
      - "/var/homelabos/erpnext/sites:/home/frappe/frappe-bench/sites"
```

If you are using bind mounts make sure the user with uid and gid 1000 has permission to directory `/var/homelabos/erpnext/sites`. All the commands in container are executed by user `frappe` with gid 1000 and uid 1000

**Comment by revant** [comment]
Something broke in ERPNext. Not a docker issue exactly

```
❯ bench new-site testdelete.localhost --install-app erpnext
MySQL root password: 

Installing frappe...
Updating DocTypes for frappe        : [========================================]
Updating country info               : [========================================]
Set Administrator password: 
Re-enter Administrator password: 

Installing erpnext...
Updating DocTypes for erpnext       : [========================================]
Traceback (most recent call last):
  File "/home/revant/.pyenv/versions/pypy3.6-7.3.0/lib-python/3/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/revant/.pyenv/versions/pypy3.6-7.3.0/lib-python/3/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/revant/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/revant/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/revant/frappe-bench/env/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/revant/frappe-bench/env/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/revant/frappe-bench/env/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/revant/frappe-bench/env/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/revant/frappe-bench/env/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/revant/frappe-bench/env/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/commands/site.py", line 46, in new_site
    no_mariadb_socket=no_mariadb_socket, db_password=db_password, db_type=db_type, db_host=db_host, db_port=db_port)
  File "/home/revant/frappe-bench/apps/frappe/frappe/commands/site.py", line 89, in _new_site
    _install_app(app, verbose=verbose, set_as_patched=not source_sql)
  File "/home/revant/frappe-bench/apps/frappe/frappe/installer.py", line 85, in install_app
    add_to_installed_apps(name)
  File "/home/revant/frappe-bench/apps/frappe/frappe/installer.py", line 110, in add_to_installed_apps
    post_install(rebuild_website)
  File "/home/revant/frappe-bench/apps/frappe/frappe/installer.py", line 171, in post_install
    init_singles()
  File "/home/revant/frappe-bench/apps/frappe/frappe/installer.py", line 192, in init_singles
    doc.save()
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 277, in save
    return self._save(*args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 300, in _save
    self.insert()
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 264, in insert
    self.run_post_save_methods()
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 938, in run_post_save_methods
    self.run_method("on_update")
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 805, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 1091, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 1074, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 799, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/revant/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_settings/stock_settings.py", line 67, in on_update
    self.toggle_warehouse_field_for_inter_warehouse_transfer()
  File "/home/revant/frappe-bench/apps/erpnext/erpnext/stock/doctype/stock_settings/stock_settings.py", line 72, in toggle_warehouse_field_for_inter_warehouse_transfer
    make_property_setter("Purchase Invoice Item", "from_warehouse", "hidden", 1 - cint(self.allow_from_pr), "Check")
  File "/home/revant/frappe-bench/apps/frappe/frappe/custom/doctype/property_setter/property_setter.py", line 90, in make_property_setter
    property_setter.insert()
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 264, in insert
    self.run_post_save_methods()
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 938, in run_post_save_methods
    self.run_method("on_update")
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 805, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 1091, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 1074, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 799, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/custom/doctype/property_setter/property_setter.py", line 74, in on_update
    validate_fields_for_doctype(self.doc_type)
  File "/home/revant/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 644, in validate_fields_for_doctype
    validate_fields(frappe.get_meta(doctype, cached=False))
  File "/home/revant/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 935, in validate_fields
    validate_data_field_type(d)
  File "/home/revant/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 902, in validate_data_field_type
    frappe.msgprint(text_str + df_options_str, title="Invalid Data Field", raise_exception=True)
  File "/home/revant/frappe-bench/apps/frappe/frappe/__init__.py", line 364, in msgprint
    _raise_exception()
  File "/home/revant/frappe-bench/apps/frappe/frappe/__init__.py", line 317, in _raise_exception
    raise ValidationError(msg)
frappe.exceptions.ValidationError: <b>Item Group</b> is an invalid Data field.<br><br>Only Options allowed for Data field are:<br><ul><li>Email</li><li>Phone</ul>

```

**Comment by revant** [comment]
Closing from here. Follow up on ERPNext github repo
