### ISSUE TITLE
RuntimeError: no object bound to conf

### ISSUE THREAD

**Issue by NickBusey** [frappe/frappe_docker#206]
## Description of the issue

Got the stack spun up with docker-compose, ran `docker exec -it -e "SITE_NAME=SITE" -e "SITES=erpnext.grownetics413.local" -e "ADMIN_PASSWORD=PASS" -e "INSTALL_APPS=erpnext" erpnext_erpnext-python_1 docker-entrypoint.sh new` successfully.

Trying to hit the URL above (served by Traefik), I get `Internal Server Error`

Docker logs of erpnext-python show: `RuntimeError: no object bound to conf`

I can't find much useful about this in the frappe_docker docs. I found some things in the erpnext github issues, but they seem to work differently than the docker deploy does.

## Context information (for bug reports)

docker-compose.yml file:

```
---
version: '3'

# This networks section required for the pacakge to be visible to Traefik.
# DO NOT Remove
networks:
  traefik_network:
    external:
      name: homelabos_traefik

services:
  redis-cache:
    networks:
      - traefik_network
    image: redis:latest
    restart: on-failure
    volumes:
      - "/var/homelabos/erpnext/redis-cache-vol:/data"

  redis-queue:
    networks:
      - traefik_network
    image: redis:latest
    restart: on-failure
    volumes:
      - "/var/homelabos/erpnext/redis-queue-vol:/data"

  redis-socketio:
    networks:
      - traefik_network
    image: redis:latest
    restart: on-failure
    volumes:
      - "/var/homelabos/erpnext/redis-socketi-vol:/data"

  mariadb:
    networks:
      - traefik_network
    image: mariadb:10.3
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - "/var/homelabos/erpnext/frappe-mariadb.cnf:/etc/mysql/conf.d/frappe.cnf"
      - "/var/homelabos/erpnext/mariadb-vol:/var/lib/mysql"

  erpnext-nginx:
    image: frappe/erpnext-nginx:${VERSION}
    restart: on-failure
    environment:
      - FRAPPE_PY=erpnext-python
      - FRAPPE_PY_PORT=8000
      - FRAPPE_SOCKETIO=frappe-socketio
      - SOCKETIO_PORT=9000
      - LETSENCRYPT_HOST=${SITES}
      - VIRTUAL_HOST=${SITES}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      - erpnext-python
      - frappe-socketio
      - frappe-worker-default
      - frappe-worker-long
      - frappe-worker-short
    links:
      - erpnext-python
      - frappe-socketio
      - frappe-worker-default
      - frappe-worker-long
      - frappe-worker-short
    volumes:
      - "/var/homelabos/erpnext/sites:/var/www/html/sites"
      - "/var/homelabos/erpnext/assets-vol:/assets"
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=homelabos_traefik"
      - "traefik.http.services.erpnext.loadbalancer.server.scheme=http"
      - "traefik.http.services.erpnext.loadbalancer.server.port=80"
      - "traefik.http.routers.erpnext-http.rule=Host(`erpnext.grownetics413.local`)"
      - "traefik.http.routers.erpnext-http.entrypoints=http"
      - "traefik.http.routers.erpnext-http.middlewares=customFrameHomelab@file"
      - "traefik.http.routers.erpnext.rule=Host(`erpnext.grownetics413.local`)"
      - "traefik.http.routers.erpnext.entrypoints=https"
      - "traefik.http.routers.erpnext.middlewares=customFrameHomelab@file"
      - "traefik.http.routers.erpnext.tls=true"
      - "traefik.http.routers.erpnext.tls.certresolver=http"

  erpnext-python:
    image: frappe/erpnext-worker:${VERSION}
    restart: on-failure
    networks:
      - traefik_network
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - REDIS_CACHE=redis-cache:6379
      - REDIS_QUEUE=redis-queue:6379
      - REDIS_SOCKETIO=redis-socketio:6379
      - SOCKETIO_PORT=9000
      - AUTO_MIGRATE=1
    volumes:
      - "/var/homelabos/erpnext/sites:/home/frappe/frappe-bench/sites"
      - "/var/homelabos/erpnext/assets-vol:/home/frappe/frappe-bench/sites/assets"

  frappe-socketio:
    networks:
      - traefik_network
    image: frappe/frappe-socketio:${VERSION}
    restart: on-failure
    depends_on:
      - redis-socketio
    links:
      - redis-socketio
    volumes:
      - "/var/homelabos/erpnext/sites:/home/frappe/frappe-bench/sites"


  frappe-worker-default:
    networks:
      - traefik_network
    image: frappe/erpnext-worker:${VERSION}
    restart: on-failure
    command: worker
    depends_on:
      - redis-queue
      - redis-cache
    links:
      - redis-queue
      - redis-cache
    volumes:
      - "/var/homelabos/erpnext/sites:/home/frappe/frappe-bench/sites"

  frappe-worker-short:
    image: frappe/erpnext-worker:${VERSION}
    networks:
      - traefik_network
    restart: on-failure
    command: worker
    environment:
      - WORKER_TYPE=short
    depends_on:
      - redis-queue
      - redis-cache
    links:
      - redis-queue
      - redis-cache
    volumes:
      - "/var/homelabos/erpnext/sites:/home/frappe/frappe-bench/sites"

  frappe-worker-long:
    image: frappe/erpnext-worker:${VERSION}
    networks:
      - traefik_network
    restart: on-failure
    command: worker
    environment:
      - WORKER_TYPE=long
    depends_on:
      - redis-queue
      - redis-cache
    links:
      - redis-queue
      - redis-cache
    volumes:
      - "/var/homelabos/erpnext/sites:/home/frappe/frappe-bench/sites"

  frappe-schedule:
    image: frappe/erpnext-worker:${VERSION}
    networks:
      - traefik_network
    restart: on-failure
    command: schedule
    depends_on:
      - redis-queue
      - redis-cache
    links:
      - redis-queue
      - redis-cache
    volumes:
      - "/var/homelabos/erpnext/sites:/home/frappe/frappe-bench/sites"
```

## Steps to reproduce the issue

1. Spin up this docker compose file, and try and access erpnext.

### Observed result

Internal Server Error

### Expected result

Working application.

### Stacktrace / full error message if available

```
[2020-04-22 15:55:11 +0000] [25] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 53, in application
    init_request(request)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 108, in init_request
    frappe.init(site=site, sites_path=_sites_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 149, in init
    local.conf = _dict(get_site_config())
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 223, in get_site_config
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 72, in __getattr__
    return self.__storage__[self.__ident_func__()][name]
KeyError: 'conf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 309, in _get_current_object
    return getattr(self.__local, self.__name__)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 74, in __getattr__
    raise AttributeError(name)
AttributeError: conf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 280, in handle
    keepalive = self.handle_request(req, conn)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 329, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 231, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/wrappers/base_request.py", line 237, in application
    resp = f(*args[:-2] + (request,))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 96, in application
    frappe.monitor.stop(response)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/monitor.py", line 26, in stop
    if frappe.conf.monitor and hasattr(frappe.local, "monitor"):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 311, in _get_current_object
    raise RuntimeError("no object bound to %s" % self.__name__)
RuntimeError: no object bound to conf
```

**Comment by revant** [comment]
> "SITE_NAME=SITE"

that means http://SITE should work given it resolves and connects to the nginx container

go through this comment: https://github.com/frappe/frappe_docker/issues/182#issuecomment-609899924

only site names that are available under `sites` directory resolve and serve the site

**Comment by NickBusey** [comment]
Yup, setting SITE_NAME to the URL worked.

The docs could maybe clarify this a bit. I think most people would expect SITE_NAME to be something like `ERPNext` and the url to be defined in SITE_URL=`erpnext.mydomain.com`

Also it's not clear why there is SITE_NAME and SITES env vars. But this worked, so closing, thanks.

**Comment by revant** [comment]
@NickBusey

Please do send a PR that will make confusion clear.

SITE_NAME variable is equivalent of `bench new-site <site_name>`

SITES variable I've used for resolving sites for nginx. Change accordingly for traefik.

May be with `HostRegexp`
```
traefik.http.routers.erpnext-http.rule=Host(`${SITES}`)
```
