### ISSUE TITLE
pymysql.err.OperationalError 1045, Access denied for user

### ISSUE THREAD

**Issue by roquegv** [frappe/frappe_docker#239]
## Description of the issue
When accessing localhost:8000 I got:

`pymysql.err.OperationalError: (1045, u"Access denied for user ‘_69928f0f6369849a’@‘172.30.0.2’ (using password: YES)")`

## Context information (for bug reports)

Running the development enviroment. Using the VS code's Remote - Containers extension

## Steps to reproduce the issue

1. Access localhost:8000 or mysite.localhost:8000 (the error shows in the console and in html format)
2. OR Running any bench command like `bench mariadb`, `bench console`, etc (the error shows in the console)

### Stacktrace / full error message if available

```
15:18:47 web.1            | INFO:werkzeug:172.30.0.1 - - [18/May/2020 15:18:47] "GET / HTTP/1.1" 500 -
15:18:47 web.1            | Traceback (most recent call last):
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/app.py", line 53, in application
15:18:47 web.1            |     init_request(request)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/app.py", line 120, in init_request
15:18:47 web.1            |     frappe.local.http_request = frappe.auth.HTTPRequest()
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/auth.py", line 51, in __init__
15:18:47 web.1            |     frappe.local.login_manager = LoginManager()
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/auth.py", line 113, in __init__
15:18:47 web.1            |     self.make_session(resume=True)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/auth.py", line 188, in make_session
15:18:47 web.1            |     full_name=self.full_name, user_type=self.user_type)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/sessions.py", line 194, in __init__
15:18:47 web.1            |     self.resume()
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/sessions.py", line 261, in resume
15:18:47 web.1            |     validate_ip_address(self.user)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/auth.py", line 404, in validate_ip_address
15:18:47 web.1            |     user = frappe.get_cached_doc("User", user) if not frappe.flags.in_test else frappe.get_doc("User", user)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 710, in get_cached_doc
15:18:47 web.1            |     doc = get_doc(*args, **kwargs)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 753, in get_doc
15:18:47 web.1            |     doc = frappe.model.document.get_doc(*args, **kwargs)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/model/document.py", line 69, in get_doc
15:18:47 web.1            |     controller = get_controller(doctype)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/model/base_document.py", line 37, in get_controller
15:18:47 web.1            |     module_name, custom = frappe.db.get_value("DocType", doctype, ("module", "custom"), cache=True) \
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/database/database.py", line 401, in get_value
15:18:47 web.1            |     order_by, cache=cache)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/database/database.py", line 445, in get_values
15:18:47 web.1            |     out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/database/database.py", line 592, in _get_values_from_table
15:18:47 web.1            |     as_dict=as_dict, debug=debug, update=update)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
15:18:47 web.1            |     self.connect()
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
15:18:47 web.1            |     self._conn = self.get_connection()
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 96, in get_connection
15:18:47 web.1            |     conn.select_db(self.user)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 446, in select_db
15:18:47 web.1            |     self._read_ok_packet()
15:18:47 web.1            |   File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 394, in _read_ok_packet
15:18:47 web.1            |     pkt = self._read_packet()
15:18:47 web.1            |   File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
15:18:47 web.1            |     packet.check_error()
15:18:47 web.1            |   File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
15:18:47 web.1            |     err.raise_mysql_exception(self._data)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
15:18:47 web.1            |     raise errorclass(errno, errval)
15:18:47 web.1            | pymysql.err.OperationalError: (1044, "Access denied for user '_69928f0f6369849a'@'172.30.0.%' to database '_69928f0f6369849a'")
15:18:47 web.1            | 
15:18:47 web.1            | During handling of the above exception, another exception occurred:
15:18:47 web.1            | 
15:18:47 web.1            | Traceback (most recent call last):
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/middlewares.py", line 16, in __call__
15:18:47 web.1            |     return super(StaticDataMiddleware, self).__call__(environ, start_response)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
15:18:47 web.1            |     return self.app(environ, start_response)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
15:18:47 web.1            |     return self.app(environ, start_response)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 231, in application
15:18:47 web.1            |     return ClosingIterator(app(environ, start_response), self.cleanup)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/werkzeug/wrappers/base_request.py", line 237, in application
15:18:47 web.1            |     resp = f(*args[:-2] + (request,))
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/app.py", line 83, in application
15:18:47 web.1            |     response = handle_exception(e)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/app.py", line 194, in handle_exception
15:18:47 web.1            |     http_status_code=http_status_code)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/website/render.py", line 33, in render
15:18:47 web.1            |     raise_if_disabled(path)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/website/render.py", line 345, in raise_if_disabled
15:18:47 web.1            |     'route': ['like', '%{0}'.format(path)]
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/database/database.py", line 528, in get_all
15:18:47 web.1            |     return frappe.get_all(*args, **kwargs)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 1318, in get_all
15:18:47 web.1            |     return get_list(doctype, *args, **kwargs)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 1291, in get_list
15:18:47 web.1            |     return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/model/db_query.py", line 96, in execute
15:18:47 web.1            |     result = self.build_and_run()
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/model/db_query.py", line 110, in build_and_run
15:18:47 web.1            |     args = self.prepare_args()
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/model/db_query.py", line 136, in prepare_args
15:18:47 web.1            |     self.set_optional_columns()
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/model/db_query.py", line 298, in set_optional_columns
15:18:47 web.1            |     columns = get_table_columns(self.doctype)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
15:18:47 web.1            |     return frappe.db.get_table_columns(doctype)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/database/database.py", line 863, in get_table_columns
15:18:47 web.1            |     columns = self.get_db_table_columns('tab' + doctype)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/database/database.py", line 854, in get_db_table_columns
15:18:47 web.1            |     where table_name = %s ''', table)]
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
15:18:47 web.1            |     self.connect()
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
15:18:47 web.1            |     self._conn = self.get_connection()
15:18:47 web.1            |   File "/workspace/development/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 96, in get_connection
15:18:47 web.1            |     conn.select_db(self.user)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 446, in select_db
15:18:47 web.1            |     self._read_ok_packet()
15:18:47 web.1            |   File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 394, in _read_ok_packet
15:18:47 web.1            |     pkt = self._read_packet()
15:18:47 web.1            |   File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
15:18:47 web.1            |     packet.check_error()
15:18:47 web.1            |   File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
15:18:47 web.1            |     err.raise_mysql_exception(self._data)
15:18:47 web.1            |   File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
15:18:47 web.1            |     raise errorclass(errno, errval)
15:18:47 web.1            | pymysql.err.OperationalError: (1044, "Access denied for user '_69928f0f6369849a'@'172.30.0.%' to database '_69928f0f6369849a'")
```

**Comment by roquegv** [comment]
The problem seems to be with the ip address.

The way I manage to workaroud this problem is by:
1. Enter the mariadb docker container: `docker exec -ti <CONTAINER_ID> bash`
2. Enter mysql: `mysql -u root -p` (default pass is 123)
2. Using wildcards for mysql.user Hosts: 
2.1. UPDATE mysql.user SET host = '172.30.0.%' WHERE host = '172.30.0.2';
2.2. UPDATE mysql.db SET host = '172.30.0.%' WHERE host = '172.30.0.2';
2.3. FLUSH PRIVILEGES;

Then ir works.

This is jus a workaround. There should be a better solution.
Thanks

**Comment by khadijazaki2** [comment]
Have you tried the mariadb error fix?
https://github.com/frappe/frappe_docker/blob/develop/development/README.md#fixing-mariadb-issues-after-rebuilding-the-container
this one?

**Comment by revant** [comment]
Now there is `--no-mariadb-socket` option available in `bench new-site` command.
It sets the credential suitable for docker at the time of site creation.

**Comment by roquegv** [comment]
I didn't see it. Looks nice! 

It is a similar aproach. Ideally this should be done at the time the container is built.

Thanks @khadijazaki2 

EDIT: that's nice @revant, next time this shouldn't be a problem. Thanks

**Comment by alexschomb** [comment]
Unfortuantely this didn't fix it for me. Starting from scratch I can't run a single bench installation at all. The logs indicate that there are several access dienied errors during the installation (``site-creator_1``).

Looking at the ``mysql.user`` table I can understand why that happens. It appears like the IP of ``site-creator`` is not allowed to access the mariadb database with the user ``root``, only with the generic username (in my case ``_c0fa167dd2d0e58a``)  - but that seems to be necessary for installation. On the other hand the IP of the ``erpnext-schedule_1`` docker is not allowed to access the mariadb database at all, but tries to do that regularly with the generic username.

Any idea how to solve that? And is there any way to manually define/setup the username/password of the productive users? That would allow us to use a common mariadb database for multiple docker projects and not a separate one just for frappe/erpnext.

**Comment by revant** [comment]
@alexschomb 

This issues was regarding frappe/bench:latest image. Are you facing this for development? I think your issue is with production setup? Create new issue for production image.

> Any idea how to solve that (for the setup process)? Because the setup won't be run a second time (after manually fixing the mariadb permissions) as the erpnext site was already created.

How did you manually fixed the mariadb permission? May be that can automated?

> And is there any way to manually define/setup the username/password of the productive users? That would allow us to use a common mariadb database for multiple docker projects and not a separate one just for frappe/erpnext.

Setup mariadb as a separate docker stack can solve this? Like described in Docker swarm setup?
