### ISSUE TITLE
Multiple issue with rendering, updating and so on

### ISSUE THREAD

**Issue by zenny** [frappe/frappe_docker#25]
Hi,

I deployed docker image (to an alpinelinux v3.7 host and another on ubuntu 16.04 host.

A. UPDATE: I have also tried to run in a Ubuntu 16.04 dockerhost instead of alpinelinux v3.7 as host, but the issue no. 1 below was unchanged, despite 'bench start' seemed to work without an error:

```
root@86aeaee4f8b6:/home/frappe/frappe-bench# bench start
2017-12-25 10:27:50 [67] [WARNING] Your terminal is not configured to receive UTF-8 encoded text. Please adjust your locale settings or force UTF-8 output by setting PYTHONIOENCODING="utf-8".
10:27:50 system           | worker_long.1 started (pid=85)
10:27:50 system           | watch.1 started (pid=90)
10:27:50 system           | schedule.1 started (pid=92)
10:27:50 system           | web.1 started (pid=91)
10:27:50 system           | worker_default.1 started (pid=95)
10:27:50 system           | socketio.1 started (pid=94)
10:27:50 system           | worker_short.1 started (pid=93)
10:27:52 socketio.1       | listening on *: 9000
10:27:55 web.1            |  * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
10:27:55 web.1            |  * Restarting with inotify reloader
10:27:55 worker_long.1    | 10:27:55 RQ worker u'rq:worker:86aeaee4f8b6.97.long' started, version 0.9.2
10:27:55 worker_long.1    | 10:27:55 Cleaning registries for queue: long
10:27:55 worker_long.1    | 10:27:55
10:27:55 worker_long.1    | 10:27:55 *** Listening on long...
10:27:55 worker_default.1 | 10:27:55 RQ worker u'rq:worker:86aeaee4f8b6.105.default' started, version 0.9.2
10:27:55 worker_short.1   | 10:27:55 RQ worker u'rq:worker:86aeaee4f8b6.106.short' started, version 0.9.2
10:27:55 worker_default.1 | 10:27:55 Cleaning registries for queue: default
10:27:55 worker_short.1   | 10:27:55 Cleaning registries for queue: short
10:27:55 worker_default.1 | 10:27:55
10:27:55 worker_default.1 | 10:27:55 *** Listening on default...
10:27:55 worker_short.1   | 10:27:55
10:27:55 worker_short.1   | 10:27:55 *** Listening on short...
10:27:56 web.1            |  * Debugger is active!
10:27:56 web.1            |  * Debugger PIN: 724-973-074
10:27:56 watch.1          | compiling avatar.less
10:27:56 watch.1          | compiling calendar.less
10:27:56 watch.1          | compiling common.less
10:27:56 watch.1          | compiling controls.less
10:27:56 watch.1          | compiling desk.less
10:27:56 watch.1          | compiling desktop.less
10:27:56 watch.1          | compiling docs.less
10:27:56 watch.1          | compiling email.less
10:27:56 watch.1          | compiling form.less
10:27:56 watch.1          | compiling form_grid.less
10:27:56 watch.1          | compiling gantt.less
10:27:56 watch.1          | compiling indicator.less
10:27:56 watch.1          | compiling kanban.less
10:27:56 watch.1          | compiling list.less
10:27:56 watch.1          | compiling mixins.less
10:27:56 watch.1          | compiling mobile.less
10:27:56 watch.1          | compiling module.less
10:27:56 watch.1          | compiling navbar.less
10:27:56 watch.1          | compiling page.less
10:27:56 watch.1          | compiling report.less
10:27:56 watch.1          | compiling role_editor.less
10:27:56 watch.1          | compiling sidebar.less
10:27:56 watch.1          | compiling slickgrid.less
10:27:56 watch.1          | compiling tags.less
10:27:56 watch.1          | compiling tree.less
10:27:56 watch.1          | compiling website.less
10:27:56 watch.1          | compiling email.less
10:27:56 watch.1          | compiling erpnext.less
10:27:56 watch.1          | compiling hub.less
10:27:56 watch.1          | compiling pos.less
10:27:56 watch.1          | compiling website.less
10:27:56 watch.1          | file watching on *: 6787
10:27:57 watch.1          | Less files compiled
10:27:57 watch.1          | Wrote css/frappe-web.css - 65.43 KB
10:27:57 watch.1          | Wrote js/frappe-web.min.js - 135.3 KB
10:27:57 watch.1          | Wrote js/control.min.js - 81.33 KB
10:27:57 watch.1          | Wrote js/dialog.min.js - 124.04 KB
10:27:57 watch.1          | Wrote css/desk.min.css - 310.76 KB
10:27:57 watch.1          | Wrote css/frappe-rtl.css - 32.73 KB
10:27:57 watch.1          | Wrote js/libs.min.js - 1.12 MB
10:27:57 watch.1          | Wrote js/desk.min.js - 475.77 KB
10:27:57 watch.1          | Wrote css/module.min.css - 2.16 KB
10:27:57 watch.1          | Wrote css/form.min.css - 4.55 KB
10:27:57 watch.1          | Wrote js/form.min.js - 205.4 KB
10:27:57 watch.1          | Wrote css/list.min.css - 13.66 KB
10:27:57 watch.1          | Wrote js/list.min.js - 161.49 KB
10:27:57 watch.1          | Wrote css/report.min.css - 8.31 KB
10:27:58 watch.1          | Wrote js/report.min.js - 262.89 KB
10:27:58 watch.1          | Wrote js/web_form.min.js - 248.66 KB
10:27:58 watch.1          | Wrote css/web_form.css - 24.69 KB
10:27:58 watch.1          | Wrote js/print_format_v3.min.js - 25.87 KB
10:27:58 watch.1          | Wrote css/erpnext.css - 8.08 KB
10:27:58 watch.1          | Wrote js/erpnext-web.min.js - 4.22 KB
10:27:58 watch.1          | Wrote js/erpnext.min.js - 167.93 KB
10:27:58 watch.1          | Wrote js/item-dashboard.min.js - 8.22 KB
```

B. dockerhost=alpinelinux v3.7. 

```
dockerhost:~/gitrepos/frappe_docker# docker ps
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                                                                    NAMES
a381e3123a51        frappedocker_frappe   "/bin/bash"              20 hours ago        Up 10 minutes       0.0.0.0:6787->6787/tcp, 0.0.0.0:8000->8000/tcp, 0.0.0.0:9000->9000/tcp   frappe
81b27de35ff4        redis:alpine          "docker-entrypoint..."   20 hours ago        Up 10 minutes       6379/tcp                                                                 redis-cache
836037a84ce1        redis:alpine          "docker-entrypoint..."   20 hours ago        Up 10 minutes       6379/tcp                                                                 redis-queue
ec758d0d4631        redis:alpine          "docker-entrypoint..."   20 hours ago        Up 10 minutes       6379/tcp                                                                 redis-socketio
d97f12fff7ef        mariadb               "docker-entrypoint..."   20 hours ago        Up 10 minutes       0.0.0.0:3307->3306/tcp                                                   mariadb
```

# Issue no. 1: 
trying to access to external_ip:8000 gives a blank page.

# Issue No. 2:
As explained in https://github.com/frappe/frappe_docker/issues/19#issuecomment-353840043,'bench start' fails to run.

# Issue no. 3:
Trying to update the bench gave the following error:
```
dockerhost:~/gitrepos/frappe_docker# ./dbench -c update

This update will remove Celery config and prepare the bench to use Python RQ.
And it will overwrite Procfile and supervisor.conf.
If you don't know what this means, type Y ;)

Do you want to continue? [y/N]: y

This update will replace ERPNext's Redis configuration files to fix a major security issue.
If you don't know what this means, type Y ;)

Do you want to continue? [y/N]: y
/bin/sh: 1: redis-server: not found
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/commands/update.py", line 31, in update
    patches.run(bench_path='.')
  File "/home/frappe/bench-repo/bench/patches/__init__.py", line 21, in run
    result = execute(bench_path)
  File "/home/frappe/bench-repo/bench/patches/v3/redis_bind_ip.py", line 10, in execute
    generate_config(bench_path)
  File "/home/frappe/bench-repo/bench/config/redis.py", line 39, in generate_config
    "redis_version": get_redis_version(),
  File "/home/frappe/bench-repo/bench/config/redis.py", line 59, in get_redis_version
    version_string = subprocess.check_output('redis-server --version', shell=True).decode().strip()
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'redis-server --version' returned non-zero exit status 127
```

Memory is adequately set aside and does not seem to be an issue unlike it was stated at https://discuss.erpnext.com/t/fails-to-build-docker-frappe/31896

```
dockerhost:~/gitrepos/frappe_docker# free -m
             total       used       free     shared    buffers     cached
Mem:          7973        761       7212         19         47        313
-/+ buffers/cache:        400       7573
Swap:         4095          0       4095
```
# Issue no. 4

Upon some research, it seemed like it was related to https://github.com/frappe/frappe_docker/issues/19#issuecomment-348860294. Even https://github.com/ierturk/frappe_docker repo gives an error './dbench init_frappe' as in two accounts (npm and sudo) as shown in bold below:

```
...
Successfully tagged ierturkfrappedocker_frappe:latest
WARNING: Image for service frappe was built because it did not already exist. To rebuild this image you must use `docCreating redis-socketio ... done
Creating frappe ... done
Creating redis-cache ... 
Creating redis-socketio ... 
Creating mariadb ... 
Creating frappe ... 
dockerhost:~/gitrepos/ierturk_frappe_docker# ./dbench init_frappe
INFO:bench.utils:virtualenv -q env -p /usr/bin/python
Already using interpreter /usr/bin/python
INFO:bench.utils:./env/bin/pip -q install --upgrade pip
INFO:bench.utils:./env/bin/pip -q install wheel
INFO:bench.utils:./env/bin/pip -q install -e git+https://github.com/frappe/python-pdfkit.git#egg=pdfkit
INFO:bench.app:getting app frappe
INFO:bench.utils:git clone https://github.com/frappe/frappe.git   --origin upstream
Cloning into 'frappe'...
remote: Counting objects: 147638, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 147638 (delta 0), reused 1 (delta 0), pack-reused 147632
Receiving objects: 100% (147638/147638), 125.52 MiB | 801.00 KiB/s, done.
Resolving deltas: 100% (112118/112118), done.

_**Checking connectivity... done.
('installing', u'frappe')
INFO:bench.app:installing frappe
INFO:bench.utils:frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe --no-cache-dir
Updating node libraries...
INFO:bench.utils:npm install
Segmentation fault
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/commands/make.py", line 21, in init
    verbose=verbose, clone_from=clone_from, skip_bench_mkdir=skip_bench_mkdir, skip_redis_config_generation=skip_redis_config_generation)
  File "/home/frappe/bench-repo/bench/utils.py", line 72, in init
    update_npm_packages(bench_path=path)
  File "/home/frappe/bench-repo/bench/utils.py", line 441, in update_npm_packages
    exec_cmd('npm install', cwd=bench_path)
  File "/home/frappe/bench-repo/bench/utils.py", line 140, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: npm install**_

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libgpm2 libpython3.5 vim-common vim-runtime
Suggested packages:
  gpm ctags vim-doc vim-scripts vim-gnome-py2 | vim-gtk-py2 | vim-gtk3-py2 | vim-athena-py2 | vim-nox-py2
The following NEW packages will be installed:
  libgpm2 libpython3.5 vim vim-common vim-runtime
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 7679 kB of archives.
After this operation, 35.1 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 libgpm2 amd64 1.20.4-6.1 [16.5 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 vim-common amd64 2:7.4.1689-3ubuntu1.2 [103 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libpython3.5 amd64 3.5.2-2ubuntu0~16.04.4 [1360 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 vim-runtime all 2:7.4.1689-3ubuntu1.2 [5164 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 vim amd64 2:7.4.1689-3ubuntu1.2 [1036 kB]          
Fetched 7679 kB in 14s (523 kB/s)                                                                                   
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 5.)
debconf: falling back to frontend: Readline
Selecting previously unselected package libgpm2:amd64.
(Reading database ... 31432 files and directories currently installed.)
Preparing to unpack .../libgpm2_1.20.4-6.1_amd64.deb ...
Unpacking libgpm2:amd64 (1.20.4-6.1) ...
Selecting previously unselected package vim-common.
Preparing to unpack .../vim-common_2%3a7.4.1689-3ubuntu1.2_amd64.deb ...
Unpacking vim-common (2:7.4.1689-3ubuntu1.2) ...
Selecting previously unselected package libpython3.5:amd64.
Preparing to unpack .../libpython3.5_3.5.2-2ubuntu0~16.04.4_amd64.deb ...
Unpacking libpython3.5:amd64 (3.5.2-2ubuntu0~16.04.4) ...
Selecting previously unselected package vim-runtime.
Preparing to unpack .../vim-runtime_2%3a7.4.1689-3ubuntu1.2_all.deb ...
Adding 'diversion of /usr/share/vim/vim74/doc/help.txt to /usr/share/vim/vim74/doc/help.txt.vim-tiny by vim-runtime'
Adding 'diversion of /usr/share/vim/vim74/doc/tags to /usr/share/vim/vim74/doc/tags.vim-tiny by vim-runtime'
Unpacking vim-runtime (2:7.4.1689-3ubuntu1.2) ...
Selecting previously unselected package vim.
Preparing to unpack .../vim_2%3a7.4.1689-3ubuntu1.2_amd64.deb ...
Unpacking vim (2:7.4.1689-3ubuntu1.2) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Setting up libgpm2:amd64 (1.20.4-6.1) ...
Setting up vim-common (2:7.4.1689-3ubuntu1.2) ...
Setting up libpython3.5:amd64 (3.5.2-2ubuntu0~16.04.4) ...
Setting up vim-runtime (2:7.4.1689-3ubuntu1.2) ...
Setting up vim (2:7.4.1689-3ubuntu1.2) ...
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vim (vim) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vimdiff (vimdiff) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rvim (rvim) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rview (rview) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vi (vi) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/view (view) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/ex (ex) in auto mode
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  sudo
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 390 kB of archives.
After this operation, 1618 kB of additional disk space will be used.

_**Get:1 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 sudo amd64 1.8.16-0ubuntu1.5 [390 kB]
Fetched 390 kB in 1s (378 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
Selecting previously unselected package sudo.
(Reading database ... 33218 files and directories currently installed.)
Preparing to unpack .../sudo_1.8.16-0ubuntu1.5_amd64.deb ...
Unpacking sudo (1.8.16-0ubuntu1.5) ...
dpkg: error processing archive /var/cache/apt/archives/sudo_1.8.16-0ubuntu1.5_amd64.deb (--unpack):
 error setting permissions of './usr/bin/sudo': Permission denied
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
unknown argument --> abort-install
Errors were encountered while processing:
 /var/cache/apt/archives/sudo_1.8.16-0ubuntu1.5_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)**_

Installing frappe...
Updating DocTypes for frappe        : [========================================]
Updating country info               : [========================================]
*** Scheduler is disabled ***
INFO:bench.app:getting app erpnext
INFO:bench.utils:git clone https://github.com/frappe/erpnext  --depth 1 --origin upstream
Cloning into 'erpnext'...
remote: Counting objects: 6325, done.
remote: Compressing objects: 100% (5571/5571), done.
remote: Total 6325 (delta 1204), reused 3275 (delta 590), pack-reused 0
Receiving objects: 100% (6325/6325), 179.03 MiB | 818.00 KiB/s, done.
Resolving deltas: 100% (1204/1204), done.
Checking connectivity... done.
Checking out files: 100% (6281/6281), done.
('installing', u'erpnext')
INFO:bench.app:installing erpnext
INFO:bench.utils:./env/bin/pip install -q  -e ./apps/erpnext --no-cache-dir

Installing erpnext...
Updating DocTypes for erpnext       : [========================================]
dockerhost:~/gitrepos/ierturk_frappe_docker# docker-compose start
Starting mariadb        ... done
Starting redis-queue    ... done
Starting redis-cache    ... done
Starting redis-socketio ... done
Starting frappe         ... done
dockerhost:~/gitrepos/ierturk_frappe_docker# 
```
Any clues?

**Comment by clarkejj** [comment]
Issue # 3 reported & not resolved 10 months ago https://discuss.erpnext.com/t/problem-with-bench-update-redis-server-not-found/19793/6

sudo denies permission to update itself!?

Preparing to unpack .../sudo_1.8.16-0ubuntu1.5_amd64.deb ...
Unpacking sudo (1.8.16-0ubuntu1.5) ...
dpkg: error processing archive /var/cache/apt/archives/sudo_1.8.16-0ubuntu1.5_amd64.deb (--unpack):
 error setting permissions of './usr/bin/sudo': Permission denied
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)

**Comment by chabad360** [comment]
Please close as this is no longer relevant.
