### ISSUE TITLE
Cannot finalize site-creator

### ISSUE THREAD

**Issue by tonihoang** [frappe/frappe_docker#310]
# Description of the issue

Site creator does not finish, throws an error in edge version, and in version-12-hotfix version-13-bet

Looks like a problem with database setup. As I am new, in erpnext have not found the source yet.

## Steps to reproduce the issue

1. Start PWD
2. check logs of site creator
3. using webinterface to setup initial data --> same error

### Observed result
frappe.core.doctype.doctype.doctype.UniqueFieldnameError: Purchase Receipt: Fieldname project appears multiple times in rows 97, 102

### Expected result
no error

### Stacktrace / full error message if available

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/commands/new.py", line 106, in <module>
    main()
  File "/home/frappe/frappe-bench/commands/new.py", line 59, in main
    db_port=db_port,
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 91, in _new_site
    _install_app(app, verbose=verbose, set_as_patched=not source_sql)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 86, in install_app
    add_to_installed_apps(name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 111, in add_to_installed_apps
    post_install(rebuild_website)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 190, in post_install
    init_singles()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 211, in init_singles
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 281, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 303, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 264, in insert
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 953, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 820, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1112, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1095, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 814, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/global_defaults/global_defaults.py", line 48, in on_update
    self.toggle_in_words()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/doctype/global_defaults/global_defaults.py", line 74, in toggle_in_words
    make_property_setter(doctype, "in_words", "hidden", self.disable_in_words, "Check")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/custom/doctype/property_setter/property_setter.py", line 90, in make_property_setter
    property_setter.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 264, in insert
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 953, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 820, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1112, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1095, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 814, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/custom/doctype/property_setter/property_setter.py", line 74, in on_update
    validate_fields_for_doctype(self.doc_type)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 650, in validate_fields_for_doctype
    validate_fields(frappe.get_meta(doctype, cached=False))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 946, in validate_fields
    check_unique_fieldname(meta.get("name"), d.fieldname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 684, in check_unique_fieldname
    frappe.throw(_("{0}: Fieldname {1} appears multiple times in rows {2}").format(docname, fieldname, ", ".join(duplicates)), UniqueFieldnameError)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 396, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 375, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 326, in _raise_exception
    raise raise_exception(msg)
frappe.core.doctype.doctype.doctype.UniqueFieldnameError: Purchase Receipt: Fieldname project appears multiple times in rows 97, 102
```

**Comment by revant** [comment]
this is an issue with ERPNext develop branch

https://github.com/frappe/erpnext/issues/22687

I'll close it from here

**Comment by tonihoang** [comment]
as mentioned, I tried replacing the values in the config files with "version-12" "version-12-hotfix" "version-13-beta" (both erpnext and frappe), not working as well

**Comment by tonihoang** [comment]
looks like all of these versions were broken by this:

![image](https://user-images.githubusercontent.com/19792352/87548062-4440e680-c6ac-11ea-84f0-ddbdf44492ea.png)

**Comment by revant** [comment]
They are built at same time but they have different branches.

I created a v12 site 8 hrs ago on fresh docker swarm install.

Test are passing for v12
https://travis-ci.com/github/frappe/frappe_docker/jobs/361298408#L542

**Comment by Thunderbottom** [comment]
> as mentioned, I tried replacing the values in the config files with "version-12" "version-12-hotfix" "version-13-beta" (both erpnext and frappe), not working as well

seems like the images for those versions have not been pulled?

> it seems the problem is in bench, and I cannot edit the bench version from config files (.env)

(un)fortunately there's no bench included with the docker setup.

could you try pulling a specific image and then try setting the system up again?
