### ISSUE TITLE
MariaDB connection problem

### ISSUE THREAD

**Issue by JanMrlth** [frappe/frappe_docker#311]
## Description of the issue
There seems to be a problem for the site-creator to connect to mariadb

## Steps to reproduce the issue

1. configure the .env file 
2. docker-compose --project-name gobanosde up -d

### Observed result
Site Creator can not connect to mariadb

### Expected result
sitecreator should connect to mariadb 

### Stacktrace / full error message if available

LOG of MariaDB: 

020-07-15 10:02:30+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.3.23+maria~focal started.
2020-07-15 10:02:31+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2020-07-15 10:02:31+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.3.23+maria~focal started.
2020-07-15 10:02:31+00:00 [Note] [Entrypoint]: Initializing database files

PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
To do so, start the server, then issue the following commands:

'/usr/bin/mysqladmin' -u root password 'new-password'
'/usr/bin/mysqladmin' -u root -h  password 'new-password'

Alternatively you can run:
'/usr/bin/mysql_secure_installation'

which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.

See the MariaDB Knowledgebase at http://mariadb.com/kb or the
MySQL manual for more instructions.

Please report any problems at http://mariadb.org/jira

The latest information about MariaDB is available at http://mariadb.org/.
You can find additional information about the MySQL part at:
http://dev.mysql.com
Consider joining MariaDB's strong and vibrant community:
https://mariadb.org/get-involved/

2020-07-15 10:02:34+00:00 [Note] [Entrypoint]: Database files initialized
2020-07-15 10:02:34+00:00 [Note] [Entrypoint]: Starting temporary server
2020-07-15 10:02:34+00:00 [Note] [Entrypoint]: Waiting for server startup
2020-07-15 10:02:34 0 [Note] mysqld (mysqld 10.3.23-MariaDB-1:10.3.23+maria~focal) starting as process 120 ...
2020-07-15 10:02:35 0 [Note] InnoDB: Using Linux native AIO
2020-07-15 10:02:35 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2020-07-15 10:02:35 0 [Note] InnoDB: Uses event mutexes
2020-07-15 10:02:35 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2020-07-15 10:02:35 0 [Note] InnoDB: Number of pools: 1
2020-07-15 10:02:35 0 [Note] InnoDB: Using SSE2 crc32 instructions
2020-07-15 10:02:35 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
2020-07-15 10:02:35 0 [Note] InnoDB: Completed initialization of buffer pool
2020-07-15 10:02:35 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2020-07-15 10:02:35 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2020-07-15 10:02:35 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2020-07-15 10:02:35 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2020-07-15 10:02:35 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2020-07-15 10:02:35 0 [Note] InnoDB: Waiting for purge to start
2020-07-15 10:02:35 0 [Note] InnoDB: 10.3.23 started; log sequence number 1625448; transaction id 21
2020-07-15 10:02:35 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2020-07-15 10:02:35 0 [Note] Plugin 'FEEDBACK' is disabled.
2020-07-15 10:02:35 0 [Warning] 'user' entry 'root@53b406cde6cb' ignored in --skip-name-resolve mode.
2020-07-15 10:02:35 0 [Warning] 'user' entry '@53b406cde6cb' ignored in --skip-name-resolve mode.
2020-07-15 10:02:35 0 [Warning] 'proxies_priv' entry '@% root@53b406cde6cb' ignored in --skip-name-resolve mode.
2020-07-15 10:02:35 0 [Note] InnoDB: Buffer pool(s) load completed at 200715 10:02:35
2020-07-15 10:02:35 0 [Note] Reading of all Master_info entries succeeded
2020-07-15 10:02:35 0 [Note] Added new Master_info '' to hash table
2020-07-15 10:02:35 0 [Note] mysqld: ready for connections.
Version: '10.3.23-MariaDB-1:10.3.23+maria~focal'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
2020-07-15 10:02:35+00:00 [Note] [Entrypoint]: Temporary server started.
Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
2020-07-15 10:02:39 10 [Warning] 'proxies_priv' entry '@% root@53b406cde6cb' ignored in --skip-name-resolve mode.

2020-07-15 10:02:39+00:00 [Note] [Entrypoint]: Stopping temporary server
2020-07-15 10:02:39 0 [Note] mysqld (initiated by: root[root] @ localhost []): Normal shutdown
2020-07-15 10:02:39 0 [Note] InnoDB: FTS optimize thread exiting.
2020-07-15 10:02:39 0 [Note] Event Scheduler: Purging the queue. 0 events
2020-07-15 10:02:39 0 [Note] InnoDB: Starting shutdown...
2020-07-15 10:02:39 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2020-07-15 10:02:39 0 [Note] InnoDB: Buffer pool(s) dump completed at 200715 10:02:39
2020-07-15 10:02:40 0 [Note] InnoDB: Shutdown completed; log sequence number 1625457; transaction id 24
2020-07-15 10:02:40 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2020-07-15 10:02:40 0 [Note] mysqld: Shutdown complete

2020-07-15 10:02:41+00:00 [Note] [Entrypoint]: Temporary server stopped

2020-07-15 10:02:41+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.

2020-07-15 10:02:41 0 [Note] mysqld (mysqld 10.3.23-MariaDB-1:10.3.23+maria~focal) starting as process 1 ...
2020-07-15 10:02:41 0 [Note] InnoDB: Using Linux native AIO
2020-07-15 10:02:41 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2020-07-15 10:02:41 0 [Note] InnoDB: Uses event mutexes
2020-07-15 10:02:41 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2020-07-15 10:02:41 0 [Note] InnoDB: Number of pools: 1
2020-07-15 10:02:41 0 [Note] InnoDB: Using SSE2 crc32 instructions
2020-07-15 10:02:41 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
2020-07-15 10:02:41 0 [Note] InnoDB: Completed initialization of buffer pool
2020-07-15 10:02:41 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2020-07-15 10:02:41 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2020-07-15 10:02:41 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2020-07-15 10:02:41 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2020-07-15 10:02:41 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2020-07-15 10:02:41 0 [Note] InnoDB: 10.3.23 started; log sequence number 1625457; transaction id 21
2020-07-15 10:02:41 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2020-07-15 10:02:41 0 [Note] Plugin 'FEEDBACK' is disabled.
2020-07-15 10:02:41 0 [Note] Server socket created on IP: '::'.
2020-07-15 10:02:41 0 [Warning] 'proxies_priv' entry '@% root@53b406cde6cb' ignored in --skip-name-resolve mode.
2020-07-15 10:02:41 0 [Note] InnoDB: Buffer pool(s) load completed at 200715 10:02:41
2020-07-15 10:02:41 0 [Note] Reading of all Master_info entries succeeded
2020-07-15 10:02:41 0 [Note] Added new Master_info '' to hash table
2020-07-15 10:02:41 0 [Note] mysqld: ready for connections.
Version: '10.3.23-MariaDB-1:10.3.23+maria~focal'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2020-07-15 10:02:45 14 [Warning] Access denied for user 'frappe'@'192.168.224.9' (using password: NO)
2020-07-15 10:02:45 15 [Warning] 'proxies_priv' entry '@% root@53b406cde6cb' ignored in --skip-name-resolve mode.
2020-07-15 10:03:43 18 [Warning] Access denied for user '_06ed80b30352298a'@'192.168.224.13' (using password: YES)
2020-07-15 10:04:18 19 [Warning] 'proxies_priv' entry '@% root@53b406cde6cb' ignored in --skip-name-resolve mode.
2020-07-15 10:04:18 20 [Warning] 'proxies_priv' entry '@% root@53b406cde6cb' ignored in --skip-name-resolve mode.
2020-07-15 10:04:18 21 [Warning] 'proxies_priv' entry '@% root@53b406cde6cb' ignored in --skip-name-resolve mode.
2020-07-15 10:04:18 22 [Warning] 'proxies_priv' entry '@% root@53b406cde6cb' ignored in --skip-name-resolve mode.
2020-07-15 10:04:18 16 [Warning] Aborted connection 16 to db: '_06ed80b30352298a' user: '_06ed80b30352298a' host: '192.168.224.9' (Got an error reading communication packets)

**Comment by revant** [comment]
Can you share the log of site-creator container? or anything in particular?

Use v12 images for this week. ERPNext develop branch has issue with new site creation.

**Comment by JanMrlth** [comment]
Sorry, I was too quick on the trigger. It´s up and running. It was a network problem on my side.

**Comment by revant** [comment]
> Use v12 images for this week. ERPNext develop branch has issue with new site creation.

This got fixed. you can use edge images. last test cron passed successfully

**Comment by jike212** [comment]
This still is not working as of today. I had to manually set the version to 12 from the default of edge in order for site_creator to connect to mariadb to connect properly.

**Comment by revant** [comment]
https://travis-ci.com/github/frappe/frappe_docker/jobs/367085530

Last test passed.

**Comment by Altizo** [comment]
This still is not working as of today. 

### System spec:
Ubuntu 18.04.4 LTS
Docker version 19.03.6
docker-compose version 1.17.1

### ENV:
```
VERSION=edge
MARIADB_HOST=mariadb
MYSQL_ROOT_PASSWORD=admin
SITES=xxx
```

### Starting Multi bench
```
docker-compose --project-name indigo -f installation/docker-compose-common.yml     -f installation/docker-compose-erpnext.yml     -f installation/docker-compose-networks.yml     up -d
```


### Observed result
- authorization fails

### LOG of Worker: 
```
docker run -e "SITE_NAME=xxx" -e "DB_ROOT_USER=root"  -e "MYSQL_ROOT_PASSWORD=admin" -e "ADMIN_PASSWORD=admin" -e "INSTALL_APPS=erpnext" -e FORCE=1 -v "indigo_sites-vol:/home/frappe/frappe-bench/sites" --network indigo_default frappe/erpnext-worker:edge new
```

```
Attempt 1 to connect to mariadb:3306
Attempt 2 to connect to mariadb:3306
Attempt 3 to connect to mariadb:3306
Attempt 4 to connect to mariadb:3306
Attempt 5 to connect to mariadb:3306
Attempt 6 to connect to mariadb:3306
Attempt 7 to connect to mariadb:3306
Attempt 8 to connect to mariadb:3306
Attempt 9 to connect to mariadb:3306
Attempt 10 to connect to mariadb:3306
Connection to mariadb:3306 timed out
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/opt/bitnami/python/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/opt/bitnami/python/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/commands/new.py", line 112, in <module>
    main()
  File "/home/frappe/frappe-bench/commands/new.py", line 59, in main
    db_port=db_port,
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 88, in _new_site
    db_password=db_password, db_type=db_type, db_host=db_host, db_port=db_port, no_mariadb_socket=no_mariadb_socket)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 36, in install_db
    setup_database(force, source_sql, verbose, no_mariadb_socket)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/__init__.py", line 16, in setup_database
    return frappe.database.mariadb.setup_db.setup_database(force, source_sql, verbose, no_mariadb_socket=no_mariadb_socket)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/setup_db.py", line 40, in setup_database
    dbman.delete_user(db_name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/db_manager.py", line 29, in delete_user
    host = self.get_current_host()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/db_manager.py", line 15, in get_current_host
    return self.db.sql("select user()")[0][0].split('@')[1]
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
    self.connect()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
    self._conn = self.get_connection()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 91, in get_connection
    local_infile = frappe.conf.local_infile)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'mariadb' ([Errno -3] Temporary failure in name resolution)")
```


### LOG of MariaDB:
```
2020-08-17 08:44:03+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.3.23+maria~focal started.
2020-08-17 08:44:03+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2020-08-17 08:44:03+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.3.23+maria~focal started.
2020-08-17 08:44:04+00:00 [Note] [Entrypoint]: Initializing database files


PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
To do so, start the server, then issue the following commands:

'/usr/bin/mysqladmin' -u root password 'new-password'
'/usr/bin/mysqladmin' -u root -h  password 'new-password'

Alternatively you can run:
'/usr/bin/mysql_secure_installation'

which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.

See the MariaDB Knowledgebase at http://mariadb.com/kb or the
MySQL manual for more instructions.

Please report any problems at http://mariadb.org/jira

The latest information about MariaDB is available at http://mariadb.org/.
You can find additional information about the MySQL part at:
http://dev.mysql.com
Consider joining MariaDB's strong and vibrant community:
https://mariadb.org/get-involved/

2020-08-17 08:44:49+00:00 [Note] [Entrypoint]: Database files initialized
2020-08-17 08:44:49+00:00 [Note] [Entrypoint]: Starting temporary server
2020-08-17 08:44:49+00:00 [Note] [Entrypoint]: Waiting for server startup
2020-08-17  8:44:49 0 [Note] mysqld (mysqld 10.3.23-MariaDB-1:10.3.23+maria~focal) starting as process 121 ...
2020-08-17  8:44:49 0 [Note] InnoDB: Using Linux native AIO
2020-08-17  8:44:49 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2020-08-17  8:44:49 0 [Note] InnoDB: Uses event mutexes
2020-08-17  8:44:49 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2020-08-17  8:44:49 0 [Note] InnoDB: Number of pools: 1
2020-08-17  8:44:49 0 [Note] InnoDB: Using SSE2 crc32 instructions
2020-08-17  8:44:49 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
2020-08-17  8:44:49 0 [Note] InnoDB: Completed initialization of buffer pool
2020-08-17  8:44:49 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2020-08-17  8:44:51 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2020-08-17  8:44:51 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2020-08-17  8:44:51 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2020-08-17  8:44:51 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2020-08-17  8:44:51 0 [Note] InnoDB: Waiting for purge to start
2020-08-17  8:44:51 0 [Note] InnoDB: 10.3.23 started; log sequence number 1625718; transaction id 21
2020-08-17  8:44:51 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2020-08-17  8:44:51 0 [Note] Plugin 'FEEDBACK' is disabled.
2020-08-17  8:44:51 0 [Note] InnoDB: Buffer pool(s) load completed at 200817  8:44:51
2020-08-17  8:44:56 0 [Warning] 'user' entry 'root@e6fc8a59b059' ignored in --skip-name-resolve mode.
2020-08-17  8:44:56 0 [Warning] 'user' entry '@e6fc8a59b059' ignored in --skip-name-resolve mode.
2020-08-17  8:44:56 0 [Warning] 'proxies_priv' entry '@% root@e6fc8a59b059' ignored in --skip-name-resolve mode.
2020-08-17  8:45:01 0 [Note] Reading of all Master_info entries succeeded
2020-08-17  8:45:01 0 [Note] Added new Master_info '' to hash table
2020-08-17  8:45:01 0 [Note] mysqld: ready for connections.
Version: '10.3.23-MariaDB-1:10.3.23+maria~focal'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
2020-08-17 08:45:01+00:00 [Note] [Entrypoint]: Temporary server started.
Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
2020-08-17  8:45:09 10 [Warning] 'proxies_priv' entry '@% root@e6fc8a59b059' ignored in --skip-name-resolve mode.

2020-08-17 08:45:09+00:00 [Note] [Entrypoint]: Stopping temporary server
2020-08-17  8:45:09 0 [Note] mysqld (initiated by: root[root] @ localhost []): Normal shutdown
2020-08-17  8:45:09 0 [Note] Event Scheduler: Purging the queue. 0 events
2020-08-17  8:45:09 0 [Note] InnoDB: FTS optimize thread exiting.
2020-08-17  8:45:09 0 [Note] InnoDB: Starting shutdown...
2020-08-17  8:45:09 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2020-08-17  8:45:09 0 [Note] InnoDB: Buffer pool(s) dump completed at 200817  8:45:09
2020-08-17  8:45:11 0 [Note] InnoDB: Shutdown completed; log sequence number 1625727; transaction id 24
2020-08-17  8:45:11 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2020-08-17  8:45:12 0 [Note] mysqld: Shutdown complete

2020-08-17 08:45:13+00:00 [Note] [Entrypoint]: Temporary server stopped

2020-08-17 08:45:13+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.

2020-08-17  8:45:13 0 [Note] mysqld (mysqld 10.3.23-MariaDB-1:10.3.23+maria~focal) starting as process 1 ...
2020-08-17  8:45:13 0 [Note] InnoDB: Using Linux native AIO
2020-08-17  8:45:13 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2020-08-17  8:45:13 0 [Note] InnoDB: Uses event mutexes
2020-08-17  8:45:13 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2020-08-17  8:45:13 0 [Note] InnoDB: Number of pools: 1
2020-08-17  8:45:13 0 [Note] InnoDB: Using SSE2 crc32 instructions
2020-08-17  8:45:13 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
2020-08-17  8:45:13 0 [Note] InnoDB: Completed initialization of buffer pool
2020-08-17  8:45:13 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2020-08-17  8:45:15 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2020-08-17  8:45:15 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2020-08-17  8:45:15 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2020-08-17  8:45:15 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2020-08-17  8:45:15 0 [Note] InnoDB: Waiting for purge to start
2020-08-17  8:45:15 0 [Note] InnoDB: 10.3.23 started; log sequence number 1625727; transaction id 21
2020-08-17  8:45:15 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2020-08-17  8:45:15 0 [Note] Plugin 'FEEDBACK' is disabled.
2020-08-17  8:45:15 0 [Note] InnoDB: Buffer pool(s) load completed at 200817  8:45:15
2020-08-17  8:45:15 0 [Note] Server socket created on IP: '::'.
2020-08-17  8:45:15 0 [Warning] 'proxies_priv' entry '@% root@e6fc8a59b059' ignored in --skip-name-resolve mode.
2020-08-17  8:45:15 0 [Note] Reading of all Master_info entries succeeded
2020-08-17  8:45:15 0 [Note] Added new Master_info '' to hash table
2020-08-17  8:45:15 0 [Note] mysqld: ready for connections.
Version: '10.3.23-MariaDB-1:10.3.23+maria~focal'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2020-08-17  8:49:48 8 [Warning] Access denied for user '_2703cf91f752a95d'@'172.21.0.11' (using password: YES)
2020-08-17  8:50:48 9 [Warning] Access denied for user '_2703cf91f752a95d'@'172.21.0.11' (using password: YES)
2020-08-17  8:51:48 10 [Warning] Access denied for user '_2703cf91f752a95d'@'172.21.0.11' (using password: YES)
```

I don't know much about the issue.
Maybe a problem with changing the encoding to utf8mb4 in the database?

I tried to change versions to 12, the problem repeats

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/issues/303#issuecomment-674910235
