### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/home/frappe/frappe-bench/logs/frappe.log'

### ISSUE THREAD

**Issue by zengxc-1996** [frappe/frappe_docker#452]
**Is your feature request related to a problem? Please describe.**
when I user docker-compose run this container;
docker logs erpnext-site-creator
```
Attempt 1 to connect to mariadb:3306
Attempt 2 to connect to mariadb:3306
Attempt 3 to connect to mariadb:3306
Attempt 1 to connect to redis-queue:6379
Attempt 1 to connect to redis-cache:6379
Attempt 1 to connect to redis-socketio:6379
Connections OK
Created user _76025c3c246ef900
Created database _76025c3c246ef900
Granted privileges to user _76025c3c246ef900 and database _76025c3c246ef900
Starting database import...
Imported from database /home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/framework_mariadb.sql

Installing frappe...
Updating DocTypes for frappe        : [========================================] 100%
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/commands/new.py", line 118, in <module>
    main()
  File "/home/frappe/frappe-bench/commands/new.py", line 70, in main
    db_port=db_port,
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 79, in _new_site
    install_app(app, verbose=verbose, set_as_patched=not source_sql)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 170, in install_app
    frappe.get_attr(after_install)()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/install.py", line 21, in after_install
    install_basic_docs()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/install.py", line 83, in install_basic_docs
    frappe.get_doc(d).insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 237, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 949, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 847, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1136, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1119, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 841, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_domain/email_domain.py", line 20, in validate
    logger = frappe.logger()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1625, in logger
    return get_logger(module=module, with_more_info=with_more_info, allow_site=allow_site, filter=filter, max_size=max_size, file_count=file_count)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/logger.py", line 61, in get_logger
    handler = RotatingFileHandler(log_filename, maxBytes=max_size, backupCount=file_count)
  File "/usr/local/lib/python3.7/logging/handlers.py", line 148, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/lib/python3.7/logging/handlers.py", line 55, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/home/frappe/frappe-bench/logs/frappe.log'
```
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by revant** [comment]
v13 is available, change the env variable for VERSION.

The error is not related to version tag not available. It is related to permission error for logs volume.

I can't figure out why that is happening.

**Comment by zengxc-1996** [comment]
Thanks for your help. I have solved this problem. The reason is that I mounted the data volume on the host machine, which caused the permission problem.
I regret that this will cause the data volume to default to root and run as a normal user inside the container.
But I still want to mount the data volume under /data instead of the default /var/lib/docker/volumes, I'm working on that...

**Comment by zengxc-1996** [comment]
As for why I want to do this, what I want is that when I run docker-compose down-v, the data volume will not be deleted.

**Comment by revant** [comment]
Use docker bind mount, instead of `sites-vol:...` use `/data:..` check this, https://0x0.st/-cVW.yml

Do not forget to `sudo chown -R 1000:1000 /data` before you do `docker-compose up`

> As for why I want to do this, what I want is that when I run docker-compose down-v, the data volume will not be deleted.

I don't think docker-compose down causes named volumes to be removed. check: https://docs.docker.com/compose/reference/down
