### ISSUE TITLE
pymysql.err.InternalError when running Single Bench docker installation

### ISSUE THREAD

**Issue by yalios** [frappe/frappe_docker#468]
I am getting the below error message when running the single bench docker installation. Any passwords supplied in .env file have special characters so I am not sure where the below mentioned scripts are getting the password. anyone has any ideas?

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/commands/new.py", line 118, in <module>
    main()
  File "/home/frappe/frappe-bench/commands/new.py", line 70, in main
    db_port=db_port,
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 87, in _new_site
    db_password=db_password, db_type=db_type, db_host=db_host, db_port=db_port, no_mariadb_socket=no_mariadb_socket)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 27, in install_db
    setup_database(force, source_sql, verbose, no_mariadb_socket)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/__init__.py", line 16, in setup_database
    return frappe.database.mariadb.setup_db.setup_database(force, source_sql, verbose, no_mariadb_socket=no_mariadb_socket)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/setup_db.py", line 47, in setup_database
    dbman.create_user(db_name, frappe.conf.db_password)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/db_manager.py", line 23, in create_user
    self.db.sql("CREATE USER '%s'@'%s' IDENTIFIED BY '%s';" % (user, host, password))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1819, 'Your password does not satisfy the current policy requirements: [Include special characters]')

**Comment by revant** [comment]
> Any passwords supplied in .env file have special characters

Try without special characters

**Comment by revant** [comment]
Related https://stackoverflow.com/questions/43495673/bash-export-environment-variables-with-special-characters
Re-open if necessary.

**Comment by yalios** [comment]
My database requires special characters on the passwords, is the only way to change the password requirements on the database server?

**Comment by revant** [comment]
Try to pass the special characters as environment variable.

> Related https://stackoverflow.com/questions/43495673/bash-export-environment-variables-with-special-characters

**Comment by yalios** [comment]
I saw that before, but isn't that something that needs to happen on one of the scripts? Will I be able to apply that workaround inside the .env file?
