### ISSUE TITLE
bench get-app fails for a required Python package

### ISSUE THREAD

**Issue by gdbaldw** [frappe/frappe_docker#473]
## Description of the issue

frappe_docker does not include `libpoppler-cpp-dev`

## Context information (for bug reports)

My custom app successfully installs into my docker development frappe-bench, without a necessary Python package, `pdftotext`. In researching, I found `pdftotext` requires `libpoppler-cpp-dev`.

I can work around the problem at the container command-line:
`sudo apt-get libpoppler-cpp-dev`

...but am unfamiliar with Docker, and how to include this in the container.

## Steps to reproduce the issue

1. Before installing `libpoppler` from the command-line, I made one change to my custom app, adding the line `pdftotext` to my `requirements.txt` file. Error message is below.

### Observed result

Installation fails.

### Expected result

Clean installation, as when `pdftotext` is not included in the `requirements.txt` file.

### Stacktrace / full error message if available

```
Installing my_app
$ ./env/bin/python -m pip install -q -U -e ./apps/my_app
  ERROR: Command errored out with exit status 1:
   command: /workspace/development/frappe-bench/env/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zmnqk_5o/pdftotext_e4e0b1985a3443acb9eb9d10185c767b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zmnqk_5o/pdftotext_e4e0b1985a3443acb9eb9d10185c767b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-y29oh8yj
       cwd: /tmp/pip-install-zmnqk_5o/pdftotext_e4e0b1985a3443acb9eb9d10185c767b/
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'pdftotext' extension
  creating build
  creating build/temp.linux-x86_64-3.7
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPOPPLER_CPP_AT_LEAST_0_30_0=0 -DPOPPLER_CPP_AT_LEAST_0_58_0=0 -I/usr/include/python3.7m -I/workspace/development/frappe-bench/env/include/python3.7m -c pdftotext.cpp -o build/temp.linux-x86_64-3.7/pdftotext.o -Wall
  pdftotext.cpp:3:10: fatal error: poppler/cpp/poppler-document.h: No such file or directory
   #include <poppler/cpp/poppler-document.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pdftotext
    ERROR: Command errored out with exit status 1:
     command: /workspace/development/frappe-bench/env/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zmnqk_5o/pdftotext_e4e0b1985a3443acb9eb9d10185c767b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zmnqk_5o/pdftotext_e4e0b1985a3443acb9eb9d10185c767b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-dh3l79ih/install-record.txt --single-version-externally-managed --compile --install-headers /workspace/development/frappe-bench/env/include/site/python3.7/pdftotext
         cwd: /tmp/pip-install-zmnqk_5o/pdftotext_e4e0b1985a3443acb9eb9d10185c767b/
    Complete output (12 lines):
    running install
    running build
    running build_ext
    building 'pdftotext' extension
    creating build
    creating build/temp.linux-x86_64-3.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPOPPLER_CPP_AT_LEAST_0_30_0=0 -DPOPPLER_CPP_AT_LEAST_0_58_0=0 -I/usr/include/python3.7m -I/workspace/development/frappe-bench/env/include/python3.7m -c pdftotext.cpp -o build/temp.linux-x86_64-3.7/pdftotext.o -Wall
    pdftotext.cpp:3:10: fatal error: poppler/cpp/poppler-document.h: No such file or directory
     #include <poppler/cpp/poppler-document.h>
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /workspace/development/frappe-bench/env/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zmnqk_5o/pdftotext_e4e0b1985a3443acb9eb9d10185c767b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zmnqk_5o/pdftotext_e4e0b1985a3443acb9eb9d10185c767b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-dh3l79ih/install-record.txt --single-version-externally-managed --compile --install-headers /workspace/development/frappe-bench/env/include/site/python3.7/pdftotext Check the logs for full command output.
$ bench build --app my_app
WARN: bench is installed in editable mode!

This is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 101, in <module>
    main()
  File "/workspace/development/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/commands/utils.py", line 26, in build
    frappe.init('')
  File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 209, in init
    setup_module_map()
  File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 1116, in setup_module_map
    for module in get_module_list(app):
  File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 982, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 940, in get_module
    return importlib.import_module(modulename)
  File "/workspace/development/frappe-bench/env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'my_app'
```

**Comment by revant** [comment]
You should build your own custom production image

https://discuss.erpnext.com/t/could-not-install-boilerplate-app-to-site/75335/2

In that image add additional Deb dependencies. Then use the custom image during installation.
