### ISSUE TITLE
Internal Server Error: favicon

### ISSUE THREAD

**Issue by Jonaswinz** [frappe/frappe_docker#478]
I want to install erpNext behind a nginx reverse proxy. But after the installation I only get "Internal Server Error".
 
LOGS:
(erpnext_erpnext-python_1):
```
Attempt 1 to connect to mariadb:3306
Attempt 1 to connect to redis-queue:6379
Attempt 1 to connect to redis-cache:6379
Attempt 1 to connect to redis-socketio:6379
Connections OK
[2021-05-21 19:44:47 +0000] [18] [INFO] Starting gunicorn 20.1.0
[2021-05-21 19:44:47 +0000] [18] [INFO] Listening at: http://0.0.0.0:8000 (18)
[2021-05-21 19:44:47 +0000] [18] [INFO] Using worker: gthread
[2021-05-21 19:44:47 +0000] [21] [INFO] Booting worker with pid: 21
[2021-05-21 19:44:47 +0000] [22] [INFO] Booting worker with pid: 22
b'Traceback (most recent call last):\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 77, in application\n    response = frappe.website.render.render()\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 41, in render\n    data = render_page(\'404\')\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 194, in render_page\n    return build(path)\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 201, in build\n    return build_page(path)\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 224, in build_page\n    html = frappe.get_template(context.template).render(context)\n  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render\n    self.environment.handle_exception()\n  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception\n    reraise(*rewrite_traceback_stack(source=source))\n  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise\n    raise value.with_traceback(tb)\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/./www/404.html", line 1, in top-level template code\n    {% extends "templates/web.html" %}\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/web.html", line 1, in top-level template code\n    {% extends base_template_path %}\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 25, in top-level template code\n    {%- block head -%}\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 33, in block "head"\n    {{ include_style(\'website.bundle.css\') }}\n  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call\n    return __context.call(__obj, *args, **kwargs)\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja_globals.py", line 78, in include_style\n    path = bundled_asset(path)\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja_globals.py", line 88, in bundled_asset\n    path = bundled_assets.get(path) or path\nAttributeError: \'NoneType\' object has no attribute \'get\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 49, in render\n    data = render_page_by_language(path)\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 178, in render_page_by_language\n    return render_page(path)\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 194, in render_page\n    return build(path)\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 201, in build\n    return build_page(path)\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 224, in build_page\n    html = frappe.get_template(context.template).render(context)\n  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render\n    self.environment.handle_exception()\n  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception\n    reraise(*rewrite_traceback_stack(source=source))\n  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise\n    raise value.with_traceback(tb)\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/./www/message.html", line 1, in top-level template code\n    {% extends "templates/web.html" %}\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/web.html", line 1, in top-level template code\n    {% extends base_template_path %}\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 25, in top-level template code\n    {%- block head -%}\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 33, in block "head"\n    {{ include_style(\'website.bundle.css\') }}\n  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call\n    return __context.call(__obj, *args, **kwargs)\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja_globals.py", line 78, in include_style\n    path = bundled_asset(path)\n  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja_globals.py", line 88, in bundled_asset\n    path = bundled_assets.get(path) or path\nAttributeError: \'NoneType\' object has no attribute \'get\'\n'
[2021-05-21 19:46:31 +0000] [22] [ERROR] Error handling request /favicon.ico
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 77, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 41, in render
    data = render_page('404')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 194, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 201, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 224, in build_page
    html = frappe.get_template(context.template).render(context)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./www/404.html", line 1, in top-level template code
    {% extends "templates/web.html" %}
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/web.html", line 1, in top-level template code
    {% extends base_template_path %}
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 25, in top-level template code
    {%- block head -%}
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 33, in block "head"
    {{ include_style('website.bundle.css') }}
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja_globals.py", line 78, in include_style
    path = bundled_asset(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja_globals.py", line 88, in bundled_asset
    path = bundled_assets.get(path) or path
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 49, in render
    data = render_page_by_language(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 178, in render_page_by_language
    return render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 194, in render_pag
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 201, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 224, in build_page
    html = frappe.get_template(context.template).render(context)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./www/message.html", line 1, in top-level template code
    {% extends "templates/web.html" %}
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/web.html", line 1, in top-level template code
    {% extends base_template_path %}
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 25, in top-level template code
    {%- block head -%}
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 33, in block "head"
    {{ include_style('website.bundle.css') }}
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja_globals.py", line 78, in include_style
    path = bundled_asset(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja_globals.py", line 88, in bundled_asset
    path = bundled_assets.get(path) or path
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 323, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 231, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/wrappers/base_request.py", line 237, in application
    resp = f(*args[:-2] + (request,))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 89, in application
    response = handle_exception(e)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 271, in handle_exception
    http_status_code=http_status_code)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 79, in render
    data = render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 194, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 201, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 224, in build_page
    html = frappe.get_template(context.template).render(context)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./www/error.html", line 1, in top-level template code
    {% extends "templates/web.html" %}
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/web.html", line 1, in top-level template code
    {% extends base_template_path %}
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 25, in top-level template code
    {%- block head -%}
  File "/home/frappe/frappe-bench/apps/frappe/frappe/./templates/base.html", line 33, in block "head"
    {{ include_style('website.bundle.css') }}
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja_globals.py", line 78, in include_style
    path = bundled_asset(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja_globals.py", line 88, in bundled_asset
    path = bundled_assets.get(path) or path
AttributeError: 'NoneType' object has no attribute 'get'
```

(erpnext_mariadb_1):
```
2021-05-21 19:44:56 109 [Warning] Access denied for user 'frappe'@'172.20.0.19' (using password: NO)
2021-05-21 19:44:57 110 [Warning] Access denied for user 'frappe'@'172.20.0.21' (using password: NO)
2021-05-21 19:44:57 111 [Warning] Access denied for user 'frappe'@'172.20.0.21' (using password: NO)
2021-05-21 19:44:57 112 [Warning] Access denied for user 'frappe'@'172.20.0.21' (using password: NO)
2021-05-21 19:44:57 113 [Warning] Access denied for user 'frappe'@'172.20.0.21' (using password: NO)
2021-05-21 19:44:57 114 [Warning] Access denied for user 'frappe'@'172.20.0.21' (using password: NO)
2021-05-21 19:44:57 115 [Warning] Access denied for user 'frappe'@'172.20.0.21' (using password: NO)
2021-05-21 19:44:57 116 [Warning] Access denied for user 'frappe'@'172.20.0.21' (using password: NO)
```

All other logs look normal.
My docker compose file:

version: "3"

```
services:
  #traefik:
  #  image: "traefik:v2.2"
  #  command:
  #    - "--log.level=DEBUG"
  #    - "--providers.docker=true"
  #    - "--providers.docker.exposedbydefault=false"
  #    - "--entrypoints.web.address=:80"
  #    - "--entrypoints.websecure.address=:443"
  #    - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
  #    - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
  #    - "--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}"
  #    - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
  #  labels:
  #    # enable traefik
  #    - "traefik.enable=true"
  #    # global redirect to https for production only
  #    - "${HTTPS_REDIRECT_RULE_LABEL}"
  #    - "${HTTPS_REDIRECT_ENTRYPOINT_LABEL}"
  #    - "${HTTPS_REDIRECT_MIDDLEWARE_LABEL}"
  #    # middleware redirect for production only
  #    - "${HTTPS_USE_REDIRECT_MIDDLEWARE_LABEL}"
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  volumes:
  #    - cert-vol:/letsencrypt
  #    - /var/run/docker.sock:/var/run/docker.sock:ro
  #  userns_mode: "host

  erpnext-nginx:
    image: frappe/erpnext-nginx:${ERPNEXT_VERSION}
    restart: on-failure
    environment:
      - FRAPPE_PY=erpnext-python
      - FRAPPE_PY_PORT=8000
      - FRAPPE_SOCKETIO=frappe-socketio
      - SOCKETIO_PORT=9000
      - SKIP_NGINX_TEMPLATE_GENERATION=${SKIP_NGINX_TEMPLATE_GENERATION}
    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.erpnext-nginx.rule=Host(${SITES})"
      - "${ENTRYPOINT_LABEL}"
#     - "${CERT_RESOLVER_LABEL}"
#      - "traefik.http.services.erpnext-nginx.loadbalancer.server.port=80"
    volumes:
      - sites-vol:/var/www/html/sites:rw
      - assets-vol:/assets:rw

  erpnext-python:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: on-failure
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - REDIS_CACHE=redis-cache:6379
      - REDIS_QUEUE=redis-queue:6379
      - REDIS_SOCKETIO=redis-socketio:6379
      - SOCKETIO_PORT=9000
      - AUTO_MIGRATE=1
      - WORKER_CLASS=${WORKER_CLASS}
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - assets-vol:/home/frappe/frappe-bench/sites/assets:rw

  frappe-socketio:
    image: frappe/frappe-socketio:${FRAPPE_VERSION}
    restart: on-failure
    depends_on:
      - redis-socketio
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

  erpnext-worker-default:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: on-failure
    command: worker
    depends_on:
      - redis-queue
      - redis-cache
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

  erpnext-worker-short:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: on-failure
    command: worker
    environment:
      - WORKER_TYPE=short
    depends_on:
      - redis-queue
      - redis-cache
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

  erpnext-worker-long:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: on-failure
    command: worker
    environment:
      - WORKER_TYPE=long
    depends_on:
      - redis-queue
      - redis-cache
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw

  erpnext-schedule:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: on-failure
    command: schedule
    depends_on:
      - redis-queue
      - redis-cache
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

  redis-cache:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-cache-vol:/data

  redis-queue:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-queue-vol:/data

  redis-socketio:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-socketio-vol:/data

  mariadb:
    image: mariadb:10.3
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./frappe-mariadb.cnf:/etc/mysql/conf.d/frappe.cnf
      - mariadb-vol:/var/lib/mysql

  site-creator:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: "no"
    command: new
    depends_on:
      - erpnext-python
    environment:
      - SITE_NAME=${SITE_NAME}
      - DB_ROOT_USER=${DB_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - INSTALL_APPS=${INSTALL_APPS}
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

volumes:
  mariadb-vol:
  redis-cache-vol:
  redis-queue-vol:
  redis-socketio-vol:
  assets-vol:
  sites-vol:
  cert-vol:
  logs-vol:

networks:
  default:
    external:
       name: proxy_default

```

And finally my reverse proxy (nginx) config:
```
server {
      listen        443 ssl;
      server_name   erp.<domain>;

      if ($host ~* ^www\.(.*)) {
        set $host_without_www $1;
        rewrite ^(.*) https://$host_without_www$1 permanent;
      }

      client_max_body_size  64M;

      ssl_certificate /etc/ssl/private/fullchain.pem;
      ssl_certificate_key /etc/ssl/private/privkey.pem;

    location / {

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Frappe-Site-Name erp.bitbot.eu;
        proxy_pass_request_headers on;
        proxy_redirect off;

        proxy_pass  http://erpnext_erpnext-nginx_1:80;
     }
}
```

Am I missing something ? I would appreciate some help.

**Comment by revant** [comment]
Can you try with latest develop images or try with v13 images?

> AttributeError: 'NoneType' object has no attribute 'get'

I faced this recently on latest then for fixed in daily build.

**Comment by Jonaswinz** [comment]
Stupid simple problem: I did not wait until the erpnext site was successfully installed (site creator finished).
