### ISSUE TITLE
pymysql.err.ProgrammingError pymysql.err.ProgrammingError: ('DocType', 'Portal Menu Item')

### ISSUE THREAD

**Issue by bkzarok** [frappe/frappe_docker#506]
## Description of the issue
I'm getting this issue when I stall erpnext site and try to run the site after following all the steps

## Context information (for bug reports)
none
## Steps to reproduce the issue
none
1.
2.
3.

### Stacktrace / full error message if available

```
(paste here)
```

**Comment by revant** [comment]
Yes try and share output.

I can't help much. I don't get this issue.

**Comment by bkzarok** [comment]
this is the out on mysite.localhost:8000 on my browser 

pymysql.err.ProgrammingError
pymysql.err.ProgrammingError: ('DocType', 'Portal Menu Item')

Traceback (most recent call last)
File "/workspace/development/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
init_request(request)
File "/workspace/development/frappe-bench/apps/frappe/frappe/app.py", line 118, in init_request
raise frappe.SessionStopped('Session Stopped')
During handling of the above exception, another exception occurred:
File "/workspace/development/frappe-bench/apps/frappe/frappe/middlewares.py", line 16, in __call__
return super(StaticDataMiddleware, self).__call__(environ, start_response)
File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
return self.app(environ, start_response)
File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
return self.app(environ, start_response)
File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 231, in application
return ClosingIterator(app(environ, start_response), self.cleanup)
File "/workspace/development/frappe-bench/env/lib/python3.7/site-packages/werkzeug/wrappers/base_request.py", line 237, in application
resp = f(*args[:-2] + (request,))
File "/workspace/development/frappe-bench/apps/frappe/frappe/app.py", line 85, in application
response = frappe.utils.response.handle_session_stopped()
File "/workspace/development/frappe-bench/apps/frappe/frappe/utils/response.py", line 223, in handle_session_stopped
return frappe.website.render.render("message", http_status_code=503)
File "/workspace/development/frappe-bench/apps/frappe/frappe/website/render.py", line 35, in render
raise_if_disabled(path)
File "/workspace/development/frappe-bench/apps/frappe/frappe/website/render.py", line 372, in raise_if_disabled
'route': ['like', '%{0}'.format(path)]
File "/workspace/development/frappe-bench/apps/frappe/frappe/database/database.py", line 528, in get_all
return frappe.get_all(*args, **kwargs)
File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 1338, in get_all
return get_list(doctype, *args, **kwargs)
File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 1311, in get_list
return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
File "/workspace/development/frappe-bench/apps/frappe/frappe/model/db_query.py", line 96, in execute
result = self.build_and_run()
File "/workspace/development/frappe-bench/apps/frappe/frappe/model/db_query.py", line 110, in build_and_run
args = self.prepare_args()
File "/workspace/development/frappe-bench/apps/frappe/frappe/model/db_query.py", line 136, in prepare_args
self.set_optional_columns()
File "/workspace/development/frappe-bench/apps/frappe/frappe/model/db_query.py", line 302, in set_optional_columns
Open an interactive python shell in this framecolumns = get_table_columns(self.doctype)
File "/workspace/development/frappe-bench/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
return frappe.db.get_table_columns(doctype)
File "/workspace/development/frappe-bench/apps/frappe/frappe/database/database.py", line 865, in get_table_columns
raise self.TableMissingError('DocType', doctype)
pymysql.err.ProgrammingError: ('DocType', 'Portal Menu Item')

**Comment by revant** [comment]
I'm not getting this error on fresh site I created just now to test.

http://ip172-18-0-74-c45ulinnjsv000c8rgfg-80.direct.labs.play-with-docker.com/ (will be removed in few minutes)
user: Administrator, pass: admin

**Comment by bkzarok** [comment]
ok I will reinstall it thanks I will keep u updated note I'm following the developer setup instructions https://github.com/frappe/frappe_docker/tree/develop/development  using vscode container

**Comment by revant** [comment]
then you don't need to reinstall everything.

Just recreate the site.

If it is windows/mac. allocate appropriate RAM for Docker

**Comment by bkzarok** [comment]
Thank you that works problem solved I had to disable using docker wsl 2 and instead use hyper v backend, then I reinstall everything just as a precaution then after that it works 
![image](https://user-images.githubusercontent.com/12804696/128505062-26842111-c9da-45d4-969f-231ee6a891fc.png)
