### ISSUE TITLE
No module named 'erpnext' using bench commands

### ISSUE THREAD

**Issue by FiloSpaTeam** [frappe/frappe_docker#516]
## Description of the issue
Simply run `docker run -v erp_sites-vol:/home/frappe/frappe-bench/sites --network erp_default --user frappe frappe/frappe-worker:version-13 bench version`.
I'm expecting the version of installed apps. Actually al works. I would like to install custom app.

## Steps to reproduce the issue

1. docker run -v erp_sites-vol:/home/frappe/frappe-bench/sites --network erp_default --user frappe frappe/frappe-worker:version-13 bench version

### Observed result
```bash
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/utils.py", line 762, in get_version
    frappe.init("")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 212, in init
    setup_module_map()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1118, in setup_module_map
    for module in get_module_list(app):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 986, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 944, in get_module
    return importlib.import_module(modulename)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 18, in <module>
    [sys.executable, bench_helper, 'frappe'] + sys.argv[1:],
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/frappe/frappe-bench/env/bin/python', '/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py', 'frappe', 'version']' returned non-zero exit status 1.
```

### Expected result
List of apps version

**Comment by revant** [comment]
> frappe/frappe-worker:version-13

you won't find ERPNext in Frappe worker image

use erpnext-worker
