### ISSUE TITLE
./dbench init returns error Missing argument "PATH"

### ISSUE THREAD

**Issue by pleasxplain** [frappe/frappe_docker#54]
Hi,

Followed steps for installing erpnext docker image from:
https://github.com/frappe/frappe_docker

Working up to step copied below:

1. First time setup

./dbench init

returns following:

Usage: bench init [OPTIONS] PATH
Try "bench init --help" for help.

Error: Missing argument "PATH".
mv: cannot stat 'Procfile_docker': No such file or directory

Have tried setting paths but no luck. Any suggestions?

Thanks,

**Comment by Thunderbottom** [comment]
actually there is another issue caused by a previous commit. I will fix it asap.

**Comment by pleasxplain** [comment]
Thanks for quick reply,

Using the step ./dbench init frappe-bench works successfully. However, on the next step following the instructions it returns the following error when run from the :

./dbench setup hosts
ls: cannot access 'sites/*/site_config.json': No such file or directory
127.0.0.1
127.0.0.1

the normal bench commands now seem to work OK, but I am not able to access anything on 127.0.0.0:8000 or any other addresses. 

docker ps shows the status as up? But I am unable to access frappe?

docker ps
1e8bafa6d36b        frappe_docker_frappe   "/bin/bash"              29 minutes ago      Up 29 minutes       0.0.0.0:6787->6787/tcp, 0.0.0.0:8000->8000/tcp, 0.0.0.0:9000->9000/tcp   frappe
24972186a4d9        mariadb                "docker-entrypoint.s…"   29 minutes ago      Up 29 minutes       0.0.0.0:3307->3306/tcp                                                   mariadb
e8f690b5889a        redis:alpine           "docker-entrypoint.s…"   29 minutes ago      Up 29 minutes       6379/tcp                                                                 redis-queue
c04f0e7bb7ce        redis:alpine           "docker-entrypoint.s…"   29 minutes ago      Up 29 minutes       6379/tcp                                                                 redis-socketio
0344fea10435        redis:alpine           "docker-entrypoint.s…"   29 minutes ago      Up 29 minutes       6379/tcp                                                                 redis-cache

Please let me know if there is anything I am missing?

Thanks

**Comment by pleasxplain** [comment]
Hi,

All working, needed to just follow normal erpnext steps.

I will delete the build and rebuild noting all the steps and post in case anyone else has the same problem. Thanks again for the quick reply.

Regards,

**Comment by pleasxplain** [comment]
Hi,

Almost working! Can see erpNEXT screen then it fails. 
Steps I followed are below:
Re-installation of frappe and erpnext on docker
1. Test if any old instances exist or are running:
$docker ps
if frappe/erpnext docker processes running need to stop them using:
$docker stop pid1 pid2 pid3 etc
Now remove these so we can have a clean installation (only needed if in test mode)
$docker rm pid1 pid2 pid3 etc
From the official erpnext docker site do following steps:
link is here to website: https://github.com/frappe/frappe_docker
cd to home directory for user, in my case: $HOME
1. Remove the old installation directories:
sudo rm -r frappe_docker
Now install clean files:
1. 	git clone --depth 1 https://github.com/frappe/frappe_docker.git
2. 	cd frappe_docker
3. 	./dbench setup docker
4. 	./dbench init frappe-bench
5.	./dbench setup hosts
6. 	./dbench new-site site1.local
7.  	./dbench get-app erpnext https://github.com/frappe/erpnext
8. 	./dbench --site site1.local install-app erpnext
9.	./dbench start

Go to browser and open localhost:8000
Can then run erpNEXT. However, it gets to company configuration and in my case exits with message:
"Setup failed
Could not start up: Error in setup"

On console screen it has following messages:

05:52:34 web.1            |  * Detected change in '/home/frappe/frappe-bench/apps/erpnext/erpnext/domains/distribution.pyc', reloading
05:52:34 web.1            | INFO:werkzeug: * Detected change in '/home/frappe/frappe-bench/apps/erpnext/erpnext/domains/distribution.pyc', reloading
05:52:34 web.1            |  * Detected change in '/home/frappe/frappe-bench/apps/erpnext/erpnext/domains/distribution.pyc', reloading
05:52:34 web.1            | INFO:werkzeug: * Detected change in '/home/frappe/frappe-bench/apps/erpnext/erpnext/domains/distribution.pyc', reloading
05:52:35 web.1            | ----------------------------------------
05:52:35 web.1            | Exception happened during processing of request from ('192.168.1.4', 42590)
05:52:35 web.1            | Exception in thread Thread-20 (most likely raised during interpreter shutdown):
05:52:35 web.1            | Traceback (most recent call last):
05:52:35 web.1            |   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
05:52:35 web.1            |   File "/usr/lib/python2.7/threading.py", line 754, in run
05:52:35 web.1            |   File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
05:52:35 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 621, in handle_error
05:52:35 web.1            |   File "/usr/lib/python2.7/SocketServer.py", line 350, in handle_error
05:52:35 web.1            | <type 'exceptions.ImportError'>: No module named traceback
05:52:35 web.1            |  * Restarting with inotify reloader
05:52:36 web.1            |  * Debugger is active!
05:52:36 web.1            |  * Debugger PIN: 724-973-074

Any help much appreciated!

**Comment by Thunderbottom** [comment]
okay glad to know that your issues are _mostly_ fixed. secondly, now you do not need to do `bench init <bench-name>`, just `bench init` will suffice.

thirdly, I'm unsure of whether the problem you're facing now is related to docker by any means because I cannot see any tracebacks (I'm also unsure of why you do not have the `traceback` module, which is supposed to be packaged with python).

I can try running the setup in a while on my instance just to try and reproduce this error. Thanks for reporting.

**Comment by pleasxplain** [comment]
Hi,

Just re-ran these steps minus the bench init <bench-name> and it works. However, there are no erpnext modules available. In the setup it did not ask for type of industry? I have access to email, tools and explore only?

Regards

**Comment by Thunderbottom** [comment]
I'm sorry for not getting back to you before. I tried running it on my local instance, and ERPnext works just fine. Can you try running an entirely new instance?

**Comment by pleasxplain** [comment]
Hi

All working!!

Stopped the container then completed following:

./dbench switch-to-branch master
./dbench update --patch
./dbench start

Now everything is working, thanks again for your assistance and this great program.

**Comment by Thunderbottom** [comment]
sweet! glad that you got it all working!
