### ISSUE TITLE
Helm Release Fails

### ISSUE THREAD

**Issue by revant** [frappe/frappe_docker#562]
https://github.com/frappe/frappe_docker/runs/4167916296?check_suite_focus=true

```
  with:
    global: true
    email: github-action@users.noreply.github.com
    name: GitHub Action
    actor: GITHUB_ACTOR
  env:
    IS_AUTHORIZED_RUN: true
    SSH_AUTH_SOCK: /tmp/ssh-HBRa8URBHE8W/agent.1449
    SSH_AGENT_PID: 1450
Started: bash /home/runner/work/_actions/oleksiyrudenko/gha-git-credentials/v2-latest/dist/action.sh
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/oleksiyrudenko/gha-git-credentials/v2-latest/dist/index.js:57:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/oleksiyrudenko/gha-git-credentials/v2-latest/dist/index.js:57:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

Temporary workaround: change the tag(s) manually in `values`

**Comment by revant** [comment]
#563

**Comment by revant** [comment]
:frowning_face: 

https://github.com/frappe/frappe_docker/runs/4172419229?check_suite_focus=true

```
0s
Run fregante/setup-git-user@v1
  env:
    IS_AUTHORIZED_RUN: true
    SSH_AUTH_SOCK: /tmp/ssh-mvcHBGM7KIUJ/agent.1470
    SSH_AGENT_PID: 1471
/home/runner/work/_actions/fregante/setup-git-user/v1/index.js:9
		throw error;
		^

[Error: ENOENT: no such file or directory, open '.git/config'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '.git/config'
}
```
