### ISSUE TITLE
Error occurred when sending email of a sales order with PDF print format setting

### ISSUE THREAD

**Issue by a157147899** [frappe/frappe_docker#589]
## Description of the issue
I'm running ERPNext on my Mac Docker Desktop and having an issue where it cannot email a sales order in PDF print format. From the error log, it seems the problem is related to the package "wkhtmltopdf". Tried to find a solution in the forum but all the answers just point the cause to the incorrect installation/version of "wkhtmltopdf", but I believe that is not my case.

I tested "wkhtmltopdf" command in the docker container(erpnext-worker-default_1) to manually convert an html file into a pdf file for testing, and that worked without any issues.
![image](https://user-images.githubusercontent.com/1812136/143733168-46aa53d4-c93d-4141-a03f-b7f886350298.png)

## Context information (for bug reports)
macOS Monterey

Docker Desktop 4.2.0 (70708)

bench version
erpnext 13.x.x-develop
frappe 14.x.x-develop

wkhtmltopdf --version
wkhtmltopdf 0.12.6 (with patched qt)

## Steps to reproduce the issue

1. setup a Gmail email account
2. create a simple sales order
3. email it

### Stacktrace / full error message if available
stacktrach from the error log
```
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 123, in send
    message = ctx.build_message(recipient.recipient)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 240, in build_message
    message = self.include_attachments(message)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 300, in include_attachments
    print_format_file = frappe.attach_print(**attachment)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1588, in attach_print
    content = get_print(doctype, name, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1554, in get_print
    return get_pdf(html, options=pdf_options, output=output)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/pdf.py", line 37, in get_pdf
    filedata = pdfkit.from_string(html, False, options=options or {})
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/pdfkit/api.py", line 72, in from_string
    return r.to_pdf(output_path)
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/pdfkit/pdfkit.py", line 156, in to_pdf
    raise IOError('wkhtmltopdf reported an error:\n' + stderr)

 Queue Name: 573d7378a8
```

**Comment by revant** [comment]
check the `frappe-bench/logs` for more info on what failed for the command

**Comment by a157147899** [comment]
> 

tried to search for errors in all the log files but didn't get any luck.

**Comment by a157147899** [comment]
> check the `frappe-bench/logs` for more info on what failed for the command

Hi Revant, any ideas? Not sure if you can test it out in Docker Desktop.

**Comment by a157147899** [comment]
@revant sorry, I was in the wrong docker container. Below is the error detail

```
2021-11-29 03:47:37,088 ERROR frappe Could not take error snapshot: characters_written
Site: mysite.localhost
Form Dict: {'name': 'SAL-ORD-2021-00001', 'cmd': 'frappe.email.doctype.email_queue.email_queue.send_now', 'doctype': 'Sales Order', 'format': 'Standard', 'style': None, 'doc': None, 'no_letterhead': False}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1213, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 320, in send_now
    record.send()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 123, in send
    message = ctx.build_message(recipient.recipient)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 240, in build_message
    message = self.include_attachments(message)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 300, in include_attachments
    print_format_file = frappe.attach_print(**attachment)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1588, in attach_print
    content = get_print(doctype, name, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1554, in get_print
    return get_pdf(html, options=pdf_options, output=output)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/pdf.py", line 37, in get_pdf
    filedata = pdfkit.from_string(html, False, options=options or {})
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/pdfkit/api.py", line 72, in from_string
    return r.to_pdf(output_path)
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/pdfkit/pdfkit.py", line 156, in to_pdf
    raise IOError('wkhtmltopdf reported an error:\n' + stderr)
OSError: wkhtmltopdf reported an error:
Exit with code 1 due to network error: ConnectionRefusedError


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 127, in get_snapshot
    value = pydoc.text.repr(getattr(evalue, name))
AttributeError: characters_written
```

**Comment by revant** [comment]
is any of your image results into 404?

https://stackoverflow.com/questions/57991848/wkhtmltopdf-exit-with-code-1-due-to-network-error-contentnotfounderror

**Comment by a157147899** [comment]
@revant Thanks for the hint. I managed to reproduce the issue which was caused by a CSS link in the HTML code of the sales order. 

The problem is that the host "http://mysite.localhost" is not accessible in the docker container but can be accessed from the browser.

I feel like it might need to add some network settings to the docker-compose.yml, but I am just not familiar with that.

added the CSS link to the 'test.html' and tested it
![image](https://user-images.githubusercontent.com/1812136/144024647-d39553b3-116d-4320-b82f-5f43888dbef9.png)

curl the link also got the same error
![image](https://user-images.githubusercontent.com/1812136/144026014-78233fd2-02ca-4539-aa48-dc2edaf1c838.png)

can access the link from browser
![image](https://user-images.githubusercontent.com/1812136/144026177-8fbfd515-e6bb-43e6-b896-eaf9cfd5bd7e.png)

**Comment by revant** [comment]
all containers can have a section for `extra_hosts:`


```yaml
  erpnext-worker-default:
    ...
    extra_hosts:
      mysite.localhost: 172.17.0.1
...
```

you can add any hosts in `extra_hosts`, they'll land up in `/etc/hosts` inside container

**Comment by a157147899** [comment]
@revant  thanks for your help. Finally solved the issue by adding a host entry.

Also, I am wondering that if there is a particular reason for not adding this host mapping in docker-compose.yml by default. I've noticed that the site name is already defined in .env file, so I guess everyone will encounter the same issue regardless of using Docker Desktop or native docker, correct?

**Comment by revant** [comment]
`mysite.localhost` is simple local way to access and check erpnext on a machine. Frappe/ERPNext is ideally meant to be deployed as a web app under a https domain name. Everything is geared towards production setup.

The *.localhost sites are used to check app features locally or during local development. During development the `.devcontainer` directory is gitignored, and it can have a complex configuration with custom docker-compose.yml based on devcontainer-example.
