### ISSUE TITLE
Bench init frappe version-12 Failed

### ISSUE THREAD

**Issue by FHenry** [frappe/frappe_docker#611]
```
/workspace/development$ bench init --skip-redis-config-generation --frappe-branch version-12 frappe-bench
$ /home/frappe/.local/bin/virtualenv --quiet env -p python3
$ /workspace/development/frappe-bench/env/bin/python -m pip install --quiet --upgrade pip
Getting frappe
$ git clone https://github.com/frappe/frappe.git --branch version-12 --depth 1 --origin upstream
Cloning into 'frappe'...
remote: Enumerating objects: 2663, done.
remote: Counting objects: 100% (2663/2663), done.
remote: Compressing objects: 100% (2463/2463), done.
remote: Total 2663 (delta 348), reused 1127 (delta 150), pack-reused 0
Receiving objects: 100% (2663/2663), 12.43 MiB | 1.91 MiB/s, done.
Resolving deltas: 100% (348/348), done.
Installing frappe
$ /workspace/development/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /workspace/development/frappe-bench/apps/frappe 
$ yarn install
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.3.1" has unmet peer dependency "popper.js@^1.14.7".
[4/4] Building fresh packages...
[1/2] ⠈ cypress
error /workspace/development/frappe-bench/apps/frappe/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /workspace/development/frappe-bench/apps/frappe/node_modules/node-sass
Output:
Building: /home/frappe/.nvm/versions/node/v14.18.1/bin/node /workspace/development/frappe-bench/apps/frappe/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/home/frappe/.nvm/versions/node/v14.18.1/bin/node',
gyp verb cli   '/workspace/development/frappe-bench/apps/frappe/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.18.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/workspace/development/frappe-bench/apps/frappe/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/workspace/development/frappe-bench/apps/frappe/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/workspace/development/frappe-bench/apps/frappe/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /workspace/development/frappe-bench/apps/frappe/node_modules/which/which.js:89:16
gyp verb `which` failed     at /workspace/development/frappe-bench/apps/frappe/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /workspace/development/frappe-bench/apps/frappe/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:191:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/workspace/development/frappe-bench/apps/frappe/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/workspace/development/frappe-bench/apps/frappe/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/workspace/development/frappe-bench/apps/frappe/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /workspace/development/frappe-bench/apps/frappe/node_modules/which/which.js:89:16
gyp verb `which` failed     at /workspace/development/frappe-bench/apps/frappe/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /workspace/development/frappe-bench/apps/frappe/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:191:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /home/frappe/.pyenv/shims/python
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /home/frappe/.pyenv/shims/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:383:12)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
gyp ERR! System Linux 5.11.0-41-generic
gyp ERR! command "/home/frappe/.nvm/versions/node/v14.18.1/bin/node" "/workspace/development/frappe-bench/apps/frappe/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /workspace/development/frappe-bench/apps/frappe/node_modules/node-sass
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1

Traceback (most recent call last):
  File "/home/frappe/.bench/bench/commands/make.py", line 70, in init
    init(
  File "/home/frappe/.bench/bench/utils/render.py", line 95, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.bench/bench/utils/system.py", line 78, in init
    get_app(
  File "/home/frappe/.bench/bench/app.py", line 357, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets)
  File "/home/frappe/.bench/bench/utils/render.py", line 110, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.bench/bench/app.py", line 188, in install
    install_app(
  File "/home/frappe/.bench/bench/app.py", line 414, in install_app
    bench.run("yarn install", cwd=app_path)
  File "/home/frappe/.bench/bench/bench.py", line 43, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd)
  File "/home/frappe/.bench/bench/utils/__init__.py", line 126, in exec_cmd
    raise CommandFailedError
bench.exceptions.CommandFailedError

ERROR: There was a problem while creating frappe-bench
Do you want to rollback these changes? [y/N]: ^CAborted!

```

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/tree/main/development#setup-first-bench

note is added for v12:

> Note: For version 12 use python 3.7 by passing option to bench init command, e.g. `bench init --skip-redis-config-generation --frappe-branch version-12 --python python3.7 frappe-bench`

**Comment by revant** [comment]
@FHenry make sure you've latest bench image.

@vrslev do we need python2 to build something with node-gyp?

**Comment by FHenry** [comment]
@revant  Yes I confirm docker pull image this morning. 
I just try with 
`bench init --skip-redis-config-generation --frappe-branch version-12 --python python3.7 frappe-bench`
same error message

**Comment by FHenry** [comment]
@vrslev 
`frappe@a0af32fc3e32:/workspace/development$ sudo apt-get update`
`frappe@a0af32fc3e32:/workspace/development$ sudo apt-get install python`
`
frappe@a0af32fc3e32:/workspace/development$ bench init --skip-redis-config-generation --frappe-branch version-12 --python python3.7 frappe-bench`

It works.
Thanks

**Comment by FHenry** [comment]
Should I close the issue?

**Comment by vrslev** [comment]
No. I will send the PR that fixes this.
