### ISSUE TITLE
issue with single bench

### ISSUE THREAD

**Issue by neil-abkd** [frappe/frappe_docker#638]
## Description of the issue
mariadb is not capturing the password from the .env file

## Steps to reproduce the issue

1. fresh ubuntu and docker install
2. clone github and copy env-production to .env
3. docker-compose

### Observed result
internal server error and/or error 404
### Expected result
erpnext login page
### Stacktrace / full error message if available

```
mariadb_1                 | 2022-01-17 18:31:58 9 [Warning] Access denied for user '_a6baca2e68f9be45'@'172.20.0.6' (using password: YES)
mariadb_1                 | 2022-01-17 18:31:58 10 [Warning] Access denied for user '_a6baca2e68f9be45'@'172.20.0.6' (using password: YES)
erpnext-python_1          | [2022-01-17 18:31:58 +0000] [20] [ERROR] Error handling request /
erpnext-python_1          | Traceback (most recent call last):
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
erpnext-python_1          |     init_request(request)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 125, in init_request
erpnext-python_1          |     frappe.local.http_request = frappe.auth.HTTPRequest()
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 34, in __init__
erpnext-python_1          |     self.set_session()
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 71, in set_session
erpnext-python_1          |     frappe.local.login_manager = LoginManager()
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 124, in __init__
erpnext-python_1          |     self.make_session(resume=True)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 201, in make_session
erpnext-python_1          |     full_name=self.full_name, user_type=self.user_type)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 194, in __init__
erpnext-python_1          |     self.resume()
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 261, in resume
erpnext-python_1          |     validate_ip_address(self.user)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 392, in validate_ip_address
erpnext-python_1          |     user = frappe.get_cached_doc("User", user) if not frappe.flags.in_test else frappe.get_doc("User", user)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 752, in get_cached_doc
erpnext-python_1          |     doc = get_doc(*args, **kwargs)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 795, in get_doc
erpnext-python_1          |     doc = frappe.model.document.get_doc(*args, **kwargs)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 69, in get_doc
erpnext-python_1          |     controller = get_controller(doctype)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 38, in get_controller
erpnext-python_1          |     module_name, custom = frappe.db.get_value("DocType", doctype, ("module", "custom"), cache=True) \
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 408, in get_value
erpnext-python_1          |     order_by, cache=cache)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 452, in get_values
erpnext-python_1          |     out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 599, in _get_values_from_table
erpnext-python_1          |     as_dict=as_dict, debug=debug, update=update)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
erpnext-python_1          |     self.connect()
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
erpnext-python_1          |     self._conn = self.get_connection()
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
erpnext-python_1          |     local_infile = frappe.conf.local_infile)
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
erpnext-python_1          |     return Connection(*args, **kwargs)
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
erpnext-python_1          |     self.connect()
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
erpnext-python_1          |     self._request_authentication()
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
erpnext-python_1          |     auth_packet = self._read_packet()
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
erpnext-python_1          |     packet.check_error()
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
erpnext-python_1          |     err.raise_mysql_exception(self._data)
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
erpnext-python_1          |     raise errorclass(errno, errval)
erpnext-python_1          | pymysql.err.OperationalError: (1045, "Access denied for user '_a6baca2e68f9be45'@'172.20.0.6' (using password: YES)")
erpnext-python_1          |
erpnext-python_1          | During handling of the above exception, another exception occurred:
erpnext-python_1          |
erpnext-python_1          | Traceback (most recent call last):
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 280, in handle
erpnext-python_1          |     keepalive = self.handle_request(req, conn)
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 329, in handle_request
erpnext-python_1          |     respiter = self.wsgi(environ, resp.start_response)
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 231, in application
erpnext-python_1          |     return ClosingIterator(app(environ, start_response), self.cleanup)
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/wrappers/base_request.py", line 237, in application
erpnext-python_1          |     resp = f(*args[:-2] + (request,))
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 88, in application
erpnext-python_1          |     response = handle_exception(e)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 252, in handle_exception
erpnext-python_1          |     http_status_code=http_status_code)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 35, in render
erpnext-python_1          |     raise_if_disabled(path)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 372, in raise_if_disabled
erpnext-python_1          |     'route': ['like', '%{0}'.format(path)]
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 535, in get_all
erpnext-python_1          |     return frappe.get_all(*args, **kwargs)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1368, in get_all
erpnext-python_1          |     return get_list(doctype, *args, **kwargs)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1341, in get_list
erpnext-python_1          |     return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 96, in execute
erpnext-python_1          |     result = self.build_and_run()
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 110, in build_and_run
erpnext-python_1          |     args = self.prepare_args()
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 136, in prepare_args
erpnext-python_1          |     self.set_optional_columns()
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 302, in set_optional_columns
erpnext-python_1          |     columns = get_table_columns(self.doctype)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
erpnext-python_1          |     return frappe.db.get_table_columns(doctype)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 868, in get_table_columns
erpnext-python_1          |     columns = self.get_db_table_columns('tab' + doctype)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 859, in get_db_table_columns
erpnext-python_1          |     where table_name = %s ''', table)]
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 122, in sql
erpnext-python_1          |     self.connect()
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 75, in connect
erpnext-python_1          |     self._conn = self.get_connection()
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
erpnext-python_1          |     local_infile = frappe.conf.local_infile)
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
erpnext-python_1          |     return Connection(*args, **kwargs)
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
erpnext-python_1          |     self.connect()
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
erpnext-python_1          |     self._request_authentication()
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
erpnext-python_1          |     auth_packet = self._read_packet()
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
erpnext-python_1          |     packet.check_error()
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
erpnext-python_1          |     err.raise_mysql_exception(self._data)
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
erpnext-python_1          |     raise errorclass(errno, errval)
erpnext-python_1          | pymysql.err.OperationalError: (1045, "Access denied for user '_a6baca2e68f9be45'@'172.20.0.6' (using password: YES)")
```

**Comment by revant** [comment]
I have latest docker compose and I could not recreate the issue https://docs.docker.com/compose/cli-command/

I was able to create and access the site.

**Comment by ChrisgammaDE** [comment]
Can also confirm with a Debian Buster installation.   
Nftables, Docker via Docker Repros

**Comment by entrptaher** [comment]
I am having same issue in latest docker and docker-compose.

```
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/pymysql/connections.py", line 633, in connect
erpnext-python_1          |     self._request_authentication()
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/pymysql/connections.py", line 907, in _request_authentication
erpnext-python_1          |     auth_packet = self._read_packet()
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
erpnext-python_1          |     packet.raise_for_error()
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
erpnext-python_1          |     err.raise_mysql_exception(self._data)
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
erpnext-python_1          |     raise errorclass(errno, errval)
erpnext-python_1          | pymysql.err.OperationalError: (1045, "Access denied for user '_bada7d9a378dcae6'@'172.19.0.7' (using password: YES)")
mariadb_1                 | 2022-01-24  7:26:35 56 [Warning] Access denied for user '_bada7d9a378dcae6'@'172.19.0.11' (using password: YES)


```

**Comment by entrptaher** [comment]
I managed to make it work by running mariadb first and then site-creator afterwards.

**Comment by guanfeng36** [comment]
I got the same issue. And I queried mariadb and did not found user with name like _bada7d9a378dcae6

**Comment by guanfeng36** [comment]
I create a new site with following instruction, and it seems ok.
<img width="1093" alt="Screen Shot 2022-03-08 at 10 53 48 AM" src="https://user-images.githubusercontent.com/13617570/157157094-e23d1dff-0107-45ba-94d2-e4ab82e5362e.png">

**Comment by jamalmatic** [comment]
I got the same issue. test on ubuntu, windows and google cloud 
`site-creator_1            | Updating customizations for Address
site-creator_1            | Updating customizations for Contact
site-creator_1            | *** Scheduler is disabled ***
mariadb_1                 | 2022-03-11 11:44:32 13 [Warning] Aborted connection 13 to db: '_c096fb554dd9bea7' user: '_c096fb554dd9bea7' host: '172.19.0.13' (Got an errorreading communication packets)
demo_site-creator_1 exited with code 0`

**Comment by ChiropracticBender** [comment]
same issue im having

**Comment by ChrisgammaDE** [comment]
> Can also confirm with a Debian Buster installation. Nftables, Docker via Docker Repros

I don't know what changes have been made since, but yesterday I tried it again and everything went fine this time

**Comment by revant** [comment]
refactor changes many things. reopen if needed.
