### ISSUE TITLE
Localhost does not exist

### ISSUE THREAD

**Issue by gmochid** [frappe/frappe_docker#64]
When I run `./dbench start`, and I access `localhost:8000` from my browser, I get this error.

```
23:04:57 web.1            | SystemExit: 1
23:04:57 web.1            | ----------------------------------------
23:04:57 web.1            | localhost does not exist
23:04:57 web.1            | ----------------------------------------
23:04:57 web.1            | Exception happened during processing of request from ('172.22.0.1', 43360)
23:04:57 web.1            | Traceback (most recent call last):
23:04:57 web.1            |   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
23:04:57 web.1            |     self.finish_request(request, client_address)
23:04:57 web.1            |   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
23:04:57 web.1            |     self.RequestHandlerClass(request, client_address, self)
23:04:57 web.1            |   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
23:04:57 web.1            |     self.handle()
23:04:57 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 293, in handle
23:04:57 web.1            |     rv = BaseHTTPRequestHandler.handle(self)
23:04:57 web.1            |   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
23:04:57 web.1            |     self.handle_one_request()
23:04:57 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 328, in handle_one_request
23:04:57 web.1            |     return self.run_wsgi()
23:04:57 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
23:04:57 web.1            |     execute(self.server.app)
23:04:57 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 260, in execute
23:04:57 web.1            |     for data in application_iter:
23:04:57 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/debug/__init__.py", line 288, in debug_application
23:04:57 web.1            |     app_iter = self.app(environ, start_response)
23:04:57 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/middlewares.py", line 15, in __call__
23:04:57 web.1            |     return super(StaticDataMiddleware, self).__call__(environ, start_response)
23:04:57 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 766, in __call__
23:04:57 web.1            |     return self.app(environ, start_response)
23:04:57 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 766, in __call__
23:04:57 web.1            |     return self.app(environ, start_response)
23:04:57 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/local.py", line 228, in application
23:04:57 web.1            |     return ClosingIterator(app(environ, start_response), self.cleanup)
23:04:57 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/wrappers.py", line 308, in application
23:04:57 web.1            |     resp = f(*args[:-2] + (request,))
23:04:57 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 52, in application
23:04:57 web.1            |     init_request(request)
23:04:57 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 107, in init_request
23:04:57 web.1            |     frappe.init(site=site, sites_path=_sites_path)
23:04:57 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 151, in init
23:04:57 web.1            |     local.conf = _dict(get_site_config())
23:04:57 web.1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 220, in get_site_config
23:04:57 web.1            |     sys.exit(1)
23:04:57 web.1            | SystemExit: 1
23:04:57 web.1            | ----------------------------------------
```

**Comment by chabad360** [comment]
run `./dbench setup hosts`, that may fix it.

**Comment by chabad360** [comment]
after more testing, it seems like this is caused by gunicorn being setup to return the site folder that matches the `host` request parameter, in this case `localhost`. but the only site in the `sites` folder is `site1.local` (or whatever), hence the error.

**Comment by chabad360** [comment]
as a quick fix, I'd suggest making a site called `localhost` (i.e. run `bench new-site localhost`), that should solve that issue (I'll agree it's a bad solution).

**Comment by chabad360** [comment]
Please close, since as of #84 this is no longer relevant.
