### ISSUE TITLE
[v12 BREAKING] ImportError: cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by hankjordan** [frappe/frappe_docker#668]
## Description of the issue

Backwards incompatible change in Markupsafe 2.1.0 causes ERPNext/Frappe v12 to not start.

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.29.0
frappe 12.26.0
```

## Steps to reproduce the issue

1. Install Frappe-Worker with Docker
2. Install ERPNext App
3. Error on run

### Observed result

App does not work.

### Expected result

App works.

### Stacktrace / full error message

```
[2022-02-21 17:07:14 +0000] [20] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 50, in render
    data = render_page_by_language(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 177, in render_page_by_language
    return render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 193, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 200, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 215, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 42, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 50, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 25, in resolve_route
    context = get_page_info_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 77, in get_page_info_from_template
    return get_page_info(option, app, start, app_path=app_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 223, in get_page_info
    setup_source(page_info)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 256, in setup_source
    jenv = frappe.get_jenv()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 10, in get_jenv
    from jinja2 import DebugUndefined
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/frappe/frappe-bench/env/lib/python3.7/site-packages/markupsafe/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 76, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 80, in render
    data = render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 193, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 200, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 215, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 42, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 50, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 25, in resolve_route
    context = get_page_info_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 77, in get_page_info_from_template
    return get_page_info(option, app, start, app_path=app_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 223, in get_page_info
    setup_source(page_info)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 256, in setup_source
    jenv = frappe.get_jenv()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 10, in get_jenv
    from jinja2 import DebugUndefined
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/frappe/frappe-bench/env/lib/python3.7/site-packages/markupsafe/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 50, in render
    data = render_page_by_language(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 177, in render_page_by_language
    return render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 193, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 200, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 215, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 42, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 50, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 25, in resolve_route
    context = get_page_info_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 77, in get_page_info_from_template
    return get_page_info(option, app, start, app_path=app_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 223, in get_page_info
    setup_source(page_info)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 256, in setup_source
    jenv = frappe.get_jenv()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 10, in get_jenv
    from jinja2 import DebugUndefined
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/frappe/frappe-bench/env/lib/python3.7/site-packages/markupsafe/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 280, in handle
    keepalive = self.handle_request(req, conn)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 329, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 231, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/wrappers/base_request.py", line 237, in application
    resp = f(*args[:-2] + (request,))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 88, in application
    response = handle_exception(e)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 252, in handle_exception
    http_status_code=http_status_code)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 80, in render
    data = render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 193, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 200, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 215, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 42, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 50, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 25, in resolve_route
    context = get_page_info_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 77, in get_page_info_from_template
    return get_page_info(option, app, start, app_path=app_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 223, in get_page_info
    setup_source(page_info)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 256, in setup_source
    jenv = frappe.get_jenv()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 10, in get_jenv
    from jinja2 import DebugUndefined
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/frappe/frappe-bench/env/lib/python3.7/site-packages/markupsafe/__init__.py)
```

## Additional information

Upstream has fixed the issue in Frappe v12.26.1 but the changes have not yet been pulled to the Docker image.

**Comment by vrslev** [comment]
[Manually started the build](https://github.com/frappe/frappe_docker/runs/5300577051?check_suite_focus=true). Docker image for v12.16.1 is available now.
