### ISSUE TITLE
Bench init failed

### ISSUE THREAD

**Issue by CleoMenezesJr** [frappe/frappe_docker#721]
## Description of the issue
When trying to run bench init and apparently all goes well while getting and installing Frappe, at the end of the installation I get the error message below.

## Steps to reproduce the issue

1. `docker exec -e "TERM=xterm-256color" -w /workspace/development -it devcontainer_frappe_1 bash`
2. `bench init --skip-redis-config-generation --frappe-branch version-13 frappe-bench`

### Observed result
![image](https://user-images.githubusercontent.com/54215258/159358099-802fffc3-5313-431e-a82c-4eeacdfb49f9.png)

### Stacktrace / full error message if available

```
Traceback (most recent call last):
  File "/home/frappe/.bench/bench/commands/make.py", line 70, in init
    init(
  File "/home/frappe/.bench/bench/utils/render.py", line 95, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.bench/bench/utils/system.py", line 78, in init
    get_app(
  File "/home/frappe/.bench/bench/app.py", line 371, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets)
  File "/home/frappe/.bench/bench/utils/render.py", line 110, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.bench/bench/app.py", line 198, in install
    install_app(
  File "/home/frappe/.bench/bench/app.py", line 436, in install_app
    bench.reload()
  File "/home/frappe/.bench/bench/utils/render.py", line 110, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.bench/bench/bench.py", line 142, in reload
    restart_supervisor_processes(bench_path=self.name, web_workers=web)
  File "/home/frappe/.bench/bench/utils/bench.py", line 256, in restart_supervisor_processes
    supervisor_status = get_cmd_output("supervisorctl status", cwd=bench_path)
  File "/home/frappe/.bench/bench/utils/__init__.py", line 185, in get_cmd_output
    output = subprocess.check_output(
  File "/home/frappe/.pyenv/versions/3.9.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/frappe/.pyenv/versions/3.9.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'supervisorctl status' returned non-zero exit status 127.
```

**Comment by revant** [comment]
follow this https://github.com/frappe/bench/issues/1284
