### ISSUE TITLE
Unable to install erpnext docker version

### ISSUE THREAD

**Issue by asharabu** [frappe/frappe_docker#79]
We tried to install erpnext using docker version but we are getting below error while running the below command,

/opt/frappe_docker$ ./dbench init
WARN: Command not being executed in bench directory
INFO:bench.utils:virtualenv -q env -p /usr/bin/python3
Not overwriting existing python script /home/frappe/frappe-bench/env/bin/python (you must use /home/frappe/frappe-bench/env/bin/python3)
INFO:bench.utils:env/bin/pip -q install --upgrade pip
INFO:bench.utils:env/bin/pip -q install wheel
INFO:bench.utils:env/bin/pip -q install six
INFO:bench.utils:env/bin/pip -q install -e git+https://github.com/frappe/python-pdfkit.git#egg=pdfkit
ERROR: frappe 12.1.0 has requirement pdfkit==0.6.1, but you'll have pdfkit 0.5.0 which is incompatible.
INFO:bench.app:getting app frappe
INFO:bench.utils:git clone https://github.com/frappe/frappe.git  --depth 1 --origin upstream
fatal: destination path 'frappe' already exists and is not an empty directory.
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/src/bench/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/src/bench/bench/commands/make.py", line 31, in init
    python               = python)
  File "/src/bench/bench/utils.py", line 99, in init
    get_app(frappe_path, branch=frappe_branch, bench_path=path, skip_assets=True, verbose=verbose)
  File "/src/bench/bench/app.py", line 125, in get_app
    cwd=os.path.join(bench_path, 'apps'))
  File "/src/bench/bench/utils.py", line 185, in exec_cmd
    raise CommandFailedError(cmd)
bench.utils.CommandFailedError: git clone https://github.com/frappe/frappe.git  --depth 1 --origin upstream
mv: cannot stat 'Procfile_docker': No such file or directory

**Comment by chabad360** [comment]
Try running `./dbench init "/home/frappe/frappe-docker”`

**Comment by chabad360** [comment]
Please close, since as of #84 this is no longer relevant.
