### ISSUE TITLE
APP_NAME in bake.hcl undefined apparently + notes on app

### ISSUE THREAD

**Issue by 1ubuntuuser** [frappe/frappe_docker#811]
Docker version 20.10.7, build f0df350

I have enjoyed using Frappe and created my first app. Thank you @vrslev for creating the guide, very useful. 

I did find the following bug.

`error: docker-bake.hcl:14,20-28: Unknown variable; There is no variable named "APP_NAME"., and 3 other diagnostic(s)
`

I was able to work around this by adding the following to the _docker-bake.hcl_ file.
```
variable "APP_NAME" {
	default = "docbridge"
}
```

A couple of other notes:
- Might be good to have the list of files to copy formatted in a list instead of in a paragraph.
- Might be worth noting that you need to run the docker build... command from the root of your app instead of from frappe_docker
- https://github.com/castlecraft/custom_frappe_docker If this is no longer the easiest approach to creating custom app builds, it might be worth updating it's README.

I should really learn how to do a PR.......

**Comment by vrslev** [comment]
> I should really learn how to do a PR

Definitely!

I will check later what you suggest, thanks!

**Comment by revant** [comment]
> * https://github.com/castlecraft/custom_frappe_docker If this is no longer the easiest approach to creating custom app builds, it might be worth updating it's README.

I fork and use that repo as a template to setup multiple apps in an image. It is using the updated custom_app documentation. readme mentions that and has a link to docs in this repo

**Comment by revant** [comment]
> Right, so that repo is more or less an implementation of the custom_app folder?

yes.

one can assume that custom app can be single app and you package it as part of builds where there is no separate build repo

castlecraft/custom_frappe_docker implements custom_app and additional apps as part of builds. This is what might be needed in v14. Add multiple apps including custom and community apps.

**Comment by 1ubuntuuser** [comment]
Is there a reason we can't install apps directly into the docker volumes instead of rebuilding the images? Just seems strange we can't have an ecosystem that allows an easier way to add apps.

**Comment by 1ubuntuuser** [comment]
I was able to install an app using `bench get-app` so why is building a custom image required? Or is it just a way to get apps preinstalled?

```
bench get-app  chat https://github.com/frappe/chat
bench --site erpnext.localhost install-app chat
```
App stayed installed after restarting the containers, so the installation was persistent.

**Comment by revant** [comment]
> Is there a reason we can't install apps directly into the docker volumes instead of rebuilding the images? Just seems strange we can't have an ecosystem that allows an easier way to add apps.

@vrslev any comments?

I'm okay with anything, we already have 1.5gb image, rwx volumes mandatory, Complicated nodejs, yarn, python interdependencies, we're already following these not so best practices! adding apps in volume is also fine.

> I was able to install an app using `bench get-app` so why is building a custom image required? Or is it just a way to get apps preinstalled?
> 
> ```
> bench get-app  chat https://github.com/frappe/chat
> bench --site erpnext.localhost install-app chat
> ```
> 
> App stayed installed after restarting the containers, so the installation was persistent.

restarting same container will have the app, if there are container replicas you need to do this in each container. you need to do this in new container created.

i think the get-app also needs to build assets using nodejs devDependencies and yarn.

**Comment by vrslev** [comment]
> adding apps in volume is also fine.

@revant I don’t think we should dynamically mount code as volumes. Docker Volumes eat quite a lot of memory, also it would be quite hard to track down versions and orphan volumes.

**Comment by vrslev** [comment]
I personally prefer to make things _static_ and declarative in a project as much things as possible.

There’s a “but” though. I stopped thinking about Frappe as a framework. Judging by infrastructure it is a full blown application to which ERPNext delegates its low level things. Somehow we managed to give people template for dockerizing custom apps built with Frappe _from developer’s point of view, not DevOps’_. If we want to keep it that way—for developers first—we shouldn’t consider custom apps installation using volumes.

**Comment by revant** [comment]
i belive no one really cares here.

whatever hack works, people will use it. we find that quality, attitude and approach everywhere in the project.

sometimes I really feel like just having my own docker images and let the community install, maintain, burn, bloat, delete this. I won't be bothered to protect best practices where no one really wants them.

**Comment by revant** [comment]
I'm really fed up of this.

noobs land here and complain

"that Doc is written to confuse or maybe outdated , i don't think anyone will get it working referring to that docker installation doc ."

experts want, how to install Dyson sphere using frappe framework.

**Comment by revant** [comment]
- RWX / NFS volume needed in 2022!
- multi image node-sass gymnastics!
- 1.5gb base image!

we can't escape this as the project was not designed to be containerized. Upstream don't like containers to even think of designing for containers. officially and even on FC they pull code from git branches. there is no immutable code here.

node-sass will be used in production. it generates css assets dynamically!

**Comment by 1ubuntuuser** [comment]
Lots to consider here...

> Somehow we managed to give people template for dockerizing custom apps built with Frappe _from developer’s point of view, not DevOps_
I think neither of these point of views are as important as supporting the app eco-system. I'm assuming the separation of Frappe and ERPnext was to expose the genius simplicity of the frappe framework to development alongside erpnext. I assume Frappe co hope is to foster an eco-system of apps on frappe. Outside of the dockerverse sharing apps is very easy with the `bench get-app ` no custom builds which require self hosted docker images etc.

> @revant I don’t think we should dynamically mount code as volumes. Docker Volumes eat quite a lot of memory, also it would be quite hard to track down versions and orphan volumes.
One approach would be to remove all source code from the docker images and pull source code into a docker volume (mounted on the host perhaps to support NFS) with a script on docker-compose start. Standard bench commands should work from there.

It would require a bit of a rewrite but would it make handling apps (the future in my opinion) easier?

**Comment by revant** [comment]
i would prefer being in best practices camp than join the container massacre.

also I'm using this on kubernetes. What i get with being on kubernetes is way more than low code framework. If you're ready to maintain this, I'll hand it over to you and move this immutable code to private maintenance for least headache for me.

Then I really don't care what happens here.

here are other low code frameworks that run on containers: 

https://docs.budibase.com/docs/kubernetes-k8s

https://tooljet.com

different projects but i think n8n and nodered also run on containers.

thing do happen outside, but they are not invented here.

**Comment by 1ubuntuuser** [comment]
So you run these same containers on kubernetes? 

I think the work you have done here is wonderful but unfortunately most of the details are over my head to maintain. 

I'll see if I can come up with an elegant app installation solution and figure and send a PR if it's any good.

**Comment by revant** [comment]
> So you run these same containers on kubernetes?

We have these decoupled images because I wanted to run ERPNext on Kubernetes. Before that there was just 1 bench image used for development.

> I'll see if I can come up with an elegant app installation solution and figure and send a PR if it's any good.

add supervisor and nginx to frappe/bench:latest image.

normal development happens with `sleep infinity` as command.

production can run with `supervisord` as command, and `supervisor` configures current processes + nginx to run.

supervisor and nginx should be configurable by mounting config files in right places.

**Comment by 1ubuntuuser** [comment]
That approuch could work.

I have turned frappe-bench into a volume mounted it across the containers, and used install-app. It seems to work. Is this a dump approach? 

```
    volumes:
    - type: volume
      source: frappe
      target: /home/frappe/frappe-bench
      volume: {}
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
```

**Comment by revant** [comment]
production images won't work for static assets.
static assets are built and packed into nginx. install-app from worker image just takes care of install in python environment.

in case you use bench image, no need to mount each frappe-bench separately, just mount the workspace like this https://github.com/frappe/frappe_docker/blob/main/devcontainer-example/docker-compose.yml

you will need supervisor to achieve what you need to.
just change the frappe/bench image for that.

personally, I'll not accept apps in volume for other images than frappe/bench.

**Comment by 1ubuntuuser** [comment]
@revant I see how that could be simpler, but I like how you have separated the system to multiple containers. I want to scale this to potentially hundreds of sites and I don't think 1 container could handle that very well. I'm going to see if I can get build the assets dynamically... So far when running the isntall-app on the frontend in a production container I get the following.

```

root@9340cdebc61d:/frappe-bench# install-app chat
+ APP=chat
+ cd /frappe-bench
+ test -d apps/chat/chat/public
+ cp -r apps/chat/chat/public /out/assets/chat
+ yarn --cwd apps/chat --prod
yarn install v1.22.19
[1/4] Resolving packages...
success Nothing to install.
success Saved lockfile.
Done in 0.06s.
+ cp -r apps/chat/node_modules /out/assets/chat/node_modules
+ yarn --cwd apps/chat
yarn install v1.22.19
[1/4] Resolving packages...
success Nothing to install.
success Saved lockfile.
Done in 0.07s.
+ echo chat
+ yarn --cwd apps/frappe run production --app chat
yarn run v1.22.19
$ FRAPPE_ENV=production node rollup/build.js --app chat
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'chalk'
Require stack:
- /frappe-bench/apps/frappe/rollup/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/frappe-bench/apps/frappe/rollup/build.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/frappe-bench/apps/frappe/rollup/build.js' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 
```

**Comment by revant** [comment]
> but I like how you have separated the system to multiple containers

I'm against apps in volumes. so i won't any accept change in the images you're trying to update even if you send PR.

if you mess up development image. I'm fine with that.

**Comment by 1ubuntuuser** [comment]
Alrighty... I'll giveup on that idea. I kinda get why production images should be static but I also think it's pretty limiting to the eco system to not allow apps to be shared easily.

Anyway, I will just use your https://github.com/castlecraft/custom_frappe_docker repo to package multiple apps.

Perhaps loading apps dynamically will be considered for the next version. Thanks for your consideration anyway.
