### ISSUE TITLE
ERROR: Volume vscode declared as external, but could not be found. Please create the volume manually using `docker volume create --name=vscode` and try again.

### ISSUE THREAD

**Issue by bytes-karnav** [frappe/frappe_docker#825]
## Steps to reproduce the issue

1. Launch the command, from Command Palette (Ctrl + Shift + P) Remote-Containers: Reopen in Container. You can also click in the bottom left corner to access the remote container menu.

### Observed result
```
[2022-06-22T13:41:31.407Z] Remote-Containers 0.238.2 in VS Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630).
[2022-06-22T13:41:31.407Z] Start: Resolving Remote
[2022-06-22T13:41:31.427Z] Setting up container for folder or workspace: /media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker
[2022-06-22T13:41:31.427Z] Context: desktop-linux
[2022-06-22T13:41:31.431Z] Start: Check Docker is running
[2022-06-22T13:41:31.431Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2022-06-22T13:41:31.527Z] Stop (96 ms): Run: docker version --format {{.Server.APIVersion}}
[2022-06-22T13:41:31.528Z] Server API version: 1.41
[2022-06-22T13:41:31.529Z] Stop (98 ms): Check Docker is running
[2022-06-22T13:41:31.530Z] Start: Run: docker volume ls -q
[2022-06-22T13:41:31.640Z] Stop (110 ms): Run: docker volume ls -q
[2022-06-22T13:41:31.651Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker --filter label=vsch.quality=stable
[2022-06-22T13:41:31.753Z] Stop (102 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker --filter label=vsch.quality=stable
[2022-06-22T13:41:31.753Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker
[2022-06-22T13:41:31.857Z] Stop (104 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker
[2022-06-22T13:41:31.858Z] Start: Run: /usr/share/code/code /home/bytes/.vscode/extensions/ms-vscode-remote.remote-containers-0.238.2/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/bytes/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker --workspace-mount-consistency cached --id-label devcontainer.local_folder=/media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker --log-level debug --log-format json --config /media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-06-22T13:41:32.091Z] remote-containers 0.238.2.
[2022-06-22T13:41:32.091Z] Start: Run: docker buildx version
[2022-06-22T13:41:32.320Z] Stop (229 ms): Run: docker buildx version
[2022-06-22T13:41:32.321Z] Start: Resolving Remote
[2022-06-22T13:41:32.326Z] Start: Run: docker-compose version --short
[2022-06-22T13:41:33.013Z] Stop (687 ms): Run: docker-compose version --short
[2022-06-22T13:41:33.015Z] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=frappe_docker_devcontainer --filter label=com.docker.compose.service=frappe
[2022-06-22T13:41:33.157Z] Stop (142 ms): Run: docker ps -q -a --filter label=com.docker.compose.project=frappe_docker_devcontainer --filter label=com.docker.compose.service=frappe
[2022-06-22T13:41:33.160Z] Start: Run: docker-compose -f /media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker/.devcontainer/docker-compose.yml config
[2022-06-22T13:41:34.067Z] Stop (907 ms): Run: docker-compose -f /media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker/.devcontainer/docker-compose.yml config
[2022-06-22T13:41:34.067Z] services:
  frappe:
    command: sleep infinity
    environment:
      SHELL: /bin/bash
    image: frappe/bench:latest
    ports:
    - published: 8000
      target: 8000
    - published: 8001
      target: 8001
    - published: 8002
      target: 8002
    - published: 8003
      target: 8003
    - published: 8004
      target: 8004
    - published: 8005
      target: 8005
    - published: 9000
      target: 9000
    - published: 9001
      target: 9001
    - published: 9002
      target: 9002
    - published: 9003
      target: 9003
    - published: 9004
      target: 9004
    - published: 9005
      target: 9005
    volumes:
    - /media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker:/workspace:cached
    working_dir: /workspace/development
  mariadb:
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    - --skip-character-set-client-handshake
    - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: 123
    image: mariadb:10.6
    volumes:
    - mariadb-data:/var/lib/mysql:rw
  redis-cache:
    image: redis:alpine
  redis-queue:
    image: redis:alpine
  redis-socketio:
    image: redis:alpine
version: '3.7'
volumes:
  mariadb-data: {}
  postgresql-data: {}

[2022-06-22T13:41:34.079Z] Start: Run: docker -v
[2022-06-22T13:41:34.240Z] Stop (161 ms): Run: docker -v
[2022-06-22T13:41:34.241Z] Start: Run: docker events --format {{json .}} --filter event=start
[2022-06-22T13:41:34.251Z] PersistedPath=/home/bytes/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data, ContainerHasLabels=false
[2022-06-22T13:41:34.253Z] Start: Run: docker-compose -f /media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker/.devcontainer/docker-compose.yml config
[2022-06-22T13:41:35.201Z] Stop (948 ms): Run: docker-compose -f /media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker/.devcontainer/docker-compose.yml config
[2022-06-22T13:41:35.201Z] services:
  frappe:
    command: sleep infinity
    environment:
      SHELL: /bin/bash
    image: frappe/bench:latest
    ports:
    - published: 8000
      target: 8000
    - published: 8001
      target: 8001
    - published: 8002
      target: 8002
    - published: 8003
      target: 8003
    - published: 8004
      target: 8004
    - published: 8005
      target: 8005
    - published: 9000
      target: 9000
    - published: 9001
      target: 9001
    - published: 9002
      target: 9002
    - published: 9003
      target: 9003
    - published: 9004
      target: 9004
    - published: 9005
      target: 9005
    volumes:
    - /media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker:/workspace:cached
    working_dir: /workspace/development
  mariadb:
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    - --skip-character-set-client-handshake
    - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: 123
    image: mariadb:10.6
    volumes:
    - mariadb-data:/var/lib/mysql:rw
  redis-cache:
    image: redis:alpine
  redis-queue:
    image: redis:alpine
  redis-socketio:
    image: redis:alpine
version: '3.7'
volumes:
  mariadb-data: {}
  postgresql-data: {}

[2022-06-22T13:41:35.206Z] Start: Run: docker-compose --project-name frappe_docker_devcontainer -f /media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker/.devcontainer/docker-compose.yml build
[2022-06-22T13:41:35.934Z] mariadb uses an image, skipping
redis-cache uses an image, skipping
redis-queue uses an image, skipping
redis-socketio uses an image, skipping
frappe uses an image, skipping
[2022-06-22T13:41:36.055Z] Stop (849 ms): Run: docker-compose --project-name frappe_docker_devcontainer -f /media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker/.devcontainer/docker-compose.yml build
[2022-06-22T13:41:36.056Z] Start: Run: docker inspect --type image frappe/bench:latest
[2022-06-22T13:41:36.164Z] Stop (108 ms): Run: docker inspect --type image frappe/bench:latest
[2022-06-22T13:41:36.168Z] Start: Run: docker build -f /tmp/vsch/updateUID.Dockerfile-0.238.2 -t vsc-frappe_docker-bd8424e702685bb7c5c9b2c4b3d026ae-uid --build-arg BASE_IMAGE=frappe/bench:latest --build-arg REMOTE_USER=frappe --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=frappe /tmp/vsch
[2022-06-22T13:41:36.583Z] [+] Building 0.0s (0/1)                                                         
[2022-06-22T13:41:36.734Z] [+] Building 0.2s (2/2)                                                         
 => [internal] load build definition from updateUID.Dockerfile-0.238.2     0.0s
 => => transferring dockerfile: 1.34kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
[2022-06-22T13:41:36.810Z] [+] Building 0.2s (6/6) FINISHED                                                
 => [internal] load build definition from updateUID.Dockerfile-0.238.2     0.0s
 => => transferring dockerfile: 1.34kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/frappe/bench:latest             0.0s
 => [1/2] FROM docker.io/frappe/bench:latest                               0.0s
 => CACHED [2/2] RUN eval $(sed -n "s/frappe:[^:]*:\([^:]*\):\([^:]*\):[^  0.0s
 => exporting to image                                                     0.0s
 => => exporting layers                                                    0.0s
[2022-06-22T13:41:36.811Z]  => => writing image sha256:34e32e424b68020f12ed3dcb768de18eae5afc9979663  0.0s
 => => naming to docker.io/library/vsc-frappe_docker-bd8424e702685bb7c5c9  0.0s
[2022-06-22T13:41:37.154Z] Stop (986 ms): Run: docker build -f /tmp/vsch/updateUID.Dockerfile-0.238.2 -t vsc-frappe_docker-bd8424e702685bb7c5c9b2c4b3d026ae-uid --build-arg BASE_IMAGE=frappe/bench:latest --build-arg REMOTE_USER=frappe --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=frappe /tmp/vsch
[2022-06-22T13:41:37.158Z] Writing docker-compose.devcontainer.containerFeatures-1655905297158.yml to /home/bytes/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose
[2022-06-22T13:41:37.159Z] Start: Run: docker-compose --project-name frappe_docker_devcontainer -f /media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker/.devcontainer/docker-compose.yml -f /home/bytes/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1655905297158.yml up -d
[2022-06-22T13:41:38.150Z] ERROR: Volume vscode declared as external, but could not be found. Please create the volume manually using `docker volume create --name=vscode` and try again.
[2022-06-22T13:41:38.272Z] Stop (1113 ms): Run: docker-compose --project-name frappe_docker_devcontainer -f /media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker/.devcontainer/docker-compose.yml -f /home/bytes/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1655905297158.yml up -d
[2022-06-22T13:41:38.276Z] Error: Command failed: docker-compose --project-name frappe_docker_devcontainer -f /media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker/.devcontainer/docker-compose.yml -f /home/bytes/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1655905297158.yml up -d
[2022-06-22T13:41:38.277Z]     at RR (/home/bytes/.vscode/extensions/ms-vscode-remote.remote-containers-0.238.2/dist/spec-node/devContainersSpecCLI.js:204:2936)
[2022-06-22T13:41:38.278Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-22T13:41:38.278Z]     at async PR (/home/bytes/.vscode/extensions/ms-vscode-remote.remote-containers-0.238.2/dist/spec-node/devContainersSpecCLI.js:188:2240)
[2022-06-22T13:41:38.279Z]     at async zR (/home/bytes/.vscode/extensions/ms-vscode-remote.remote-containers-0.238.2/dist/spec-node/devContainersSpecCLI.js:245:2177)
[2022-06-22T13:41:38.279Z]     at async nb (/home/bytes/.vscode/extensions/ms-vscode-remote.remote-containers-0.238.2/dist/spec-node/devContainersSpecCLI.js:245:3110)
[2022-06-22T13:41:38.279Z]     at async JR (/home/bytes/.vscode/extensions/ms-vscode-remote.remote-containers-0.238.2/dist/spec-node/devContainersSpecCLI.js:245:13046)
[2022-06-22T13:41:38.280Z]     at async KR (/home/bytes/.vscode/extensions/ms-vscode-remote.remote-containers-0.238.2/dist/spec-node/devContainersSpecCLI.js:245:12802)
[2022-06-22T13:41:38.287Z] Stop (6429 ms): Run: /usr/share/code/code /home/bytes/.vscode/extensions/ms-vscode-remote.remote-containers-0.238.2/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/bytes/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker --workspace-mount-consistency cached --id-label devcontainer.local_folder=/media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker --log-level debug --log-format json --config /media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-06-22T13:41:38.288Z] Exit code 1
[2022-06-22T13:41:38.300Z] Command failed: /usr/share/code/code /home/bytes/.vscode/extensions/ms-vscode-remote.remote-containers-0.238.2/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/bytes/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker --workspace-mount-consistency cached --id-label devcontainer.local_folder=/media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker --log-level debug --log-format json --config /media/bytes/workspaces/projects/ETL-Project/codebase/frappe_docker/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-06-22T13:41:38.301Z] Exit code 1
```

**Comment by revant** [comment]
can you run the docker-compose command manually and check what is the error?

assuming you've copied the devcontainer-example
