### ISSUE TITLE
Having this issue, what could be the cause ?

### ISSUE THREAD

**Issue by yoelvd** [frappe/frappe_docker#869]
```Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1448, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 767, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/desktop.py", line 367, in get_desktop_page
    wspace = Workspace(page)
  File "apps/frappe/frappe/desk/desktop.py", line 56, in __init__
    self.onboarding_doc = self.get_onboarding_doc()
  File "apps/frappe/frappe/desk/desktop.py", line 156, in get_onboarding_doc
    if doc.check_completion():
  File "apps/frappe/frappe/desk/doctype/module_onboarding/module_onboarding.py", line 38, in check_completion
    self.save()
  File "apps/frappe/frappe/model/document.py", line 310, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 364, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1085, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 941, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1259, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1241, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 938, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/desk/doctype/module_onboarding/module_onboarding.py", line 15, in on_update
    export_to_files(record_list=[["Module Onboarding", self.name]], record_module=self.module)
  File "apps/frappe/frappe/modules/export_file.py", line 27, in export_to_files
    write_document_file(
  File "apps/frappe/frappe/modules/export_file.py", line 50, in write_document_file
    with open(os.path.join(folder, f"{fname}.json"), "w+") as txtfile:
PermissionError: [Errno 13] Permission denied: 'apps/erpnext/erpnext/accounts/module_onboarding/accounts/accounts.json'

admin@localhost:~/proj$ docker --version
Docker version 20.10.17, build 100c701
admin@localhost:~/proj$ docker-compose --version
Docker Compose version v2.9.0
admin@localhost:~/proj$ FRAPPE_VERSION=v13.32.0 ERPNEXT_VERSION=v13.33.0 docker buildx bake --no-cache
```
I'm using the custom_app recipe to make deploy 

![image](https://user-images.githubusercontent.com/14926620/182289761-ad479014-00ae-42d8-b293-143c90958023.png)

Don't know what could be the cause, it only happen in at least 5 modules not all.

Thanks in advance for your time...

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/issues/851

Is it related to this? Can you try the suggestions if they work for you?

**Comment by yoelvd** [comment]
Have erased all files and cloned repo again, this time using sudo to preserve file permissions but I got the same results after running everything with sudo except bench migrate command inside my backend of course

**Comment by revant** [comment]
can you enter the container and check file permissions?
if you need to change them for testing then enter the container as `--user=root` and try changing the permissions?

if they're not owned by user frappe then set ownership to frappe

**Comment by Morakhiyasaiyam** [comment]
> Have erased all files and cloned repo again, this time using sudo to preserve file permissions but I got the same results after running everything with sudo except bench migrate command inside my backend of course

No need to run everything with sudo
I just cloned repo with root user and then do everything else as normal way

**Comment by revant** [comment]
Create new issue if problem not solved.
