### ISSUE TITLE
legacy-install-failure and cython cannot installed

### ISSUE THREAD

**Issue by ahmedfatehi** [frappe/frappe_docker#879]
hello friends while I install erpnext app on my docker using `bench get-app --branch version-13 erpnext`
It gives me error asking me to run this code `pip install cython>=0.29.21,<1.0.0`
also when i run it it gives me error `bash: 1.0.0: No such file or directory`
when I use `which cython` it gives me `/home/frappe/.pyenv/shims/cython`

```` $ /workspace/development/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /workspace/development/frappe-bench/apps/erpnext 
  error: subprocess-exited-with-error
  
  × Running setup.py install for jsonobject did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      You are running without Cython installed. It is highly recommended to run
        pip install cython>=0.29.21,<1.0.0
      before you continue
      WARNING: The wheel package is not available.
      Warning: 'classifiers' should be a list, got type 'tuple'
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.9
      creating build/lib.linux-x86_64-3.9/jsonobject
      copying jsonobject/exceptions.py -> build/lib.linux-x86_64-3.9/jsonobject
      copying jsonobject/__init__.py -> build/lib.linux-x86_64-3.9/jsonobject
      running build_ext
      building 'jsonobject.api' extension
      creating build/temp.linux-x86_64-3.9
      creating build/temp.linux-x86_64-3.9/jsonobject
      x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/workspace/development/frappe-bench/env/include -I/usr/include/python3.9 -c jsonobject/api.c -o build/temp.linux-x86_64-3.9/jsonobject/api.o
      jsonobject/api.c:18:10: fatal error: Python.h: No such file or directory
         18 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> jsonobject

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
ERROR: 
Traceback (most recent call last):
  File "/home/frappe/.local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/home/frappe/.bench/bench/cli.py", line 127, in cli
    bench_command()
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/frappe/.bench/bench/commands/make.py", line 159, in get_app
    get_app(
  File "/home/frappe/.bench/bench/app.py", line 432, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/home/frappe/.bench/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.bench/bench/app.py", line 230, in install
    install_app(
  File "/home/frappe/.bench/bench/app.py", line 561, in install_app
    bench.run(
  File "/home/frappe/.bench/bench/bench.py", line 47, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd)
  File "/home/frappe/.bench/bench/utils/__init__.py", line 155, in exec_cmd
    raise CommandFailedError
bench.exceptions.CommandFailedError ````

**Comment by revant** [comment]
try

```
pip install "cython>=0.29.21,<1.0.0"
```

try double quotes?

**Comment by revant** [comment]
create new issue if needed.
