### ISSUE TITLE
Bench init version-13 with --python python3.9 failed

### ISSUE THREAD

**Issue by FHenry** [frappe/frappe_docker#893]
Hello,
For development purpose only with image frappe/bench:latest

I was trying to get the correct python version (aka 3.9) into pyenv for version-13

I run 
`bench init --skip-redis-config-generation --frappe-branch version-13 --python python3.9 frappe-bench`

here is the result 
```
frappe@0938383094fd:/workspace/development$ bench init --skip-redis-config-generation --frappe-branch version-13 --python python3.9 frappe-bench
Setting Up Environment
$ python3.9 -m venv env
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/workspace/development/frappe-bench/env/bin/python3.9', '-Im', 'ensurepip', '--upgrade', '--default-pip']

Traceback (most recent call last):
  File "/home/frappe/.bench/bench/commands/make.py", line 68, in init
    init(
  File "/home/frappe/.bench/bench/utils/render.py", line 105, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.bench/bench/utils/system.py", line 65, in init
    bench.setup.env(python=python)
  File "/home/frappe/.bench/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.bench/bench/bench.py", line 353, in env
    self.run(f"{venv} env", cwd=self.bench.name)
  File "/home/frappe/.bench/bench/bench.py", line 47, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd)
  File "/home/frappe/.bench/bench/utils/__init__.py", line 155, in exec_cmd
    raise CommandFailedError
bench.exceptions.CommandFailedError

ERROR: There was a problem while creating frappe-bench
Do you want to rollback these changes? [y/N]: y

```
I try this : 

```
frappe@0938383094fd:/workspace/development$ sudo apt-get install python3-venv
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python3-venv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-venv' has no installation candidate

```

**Comment by FHenry** [comment]
After look into bench container

frappe@0938383094fd:~$pyenv version
3.10.5 (set by /home/frappe/.pyenv/version)
3.7.12 (set by /home/frappe/.pyenv/version)
frappe@0938383094fd:~$ pyenv install 3.9.9              
pyenv: /home/frappe/.pyenv/versions/3.9.9 already exists
continue with installation? (y/N) N
frappe@0938383094fd:~$ pyenv global       
3.10.5
3.7.12
frappe@0938383094fd:~$ pyenv global 3.10.5 3.9.9 3.7.12

I found this into frappe_docker/images/bench/Dockerfile

now 
bench init --skip-redis-config-generation --frappe-branch version-13 --python python3.9 frappe-bench
work's correctly
