### ISSUE TITLE
bench --site local.test console failed

### ISSUE THREAD

**Issue by FHenry** [frappe/frappe_docker#900]
On development docker instance 

```
frappe@48ed1b309ad0:/workspace/development/frappe-bench$ bench --site erpnextdev.test console
Traceback (most recent call last):
  File "/home/frappe/.pyenv/versions/3.10.5/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/frappe/.pyenv/versions/3.10.5/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    main()
  File "/workspace/development/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/commands/utils.py", line 617, in console
    from IPython.terminal.embed import InteractiveShellEmbed
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/IPython/__init__.py", line 53, in <module>
    from .terminal.embed import embed
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/IPython/terminal/embed.py", line 15, in <module>
    from IPython.core.interactiveshell import DummyMod, InteractiveShell
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 74, in <module>
    from IPython.core.history import HistoryManager
  File "/workspace/development/frappe-bench/env/lib/python3.10/site-packages/IPython/core/history.py", line 11, in <module>
    import sqlite3
  File "/home/frappe/.pyenv/versions/3.10.5/lib/python3.10/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/home/frappe/.pyenv/versions/3.10.5/lib/python3.10/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```
it remind me the problem with

```
frappe@48ed1b309ad0:/workspace/development/frappe-bench$ python3
>>> import bz2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/frappe/.pyenv/versions/3.10.5/lib/python3.10/bz2.py", line 17, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
```

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/issues/840

this should fix. should we add that? it'll make the image 1.8GB

**Comment by FHenry** [comment]
Ok, Thank's I didn't dig enough to find this...

May be we can add them in comment with some explanation ?

1,8Gb is huge and for development purpose,I think that just documentation is enough.

Do you want a PR ?
