### ISSUE TITLE
Site Operations: service "backend" is not running container #1

### ISSUE THREAD

**Issue by shubham-samant** [frappe/frappe_docker#924]
https://github.com/frappe/frappe_docker/blob/main/docs/site-operations.md#setup-new-site

This command 
docker compose exec backend bench new-site sitename.com --mariadb-root-password admin@123 --admin-password admin@123

is giving the following as output:
service "backend" is not running container #1

I am setting up erpnext for the very first time and following step by step instructions as mentioned here 
https://github.com/frappe/frappe_docker/blob/main/README.md

Please suggest how to troubleshoot 
"service "backend" is not running container #1"

**Comment by kirtan403** [comment]
I've ran into this issue when I tried it first time. Just make sure all your containers were started from docker compose. I got an error on one of y containers due to arm64 architecture.

**Comment by sdfateh** [comment]
@shubham-samant 
Provide output for `docker compose ps` so we can help you

**Comment by shubham-samant** [comment]
Hi @sdfateh, following are the logs

`shubham@acer:~/Desktop$ docker compose --project-name ai-team-erp -f ~/gitops/docker-compose.yml up -d
[+] Running 12/12
 ⠿ Network frappe_docker_default          Created                                                                                                                                 0.0s
 ⠿ Container ai-team-erp-proxy-1          Started                                                                                                                                 0.6s
 ⠿ Container ai-team-erp-db-1             Healthy                                                                                                                                 2.1s
 ⠿ Container ai-team-erp-redis-1          Started                                                                                                                                 0.6s
 ⠿ Container ai-team-erp-configurator-1   Exited                                                                                                                                  2.9s
 ⠿ Container ai-team-erp-backend-1        Started                                                                                                                                 3.9s
 ⠿ Container ai-team-erp-websocket-1      Started                                                                                                                                 3.4s
 ⠿ Container ai-team-erp-queue-default-1  Started                                                                                                                                 3.7s
 ⠿ Container ai-team-erp-queue-short-1    Started                                                                                                                                 3.9s
 ⠿ Container ai-team-erp-queue-long-1     Started                                                                                                                                 3.4s
 ⠿ Container ai-team-erp-scheduler-1      Started                                                                                                                                 3.6s
 ⠿ Container ai-team-erp-frontend-1       Started                                                                                                                                 4.3s
shubham@acer:~/Desktop$ docker compose ps
no configuration file provided: not found
shubham@acer:~/Desktop$ 

`

**Comment by sdfateh** [comment]
@shubham-samant 

You have to add `-p` or `--project-name` to your operations commands

like this :
```
docker compose -p ai-team-erp exec backend bench new-site sitename.com --mariadb-root-password admin@123 --admin-pssword admin@123 
```
It will work like this.

@pv4n check if that helps you!

**Comment by shubham-samant** [comment]
@sdfateh 
Sorry i messed up the last comment, here are a few logs 
```
shubham@acer:~/Desktop/frappe_docker$ docker version
Client: Docker Engine - Community
 Version:           20.10.18
 API version:       1.41
 Go version:        go1.18.6
 Git commit:        b40c2f6
 Built:             Thu Sep  8 23:11:43 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.18
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.6
  Git commit:       e42327a
  Built:            Thu Sep  8 23:09:30 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
shubham@acer:~/Desktop/frappe_docker$ docker compose version
Docker Compose version v2.10.2
shubham@acer:~/Desktop/frappe_docker$ docker compose --project-name ai-team-erp -f ~/gitops/docker-compose.yml up -d
[+] Running 12/12
 ⠿ Network frappe_docker_default          Created                                                                                                                                                     0.0s
 ⠿ Container ai-team-erp-db-1             Healthy                                                                                                                                                     2.2s
 ⠿ Container ai-team-erp-redis-1          Started                                                                                                                                                     0.7s
 ⠿ Container ai-team-erp-proxy-1          Started                                                                                                                                                     0.7s
 ⠿ Container ai-team-erp-configurator-1   Exited                                                                                                                                                      2.9s
 ⠿ Container ai-team-erp-scheduler-1      Started                                                                                                                                                     3.6s
 ⠿ Container ai-team-erp-queue-short-1    Started                                                                                                                                                     4.1s
 ⠿ Container ai-team-erp-queue-long-1     Started                                                                                                                                                     3.6s
 ⠿ Container ai-team-erp-backend-1        Started                                                                                                                                                     3.2s
 ⠿ Container ai-team-erp-queue-default-1  Started                                                                                                                                                     4.0s
 ⠿ Container ai-team-erp-websocket-1      Started                                                                                                                                                     3.6s
 ⠿ Container ai-team-erp-frontend-1       Started                                                                                                                                                     4.2s
shubham@acer:~/Desktop/frappe_docker$ docker compose exec backend bench new-site sitename.com --mariadb-root-password admin@123 --admin-password admin@123
service "backend" is not running container #1
shubham@acer:~/Desktop/frappe_docker$ docker compose ps ~/gitops/docker-compose.yml
no such service: /home/shubham/gitops/docker-compose.yml
shubham@acer:~/Desktop/frappe_docker$ docker compose ps compose.yml 
no such service: compose.yml
shubham@acer:~/Desktop/frappe_docker$ 

```

**Comment by shubham-samant** [comment]
@sdfateh 
Thanks that solved the `service "backend" is not running container #1`
However post execution of the command, its printing the below. Can you please suggest a fix? 

```
shubham@acer:~/Desktop/frappe_docker$ docker compose -p ai-team-erp exec backend bench new-site aiteamerp.com --mariadb-root-password admin@123 --admin-password admin@123 
Traceback (most recent call last):
  File "/usr/local/bin/patched_bench_helper.py", line 48, in <module>
    raise SystemExit(main())
  File "/usr/local/bin/patched_bench_helper.py", line 43, in main
    frappe.utils.bench_helper.main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 74, in new_site
    _new_site(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 75, in _new_site
    install_db(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 151, in install_db
    setup_database(force, source_sql, verbose, no_mariadb_socket)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/__init__.py", line 20, in setup_database
    return frappe.database.mariadb.setup_db.setup_database(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/setup_db.py", line 41, in setup_database
    if force or (db_name not in dbman.get_database_list()):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/db_manager.py", line 49, in get_database_list
    return self.db.sql("SHOW DATABASES", pluck=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 190, in sql
    self.connect()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 115, in connect
    self._conn = self.get_connection()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 90, in get_connection
    conn = self._get_connection()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 96, in _get_connection
    return self.create_connection()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 99, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'172.18.0.6' (using password: YES)")

```

**Comment by sdfateh** [comment]
@shubham-samant 
Check your `mariadb-root-password`

**Comment by shubham-samant** [comment]
Yes the `mariadb-root-password` should be same as what is mentioned in the .env file, in my case `DB_PASSWORD=123`
This can be included as a note here to avoid confusion.
https://github.com/frappe/frappe_docker/blob/main/docs/site-operations.md#setup-new-site

Post completion of the command, I'm getting is as the output 
```
shubham@acer:~/Desktop/frappe_docker$ docker compose -p ai-team-erp exec backend bench new-site erp-aiteam.com --mariadb-root-password 123 --admin-password admin@123 

Installing frappe...
Updating DocTypes for frappe        : [========================================] 100%
Updating country info               : [========================================] 100%
erp-aiteam.com: SystemSettings.enable_scheduler is UNSET
*** Scheduler is disabled ***

```
Following further https://github.com/frappe/frappe_docker/blob/main/docs/site-operations.md#setup-new-site
I am trying to open the UI on chrome, but i'm not sure about the address, as that is also not included in the above mentioend page. Can you suggest the next step?  or share a document that contains further steps?

**Comment by sdfateh** [comment]
If you followed the steps correctly, you now need to define a DNS for the IP of the server you are working onto your local DNS and point to `erp-aiteam.com`

**Comment by shubham-samant** [comment]
noted, thanks!
