### ISSUE TITLE
more information about pwd.yml

### ISSUE THREAD

**Issue by kahidna** [frappe/frappe_docker#991]
just want to confirm about `pwd.yml` file, is the `pwd.yml` can be used for production environment?
I tried several times deploy erp Next using combination of `compose.yml` and the `.env` but its always ends with following error :
for frappe_docker_scheduler_1
```
root@p-erpnext-01:/opt/frappe_docker# docker logs frappe_docker_scheduler_1
Traceback (most recent call last):
  File "/usr/local/bin/patched_bench_helper.py", line 48, in <module>
    raise SystemExit(main())
  File "/usr/local/bin/patched_bench_helper.py", line 43, in main
    frappe.utils.bench_helper.main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    commands = get_app_groups()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 25, in get_app_groups
    for app in get_apps():
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 102, in get_apps
    return frappe.get_all_apps(with_internal_apps=False, sites_path=".")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1385, in get_all_apps
    apps = get_file_items(os.path.join(sites_path, "apps.txt"), raise_not_found=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1533, in get_file_items
    content = read_file(path, raise_not_found=raise_not_found)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1561, in read_file
    raise OSError(f"{path} Not Found")
OSError: b'./apps.txt' Not Found
Traceback (most recent call last):
  File "/usr/local/bin/patched_bench_helper.py", line 48, in <module>
    raise SystemExit(main())
  File "/usr/local/bin/patched_bench_helper.py", line 43, in main
    frappe.utils.bench_helper.main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    commands = get_app_groups()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 25, in get_app_groups
    for app in get_apps():
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 102, in get_apps
    return frappe.get_all_apps(with_internal_apps=False, sites_path=".")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1385, in get_all_apps
    apps = get_file_items(os.path.join(sites_path, "apps.txt"), raise_not_found=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1533, in get_file_items
    content = read_file(path, raise_not_found=raise_not_found)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1561, in read_file
    raise OSError(f"{path} Not Found")
OSError: b'./apps.txt' Not Found
```

for frappe_docker_queue-short_1
```
root@p-erpnext-01:/opt/frappe_docker# docker logs frappe_docker_queue-short_1
Traceback (most recent call last):
  File "/usr/local/bin/patched_bench_helper.py", line 48, in <module>
    raise SystemExit(main())
  File "/usr/local/bin/patched_bench_helper.py", line 43, in main
    frappe.utils.bench_helper.main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    commands = get_app_groups()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 25, in get_app_groups
    for app in get_apps():
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 102, in get_apps
    return frappe.get_all_apps(with_internal_apps=False, sites_path=".")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1385, in get_all_apps
    apps = get_file_items(os.path.join(sites_path, "apps.txt"), raise_not_found=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1533, in get_file_items
    content = read_file(path, raise_not_found=raise_not_found)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1561, in read_file
    raise OSError(f"{path} Not Found")
OSError: b'./apps.txt' Not Found
Traceback (most recent call last):
  File "/usr/local/bin/patched_bench_helper.py", line 48, in <module>
    raise SystemExit(main())
  File "/usr/local/bin/patched_bench_helper.py", line 43, in main
    frappe.utils.bench_helper.main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    commands = get_app_groups()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 25, in get_app_groups
    for app in get_apps():
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 102, in get_apps
    return frappe.get_all_apps(with_internal_apps=False, sites_path=".")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1385, in get_all_apps
    apps = get_file_items(os.path.join(sites_path, "apps.txt"), raise_not_found=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1533, in get_file_items
    content = read_file(path, raise_not_found=raise_not_found)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1561, in read_file
    raise OSError(f"{path} Not Found")
OSError: b'./apps.txt' Not Found
```

for frappe_docker_queue-default_
```
root@p-erpnext-01:/opt/frappe_docker# docker logs frappe_docker_queue-default_1
Traceback (most recent call last):
  File "/usr/local/bin/patched_bench_helper.py", line 48, in <module>
    raise SystemExit(main())
  File "/usr/local/bin/patched_bench_helper.py", line 43, in main
    frappe.utils.bench_helper.main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    commands = get_app_groups()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 25, in get_app_groups
    for app in get_apps():
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 102, in get_apps
    return frappe.get_all_apps(with_internal_apps=False, sites_path=".")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1385, in get_all_apps
    apps = get_file_items(os.path.join(sites_path, "apps.txt"), raise_not_found=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1533, in get_file_items
    content = read_file(path, raise_not_found=raise_not_found)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1561, in read_file
    raise OSError(f"{path} Not Found")
OSError: b'./apps.txt' Not Found
Traceback (most recent call last):
  File "/usr/local/bin/patched_bench_helper.py", line 48, in <module>
    raise SystemExit(main())
  File "/usr/local/bin/patched_bench_helper.py", line 43, in main
    frappe.utils.bench_helper.main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    commands = get_app_groups()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 25, in get_app_groups
    for app in get_apps():
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 102, in get_apps
    return frappe.get_all_apps(with_internal_apps=False, sites_path=".")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1385, in get_all_apps
    apps = get_file_items(os.path.join(sites_path, "apps.txt"), raise_not_found=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1533, in get_file_items
    content = read_file(path, raise_not_found=raise_not_found)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1561, in read_file
    raise OSError(f"{path} Not Found")
OSError: b'./apps.txt' Not Found
```

and here is the `.env`
```
root@p-erpnext-01:/opt/frappe_docker# cat .env
# Reference: https://github.com/frappe/frappe_docker/blob/main/docs/images-and-compose-files.md

FRAPPE_VERSION=v14.0.2

# Only with ERPNext override
ERPNEXT_VERSION=v14.0.0

DB_PASSWORD=secure-pass

# Only if you use external database
DB_HOST=mariadb
DB_PORT=3306

# Only if you use external Redis
REDIS_CACHE=redis:6379/0
REDIS_QUEUE=redis:6379/1
REDIS_SOCKETIO=redis:6379/2

# Only with HTTPS override
LETSENCRYPT_EMAIL=infra@tlab.co.id

# These environment variables are not required.

# Default value is `$$host` which resolves site by host. For example, if your host is `example.com`,
# site's name should be `example.com`, or if host is `127.0.0.1` (local debugging), it should be `127.0.0.1`.
# This variable allows to override described behavior. Let's say you create site named `mysite`
# and do want to access it by `127.0.0.1` host. Than you would set this variable to `mysite`.
FRAPPE_SITE_NAME_HEADER="some-domain"

# Default value is `127.0.0.1`. Set IP address as our trusted upstream address.
UPSTREAM_REAL_IP_ADDRESS=

# Default value is `X-Forwarded-For`. Set request header field whose value will be used to replace the client address
UPSTREAM_REAL_IP_HEADER=

# Allowed values are on|off. Default value is `off`. If recursive search is disabled,
# the original client address that matches one of the trusted addresses
# is replaced by the last address sent in the request header field defined by the real_ip_header directive.
# If recursive search is enabled, the original client address that matches one of the trusted addresses is replaced by the last non-trusted address sent in the request header field.
UPSTREAM_REAL_IP_RECURSIVE=
```

**Comment by revant** [comment]
images used in pwd.yml are production images.
if it works for you, tweak and use it.
