### ISSUE TITLE
RuntimeError: no object bound to conf

### ISSUE THREAD

**Issue by sdfateh** [frappe/frappe_docker#993]
## Description of the issue
When building new images,

Any advice?

### Stacktrace / full error message if available

```
+ APP=CUSTOM_APP
+ cd /home/frappe/frappe-bench
+ rm -rf apps/CUSTOM_APP/.git
+ env/bin/pip install -e apps/CUSTOM_APP
Obtaining file:///home/frappe/frappe-bench/apps/CUSTOM_APP
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      Traceback (most recent call last):
        File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/werkzeug/local.py", line 72, in __getattr__
          return self.__storage__[self.__ident_func__()][name]
      KeyError: 'conf'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/werkzeug/local.py", line 309, in _get_current_object
          return getattr(self.__local, self.__name__)
        File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/werkzeug/local.py", line 74, in __getattr__
          raise AttributeError(name)
      AttributeError: conf
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/frappe/frappe-bench/apps/CUSTOM_APP/setup.py", line 7, in <module>
          from CUSTOM_APP import __version__ as version
        File "/home/frappe/frappe-bench/apps/CUSTOM_APP/CUSTOM_APP/__init__.py", line 2, in <module>
          from erpnext.accounts.doctype.sales_invoice.sales_invoice import SalesInvoice
        File "/home/frappe/frappe-bench/apps/erpnext/erpnext/__init__.py", line 5, in <module>
          from erpnext.hooks import regional_overrides
        File "/home/frappe/frappe-bench/apps/erpnext/erpnext/hooks.py", line 115, in <module>
          "defaults": {"doctype": "Sales Order", "parents": [{"label": _("Orders"), "route": "orders"}]},
        File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 111, in _
          all_translations = get_all_translations(lang)
        File "/home/frappe/frappe-bench/apps/frappe/frappe/translate.py", line 292, in get_all_translations
          return frappe.cache().hget(MERGED_TRANSLATION_KEY, lang, generator=_merge_translations)
        File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 360, in cache
          redis_server = RedisWrapper.from_url(conf.get("redis_cache") or "redis://localhost:11311")
        File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/werkzeug/local.py", line 348, in __getattr__
          return getattr(self._get_current_object(), name)
        File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/werkzeug/local.py", line 311, in _get_current_object
          raise RuntimeError("no object bound to %s" % self.__name__)
      RuntimeError: no object bound to conf
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
The command '/bin/sh -c install-app CUSTOM_APP' returned a non-zero code: 1

```

**Comment by revant** [comment]
no idea, check your app code. try working app. try fresh new app. check for difference.

**Comment by sdfateh** [comment]
It's a frappe framework issue, the do revert, and everything is now good.
